### ISSUE TITLE
Check all called functions at runtime

### ISSUE THREAD

**Issue by The-Compiler** [agronholm/typeguard#1]
When adding type hints to some bigger project with good test coverage, it'd be nice to be able to typecheck _anything_ which is called and annotated rather than doing so selectively.

This would be possible using an import hook or `sys.settrace` possibly.

I'm aware this is rather "weird" and breaks e.g. debuggers, but I imagine it as a separate "mode" you run your tests under selectively, similar to how people e.g. run tests without coverage locally (for speed), and with coverage on a CI.

I might work on this myself once I start using type annotations in my project, but it might take me a few months since there's more important stuff to do first :wink:

**Comment by agronholm** [comment]
It appears that this is impossible to implement because when a settrace hook raises an exception, the hook is reset to `None`, as evidenced by the failing assert in this snippet:
```python
import sys


def debugger(frame, event, arg):
    if event == 'call' and raise_exception:
        raise Exception('blah')


def foo():
    print('foo')

sys.settrace(debugger)
raise_exception = True
try:
    foo()
except Exception:
    pass
finally:
    raise_exception = False

assert sys.gettrace() is not None

```

**Comment by agronholm** [comment]
I lied, I added this in 69ce354d74b9de0cee0efc1b6509e8bb2e51ca47. It just emits warnings instead of raising exceptions since that would reset the profiler hook.
