### ISSUE TITLE
*args and **kwargs not according to PEP 484

### ISSUE THREAD

**Issue by jlibovicky** [agronholm/typeguard#10]
Hi, [PEP 484](https://www.python.org/dev/peps/pep-0484/#arbitrary-argument-lists-and-default-argument-values) says `*args` and `**kwargs` (e.g., `**kwargs: int`) should by annotated only by their value types and the type of the resulting dict (e.g., `Dict[str, int]`) should be deduced. 

`check_argument_types()`, however, required the dict in the annotation which makes it impossible to [mypy](http://mypy-lang.org/) for static type checking and typeguard at the same time.

**Comment by agronholm** [comment]
Odd that I had not notice this before. I will of course fix it as soon as I can.
