### ISSUE TITLE
@typechecked with @typing.overload

### ISSUE THREAD

**Issue by twoertwein** [agronholm/typeguard#100]
Can `@typechecked` be used with overloaded functions?

Here is a short example which results in a warning (UserWarning: no type annotations present -- not typechecking buffered_iterator)

```py
from typing import Callable, Iterable, TypeVar, overload
from typeguard import typechecked

ANY = TypeVar("ANY")
ANY2 = TypeVar("ANY2")

def identity(item: ANY) -> ANY:
    return item

@overload
def buffered_iterator(iterator: Iterable[ANY], size: int) -> Iterable[ANY]:
    # only a stub for typing
     ...

@overload
def buffered_iterator(
        iterator: Iterable[ANY2], size: int, function: Callable[[ANY2], ANY]
) -> Iterable[ANY]:
    # only a stub for typing
     ...

@typechecked
def buffered_iterator(iterator, size=3, function=identity):
    # actual implementation

```

**Comment by agronholm** [comment]
Not at this time because the functions decorated with `@overload` are overwritten with the real one. However, with the import hook it would be possible to at least store this information somewhere since it walks the AST.

**Comment by EPronovost** [comment]
FWIW I believe with the above code snippet mypy would actually not type check the contents of the `buffered_iterator` implementation.  https://mypy.readthedocs.io/en/stable/more_types.html#type-checking-the-implementation
The suggested approach is to annotate the implementation with the union of all the variants.  Still, it would be nice to explicitly check that one of the variants was satisfied.
