### ISSUE TITLE
check_type does not check required fields when mixing required and non-required fields in TypedDict

### ISSUE THREAD

**Issue by ksaaskil** [agronholm/typeguard#101]
Hi, thanks for the awesome library! A recent fix for an issue (https://github.com/agronholm/typeguard/issues/94) added support for totality in `TypedDict`, thanks for that! I'm trying to mix required and non-required fields in `TypedDict` as instructed in [mypy documentation](https://mypy.readthedocs.io/en/latest/more_types.html#mixing-required-and-non-required-items):
```python
class MovieBase(TypedDict):
    name: str
    year: int

class Movie(MovieBase, total=False):
    based_on: str
```
This definition should make `name` and `year` required fields in `Movie`. 

However, `check_type` does not seem to complain if those are missing:
```python
from typeguard import check_type

movie = Movie()   # Missing `name` and `year` , type-checker complains
check_type("movie", movie, Movie)  # Does not raise error but it should?
```
Any idea what might be wrong here? Thanks!

**Comment by agronholm** [comment]
How am I going to extract the information about `MovieBase` at run time? It doesn't show up in the MRO or the list of base classes of `Movie`.

**Comment by ksaaskil** [comment]
I have no idea how that should be implemented 🙂  If it cannot be, maybe we could add a note to the documentation?

**Comment by agronholm** [comment]
Sounds reasonable.

**Comment by antonagestam** [comment]
Note that this situation [is addressed in Python 3.9 ](https://github.com/python/cpython/pull/17214) with dunder attributes for `__required_keys__` and `__optional_keys__`. Would you consider reopening this? :)

**Comment by agronholm** [comment]
Sure.

**Comment by agronholm** [comment]
It seems the new patch was botched:
```
>>> DummyDict = TypedDict('DummyDict', {'x': int, 'y': str}, total=False)
>>> DummyDict.__required_keys__
frozenset({'x', 'y'})
```
It's ignoring the `total` argument.

**Comment by agronholm** [comment]
I've submitted a fix against CPython: https://github.com/python/cpython/pull/22736

If I add support for `__required_keys__`, then it will behave wrong with the 3.5 compatible syntax in Python 3.9.0. I'm not sure what to do.
