### ISSUE TITLE
Possibility to check types of elements of an iterable directly

### ISSUE THREAD

**Issue by jsh9** [agronholm/typeguard#102]
Even though we can specify something like `List[int]` or `Sequence[float]`, for some other common array-like data types (such as numpy array, or pandas Series), it is difficult to do so. (Neither numpy array or pandas Series is a `collections.abc.Sequence` yet.)

So I wonder if you can add a `check_element_type()` function that checks the type of each element of an iterable?

It can have the following signature:
```python
def check_element_type(arg_name, iterable, expected_type):
    ...
```

Alternatively, is it possible to enforce type checking of `Iterable[something]`? For example, currently, this following case doesn't raise an error:

```python
@typeguard.typechecked
def func1(x: Iterable[int]):
    print(x)

func1([1, 2, 3.4])  # doesn't raise any error
```

Thanks!

**Comment by agronholm** [comment]
The problem with this is that it requires wrapping around the `__iter__()` or `__aiter__()` methods and replacing the return value from those. Typeguard already does this for generators but doing this for any arbitrary iterables would not be as safe.

**Comment by jsh9** [comment]
The issue is that users don't know about this detail, and they will assume `Iterable[SomeType]` is guarded, when in reality it is not guarded.

If you think safety is an issue, can you add some code to show a warning to users who are trying to guard `Iterable[SomeType]`?

**Comment by agronholm** [comment]
Why would users think that it's guarded, when it's not mentioned on the list of supported `typing` types in the [documentation](https://typeguard.readthedocs.io/en/latest/#supported-typing-types)?

The warning makes little sense because it still works as expected with static type checkers.
