### ISSUE TITLE
The typechecked decorator hides arguments from inspect

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [agronholm/typeguard#107]
We would like in tensorflow addons to use typechecked in the public API. We would also like to check that new contributors don't forget to add the types when adding new functions. The probem is that we can't implement this check since typechecked doesn't play nice with inspect:

```python
import inspect
from typeguard import typechecked

def my_func(a: int, b: str):
    pass

print(inspect.getfullargspec(my_func).args)

my_func = typechecked(my_func)

print(inspect.getfullargspec(my_func).args)
```

```
['a', 'b']
[]
```

**Comment by gabrieldemarmiesse** [comment]
I noticed that I can do `inspect.unwrap` to fix the issue. I'll leave this issue open as maybe it can still be considered a bug?

**Comment by agronholm** [comment]
`inspect.getfullargspec()` should not be used. Use `inspect.signature()` which does the right thing by default.

**Comment by agronholm** [comment]
Also, if it works for your use case, I encourage you to use the import hook instead of explicitly adding `@typechecked` decorators to the code.

**Comment by gabrieldemarmiesse** [comment]
Thanks for your answer!
