### ISSUE TITLE
Autograph is incompatible with typeguard

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [agronholm/typeguard#111]
Hello, it's surely not the job of typeguard to change anything to be compatible, I'm just leaving the issue here in case somebody were to have the same issue and was looking for the reason.

The original issue is in the tensorflow repository: https://github.com/tensorflow/tensorflow/issues/36462

And thanks for this awesome tool!

**Comment by agronholm** [comment]
Looking at the upstream issue, this seems to have been resolved.
