### ISSUE TITLE
Typechecking for `typing.Union` or `typing.Iterable` is not working

### ISSUE THREAD

**Issue by kipstakkr** [agronholm/typeguard#112]
Hi,

I am trying to use the `typeguard.check_argument_types()` in my method in which one of the arguments has a type `Iterable[str]` or `Union[List[str], Tuple[str], Set[str]]`. Both were working for lists, but when I try to use it for tuples or sets it is throwing error stating
```
type of argument "x" must be one of (List, NoneType); got tuple instead
```

I don't whether I am doing something wrong, or if the method does not account for `Union` or `Iterable` types. Please help me with this issue.

**Comment by agronholm** [comment]
How exactly would you expect `Iterable` to be type checked? An iterable could be a generator that never stops yielding new values so the checker might end up in an infinite loop trying to type check the values. Even if not, the sequence read from the iterable is often not reproduceable.

As far as the Union problem goes, issue #65 exists for that already. The error message can be confusing. Can you point out that the error is a false positive though? If so, please provide a sample snippet.

**Comment by kipstakkr** [comment]
Yes. I too think `Iterable` is a bad option for validating types. 

And for `Union`, I think there is some issue with respect to the session (kernal) in jupyter environment. I tried it out after restarting the kernel and it worked fine.

Do u have any idea why this is the issue?

**Comment by agronholm** [comment]
No clue. I don't use Jupyter myself.

**Comment by kipstakkr** [comment]
No problem. I will close this issue for now and if anything seems reproducible, I will raise it in a different one. Thanks Alex.
