### ISSUE TITLE
Support for Python 2 type comments

### ISSUE THREAD

**Issue by rmorshea** [agronholm/typeguard#119]
Support for Python 2's type comments might have been purposefully omitted, but if not, it would be great to see. Here's an implementation from a competing project that could be used for inspiration:

- https://github.com/Stewori/pytypes/blob/master/pytypes/typecomment_parser.py

**Comment by agronholm** [comment]
Typeguard will not be doing any parsing of the source code, especially now that Python 2 has reached its end of life 3 months ago.

**Comment by Stewori** [comment]
For the record, this is readily possible via [@annotations](https://github.com/Stewori/pytypes#provide-info-from-type-comments-and-stubfiles-as-__annotations__-for-other-tools) (you can also apply this to [a whole module at once](https://github.com/Stewori/pytypes#global-mode-and-module-wide-mode)). It should well be possible to use typeguard on top. `@annotations` is made for this purpose, no need to reinvent the wheel! As a side effect it also enables type info from stubfiles.
