### ISSUE TITLE
PEP 563 -- Postponed Evaluation of Annotations

### ISSUE THREAD

**Issue by slide333333** [agronholm/typeguard#123]
Consider the following example:
```
from __future__ import annotations  # PEP 563

from typing import TypedDict

class Point2D(TypedDict):
    x: float
    y: float
```

Due to the `__future__` import `Point2D.__annotations__` now contains `{'x': ForwardRef('float'), 'y': ForwardRef('float')}` instead of `{'x': float, 'y': float}`.

As a consequence the type checking for any `TypedDict` attributes is not working any more. For example:
`check_type('Point2D', {'x': 3, 'y': 'not a float'}, Point2D)` does not raise.

This is somehow related to https://github.com/agronholm/typeguard/issues/62.

Edit:
As stated in PEP 563 the solution would be to just call `typing.get_type_hints` to evaluate the expressions:

> For code that uses type hints, the typing.get_type_hints(obj, globalns=None, localns=None) function correctly evaluates expressions back from its string form. Note that all valid code currently using __annotations__ should already be doing that since a type annotation can be expressed as a string literal.

**Comment by rfrowe** [comment]
Could also be related to #130
