### ISSUE TITLE
Functions with NoReturn return types fail to type check

### ISSUE THREAD

**Issue by rfrowe** [agronholm/typeguard#131]
## Reproduction
```python3
>>> from typing import NoReturn
>>> from typeguard import typechecked

>>> @typechecked
>>> def foo() -> NoReturn:
>>>    pass

>>> foo()
# AttributeError: '_SpecialForm' object has no attribute '__values__'
```

## Expected Behavior 

Passes type checking. (Although, maybe, it should fail because `NoReturn` shouldn't return but that's another conversation).

## Cause

#114

**Comment by agronholm** [comment]
It should not pass type checking.
