### ISSUE TITLE
Deactivating typeguard through environment variable or similar?

### ISSUE THREAD

**Issue by s-m-e** [agronholm/typeguard#133]
Great tool, thanks for building it!

Question: I have been adding `typeguard` to a larger project by decorating classes with `@typeguard.typechecked`. It works like a charm and certainly helps with testing, but it also has an impressively negative performance impact.

Is it possible to deactivate `typeguard` through an environment variable for e.g. production deployments (similar to `-OO` in Python for deactivating `assert` statements)?

**Comment by agronholm** [comment]
> Is it possible to deactivate typeguard through an environment variable for e.g. production deployments (similar to -OO in Python for deactivating assert statements)?

Yes, exactly the same way. This is explained in the documentation:

> The decorator also respects the optimized mode setting so it does nothing when the interpreter
   is running in optimized mode.

**Comment by s-m-e** [comment]
I read it a few times and apparently missed this. Sorry - and thanks for the help.
