### ISSUE TITLE
Python 3.7: ImportError: cannot import name 'Literal' from 'typing'

### ISSUE THREAD

**Issue by lgeiger** [agronholm/typeguard#134]
I just noticed in [one of our CI builds](https://github.com/larq/compute-engine/pull/399/checks?check_run_id=745958478#step:5:32)  that c6fa51ce3cc63b217f74e9fe761ec46e7a87bda9 broke support for Python 3.7 in cases where `typing_extensions` isn't installed on the system since `Literal` was only introduced in Python 3.8:
https://github.com/agronholm/typeguard/blob/0cdef35c5d6314dd807479bdb521386774902494/typeguard/__init__.py#L24-L27

Probably the easiest way to fix this would be to add `typing_extensions` as an requirement to `setup.py` for Python <=3.7 or to make the use of `Literal` inside `typeguard` optional.
@agronholm what do you think would be the best fix for this?

**Comment by agronholm** [comment]
Sorry about this. I've fixed this in 0c7d1e7df87e3cf8de6e407e2ee04df21691280d and released v2.9.1.

**Comment by agronholm** [comment]
And of course only after the release I realized that `NoReturn` was part of Python 3.6.2+ while `Literal` was introduced in 3.8.0.

**Comment by lgeiger** [comment]
Thanks for the quick fix :+1:
