### ISSUE TITLE
Forward refs not resolved correctly after updating to >=2.9.0

### ISSUE THREAD

**Issue by hlynurf** [agronholm/typeguard#135]
After updating to 2.9.1 forward refs are not being resolved correctly when typeguard is called from another file. Below is a minimal example I tried to come up with (will look a bit stupid). The error 

`test_typeguard.py`
```python
from typing import List, Union

import typeguard

from test_helper import test_type


class ListOfValues(object):
	def __init__(self, items: List['Value']) -> None:
		self.items = items


class Value(object):
	def __init__(self, name: str) -> None:
		self.name = name


obj = ListOfValues([])
test_type(obj, Union['Value', ListOfValues])
```
`test_helper.py`
```python
import typeguard


def test_type(obj, type_):
	typeguard.check_type('a', obj, type_)
```
Running this gives me the error 
```
Traceback (most recent call last):
  File "test_typeguard.py", line 19, in <module>
    test_type(obj, Union['Value', ListOfValues])
  File "/home/hlynur/code/dohop/test_helper.py", line 5, in test_type
    typeguard.check_type('a', obj, type_)
  File "/home/hlynur/.config/dohop/tools_venv3/lib/python3.7/site-packages/typeguard/__init__.py", line 593, in check_type
    checker_func(argname, value, expected_type, memo)
  File "/home/hlynur/.config/dohop/tools_venv3/lib/python3.7/site-packages/typeguard/__init__.py", line 410, in check_union
    check_type(argname, value, type_, memo)
  File "/home/hlynur/.config/dohop/tools_venv3/lib/python3.7/site-packages/typeguard/__init__.py", line 588, in check_type
    expected_type = resolve_forwardref(expected_type, memo)
  File "/home/hlynur/.config/dohop/tools_venv3/lib/python3.7/site-packages/typeguard/__init__.py", line 166, in resolve_forwardref
    return evaluate_forwardref(maybe_ref, memo.globals, memo.locals)
  File "/home/hlynur/.pyenv/versions/3.7.4/lib/python3.7/typing.py", line 467, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Value' is not defined
```
The forward reference to Value is not evaluated correctly in this case.
The error does not occur in versions < 2.9.0 and the error does not occur if the helper function is inside test_typeguard.py.

**Comment by agronholm** [comment]
How would you suggest typeguard should determine which module it needs to look in to find the forward reference? For this very reason `check_type()` now comes with optional `globals` and `locals` parameters.

The reason it worked before was probably because forward references weren't looked up at all, completely bypassing the check.

**Comment by hlynurf** [comment]
I understand the issue better now. For some reason, I thought that maybe the forward reference object would bind the scope it was created in.

I managed to solve my issue by using the `globals` and `locals` parameters and referencing the call stack one layer deeper for helper functions in a separate module.

**Comment by agronholm** [comment]
I wish I had a better solution to offer, but I have not managed to extract any useful information from the forward reference objects.
