### ISSUE TITLE
Type checking annotated dicts: object has no attribute `__total__`

### ISSUE THREAD

**Issue by Granitosaurus** [agronholm/typeguard#136]
Typeguard supports TypedDicts but it almost supports annotated dicts too however since annotated dicts don't implement `__total__` typeguard's checks fail:

```
class MyDict(dict):
    name: str

check_type(MyDict(name='foo'), MyDict)
```

This throws:

```
AttributeError: type object 'MyDict' has no attribute '__total__
```

This can be fixed by implementing `__total__` in dict subclass and it seems like typeguard functions perfectly fine afterwards:

```
class MyDict(dict):
    name: str
    __total__ = False

check_type(MyDict(name='foo'), MyDict)
# no error
```

Would be great if this would be patched so it would be possible to check annotated dicts as typeddicts are not always available.

-----

Traceback points to this function:

```
    def check_typed_dict(argname: str, value, expected_type, memo: Optional[_CallMemo]) -> None:
        expected_keys = frozenset(expected_type.__annotations__)
        existing_keys = frozenset(value)
    
        extra_keys = existing_keys - expected_keys
        if extra_keys:
            keys_formatted = ', '.join('"{}"'.format(key) for key in sorted(extra_keys))
            raise TypeError('extra key(s) ({}) in {}'.format(keys_formatted, argname))
    
>       if expected_type.__total__:
```

**Comment by agronholm** [comment]
Are these even supported by mypy?

**Comment by Granitosaurus** [comment]
> Are these even supported by mypy?

What do you mean? 
From what I've gathered - no `mypy` does not raise error for dict annotations :(

```
class MyItem(dict):
    age: int

item = MyItem()
item['age'] = 'not a number'
print(item)
```

Thought we're using `typeguard` mostly for `check_type` function and it kinda sucks that it fails to check annotated dicts when it's so close to being able to :|

**Comment by agronholm** [comment]
Why would you expect it to support this if it's not supported by mypy? Why not use `TypedDict` instead?

**Comment by Granitosaurus** [comment]
@agronholm not sure what are you getting at. Should I open up an issue with mypy? The whole thing is a complete spaghetti. If you want to type check a dict subclass you need to have a second completely redundant object which is extremely silly:

```
class MyObject(dict):
    name: str
    ...

class MyObjectType(TypedDict):
    name: str

check_type(MyObject(name=foo), MyObjectType)
```

I'm not saying there's an issue with typeguard per se but that it could totally fix this by patching `__total__` check to be optional.

**Comment by agronholm** [comment]
What would the value of `__total__` be in such cases then, and why can't you create a superclass that supplies this?

I didn't know typeguard would even get this far. Because of said restrictions, typeguard has to apply a number of heuristics to determine if the annotation is in fact a TypedDict. It checks if it's a dict and has `__annotations__`, which makes it mistake your subclass for a `TypedDict`. I'm reluctant to support something that isn't part of any spec.

**Comment by Granitosaurus** [comment]
> What would the value of __total__ be in such cases then, and why can't you create a superclass that supplies this?

I'd say it should default to False as totality should be optional (in the same spirit type checking is optional) 

We indeed use this :)

```
class Item(dict):
    __total__ = False
```

I definitely see your concerns of supporting this as it seems to be inherit issue with python and  `TypedDict`. I guess we can wait and see how `TypedDict` progresses and maybe bring it up with mypy. 
In the meantime I hadn't seen any issues caused by patching in `__total__ = False` with typeguard so if someone suffers from this issue there's an easy solution for the time being.
