### ISSUE TITLE
@typechecked passes when bool is passed to int or float annotated parameter

### ISSUE THREAD

**Issue by snk4tr** [agronholm/typeguard#137]
**Describe the bug**
`typechecked` check passes when should not in cases when:
- parameter is annotated with `int` or `float` type annotation
- `bool` value is passes

**To Reproduce**
1. Install `typeguard==2.9.1`
2. Run the following code snippet:
```python
from typeguard import typechecked

@typechecked
def foo(a: float) -> None:
    pass

foo(True)
```

**Expected behavior**
TypeError is raised

**Screenshots**

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/24959314/87169789-230d7e00-c2d9-11ea-8abb-c65de8bb9bfd.png">

**Comment by agronholm** [comment]
Mypy does not complain about that either. Why should typeguard behave differently? The `bool` type is a subclass of `int`, so according to the [numeric tower](https://www.python.org/dev/peps/pep-3141/), `bool` is compatible with `float`.

**Comment by snk4tr** [comment]
@agronholm thank you for your reply!
Indeed, these types appear to be compatible which I did not know about. 

Then the question is settled, closing this issue.
