### ISSUE TITLE
TypeError: 'type' object is not subscriptable with subprocess.CompletedProcess[str]

### ISSUE THREAD

**Issue by cjolowicz** [agronholm/typeguard#138]
The type annotations provided for subprocess by typeshed define CompletedProcess as a generic type, even though it is a simple class in the standard library. This can be made to work with `from future import __annotations__` a.k.a postponed type evaluation ([PEP 563]). Unfortunately, it does not currently work with typeguard.

[PEP 563]: https://www.python.org/dev/peps/pep-0563/

**Without typeguard:**

```python
from future import __annotations__
import subprocess

def foo() -> subprocess.CompletedProcess[str]:
    return subprocess.run(["true"], text=True)

foo()
```

With the future import, the code runs without exceptions. Without the future import, the code raises `TypeError: 'type' object is not subscriptable`.

**With typeguard:**

```python
from future import __annotations__
import subprocess

from typeguard import typechecked

@typechecked
def foo() -> subprocess.CompletedProcess[str]:
    return subprocess.run(["true"], text=True)

foo()
```

This raises `TypeError: 'type' object is not subscriptable` even with the future import.

```
Traceback (most recent call last):
  File "foo-typeguard.py", line 10, in <module>
    foo()
  File "path/to/venv/lib/python3.8/site-packages/typeguard/__init__.py", line 838, in wrapper
    memo = _CallMemo(python_func, _localns, args=args, kwargs=kwargs)
  File "path/to/venv/lib/python3.8/site-packages/typeguard/__init__.py", line 112, in __init__
    hints = get_type_hints(func, localns=frame_locals)
  File "/Users/cjolowicz/.pyenv/versions/3.8.3/lib/python3.8/typing.py", line 1264, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/Users/cjolowicz/.pyenv/versions/3.8.3/lib/python3.8/typing.py", line 270, in _eval_type
    return t._evaluate(globalns, localns)
  File "/Users/cjolowicz/.pyenv/versions/3.8.3/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: 'type' object is not subscriptable
```

**Comment by agronholm** [comment]
The `subprocess.CompletedProcess[str]` type is not generic, so why would you expect this to work?

**Comment by cjolowicz** [comment]
Right. So I guess my question is, how can I run my test suite with the typeguard pytest plugin, if my codebase uses `subprocess.run` with the types provided by typeshed?

**Comment by agronholm** [comment]
Since typeguard's checks happen at run time, the types used must be compatible with the actual run-time classes. Typeshed is not relevant here. You must strip the generics from this class or use [@no_type_check](https://docs.python.org/3/library/typing.html#typing.no_type_check) if you intend to use typeguard's pytest plugin with this code.

**Comment by cjolowicz** [comment]
> You must strip the generics from this annotation

You mean omit the type subscript? Then this won't type-check with mypy:

```
error: Missing type parameters for generic type "CompletedProcess"  [type-arg]
```

> or use @no_type_check 

Hm but then it won't be type checked by mypy either 🤔 ... It would be great if there was a way to specifically exclude functions from typeguard's import hook, while still allowing static type checks. Is there, or do you have anything like that planned?

FWIW it is possible to work around the problem with `subprocess.CompletedProcess` using a type alias and `typing.TYPE_CHECKING`:

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    CompletedProcess = subprocess.CompletedProcess[str]
else:
    CompletedProcess = subprocess.CompletedProcess
```

**Comment by agronholm** [comment]
> Hm but then it won't be type checked by mypy either thinking ... It would be great if there was a way to specifically exclude functions from typeguard's import hook, while still allowing static type checks. Is there, or do you have anything like that planned?

I haven't had anything like that planned because a conflict like this has never come up before. I cannot offer a better solution than your workaround right now. Given the steps Python 3.9 has taken, maybe we'll finally see generics in the standard library code one day (outside of the `typing` module that is).
