### ISSUE TITLE
Errors reported from TypeVars that include generics

### ISSUE THREAD

**Issue by sjjessop** [agronholm/typeguard#139]
This is similar to #43, but that issue was invalid because the code failed mypy, whereas this code passes mypy:

```python
from typing import Any, List, TypeVar

from typeguard import check_argument_types

T = TypeVar('T', int, List[Any])


def foo(a: T, b: T) -> T:
    assert check_argument_types()
    return a + b


def test_foo() -> None:
    assert foo(1, 2) == 3  # OK
    assert foo([1, 2], [3, 4]) == [1, 2, 3, 4]


if __name__ == '__main__':
    test_foo()
```

Results (with my terminal prompt and file paths truncated) are:

```terminal
$ flake8 guardtest.py

$ mypy guardtest.py
Success: no issues found in 1 source file

$ python guardtest.py
Traceback (most recent call last):
  File "guardtest.py", line 19, in <module>
    test_foo()
  File "guardtest.py", line 15, in test_foo
    assert foo([1, 2], [3, 4]) == [1, 2, 3, 4]
  File "guardtest.py", line 10, in foo
    assert check_argument_types()
  File "lib/site-packages/typeguard/__init__.py", line 700, in check_argument_types
    raise exc from None
  File "lib/site-packages/typeguard/__init__.py", line 698, in check_argument_types
    check_type(description, value, expected_type, memo)
  File "lib/site-packages/typeguard/__init__.py", line 625, in check_type
    check_typevar(argname, value, expected_type, memo)
  File "lib/site-packages/typeguard/__init__.py", line 453, in check_typevar
    format(subject, typelist, qualified_name(value_type)))
TypeError: type of argument "a" must be one of (int, List); got list instead
```

I'm using 2.9.1 of typeguard, 3.7.3 of Python, 0.782 of mypy

I see the same result with `@typechecked`, or with `List[int]` in place of `List[Any]`, or with `Iterable` in place of `List`.

typeguard is happy if I replace the TypeVar with a Union, but of course then mypy is not happy, because `a` and `b` are no longer constrained by the TypeVar to avoid trying to add `int` and `list`. So the issue seems to be that typeguard understands generics in Unions, but not in TypeVars.

IMO typeguard should permit a list to satisfy a constrained TypeVar where one of the constraints is List (or some other suitable generic type). My real code that landed me here was supplying a generator, where Iterable was expected in my TypeVar, so that's the case I *truly* care about!

**Comment by sjjessop** [comment]
It's possible that we disagree over the interpretation of the note in PEP-484: "TypeVar supports constraining parametric types to a fixed set of possible types (note: those types cannot be parameterized by type variables)". I took this to mean that you're not supposed to do `T = TypeVar('T', int, List[U])`, where `U` is another `TypeVar`. Possibly you interpret it to mean that since `List` is parameterized by a type variable, therefore `List` cannot be used in a TypeVar constraint at all, not even as `List[Any]`?

If that's the disagreement, then I don't claim to have any particular insight into what PEP-484 means.

**Comment by sjjessop** [comment]
Oh, I've found an even simpler case which mypy accepts and typeguard rejects, and I think it's because of the same piece of code in `check_typevar`:

```python
class Super:
    pass


class Sub(Super):
    pass


T = TypeVar('T', int, Super)


def first(a: T, b: T) -> T:
    assert check_argument_types()
    return a


def test_first() -> None:
    assert first(1, 2) == 1
    assert first(Sub(), Super())
```

`mypy` apparently is happy to deduce `T` as `Super` and then permit any instance of `Super` as the argument, whereas typeguard requires the type of the argument to be exactly `T`.

**Comment by sjjessop** [comment]
I've done a quick check with `pytypes`, and it rejects `first(Sub(), Super())` but accepts `first(Sub(), Sub())` (which typeguard rejects). So, it disagrees with both of us as to how TypeVars should be deduced, but agrees with you that once deduced the argument type needs to exactly match it. It accepts my first test case with the `List[Any]` constraint.

**Comment by agronholm** [comment]
Typeguard handles type variables somewhat incorrectly. This largely stems from an initial misunderstanding of how constraints and co-/contravariance works. Fixing this is non-trivial and I don't expect this to get done before v3.0. However, I think I may be able to help you in the short term. The `check_typevar()` function is currently a bit too restrictive about how it checks value candidates against the constraint. I will try to fix that and submit a PR for your review then.

**Comment by agronholm** [comment]
Hm, looks like it wasn't that easy after all. The check really needs a whole different approach to it to be correct.

**Comment by sjjessop** [comment]
Thanks very much for looking into it so quickly. Totally understandable if it has to wait for a more thorough rewrite.

I thought the "naive" fix would be to replace `if value_type not in constraints:` in `check_typevar`, with a loop calling `check_type` for each constraint in turn, like in `check_union`. Is that (part of) the short-term approach that you tried and rejected? Unfortunately I don't know whether that change is correct, only that it's strictly more permissive than the current code...

For my own purposes I'm happy to err towards permissiveness. The main goal for my type annotations is documentation. So what I most want is an automated test that the types that end up my docs aren't lies. mypy is mostly OK for that, but at the cost of having to help it out where it can't deduce everything. Finding bugs elsewhere than in my function signatures is a nice-to-have side-effect! So I might try my naive fix and see if that gets me further forward.

**Comment by agronholm** [comment]
I'll see what I can do, but these changes break a number of existing tests, although many of them ought to be removed anyway because they test for the wrong things.

**Comment by diogavila** [comment]
@agronholm any expectation on new release with a fix?

**Comment by agronholm** [comment]
None. I'm way too busy with other projects and my paid work. If somebody else wants to pick up the torch on this, I can support that.
