### ISSUE TITLE
question: use to check type compatibility?

### ISSUE THREAD

**Issue by shaunc** [agronholm/typeguard#140]
I am writing a distributed execution system, in which messages are sent among task nodes implemented by python functions. Before they are run, the flow graph is "compiled". During this step, I would like to check types of messages. 

I can get the type annotation of a message from both sender and receiver, and am searching for a way to check if these two types are compatible with one another. (In particular, if a message created by the sender will be of the type expected by the receiver, if the sender respects the type annotation.) Can I do this with typeguard? An example or pointer to the docs would be much appreciated if it is possible. If not, any suggestions as to another package that can help me?

**Comment by agronholm** [comment]
Typeguard does not currently support checking for the compatibility of a type against another. It only deals with checking if a value matches an annotation. This is something that will have to be implemented for v3.0, whenever I have the time and inspiration for that.

**Comment by shaunc** [comment]
Thanks for the quick reply! Best wishes for v3. :)

**Comment by agronholm** [comment]
To add, I'm not aware of any other package that offers run-time type compatibility checks. But then again, I'm not all-knowing.

**Comment by Stewori** [comment]
Actually, this is a central functionality in pytypes, see [pytypes.is_subtype](https://github.com/Stewori/pytypes#is_subtypesubtype-supertype-bound_genericnone). Typechecking and the typesafe overload decorator are built around this. However, not all typing features are supported yet, especially not the newer ones (Python 3.7+). Note that there are somewhat different levels of this typesafe piping idea. Just to check whether a given type can be used where some other given type is required is one thing (can be done with is_subtype). Telling whether a tuple of types can be fed into a given function signature, possibly including default values, varargs and varkw (and upcoming position-only args) is the other. The overwrite decorator does indeed check against function signatures with all these issues to consider, but it's still a todo to expose this second type of checking as a comfortably usable API.

**Comment by shaunc** [comment]
@Stewori -- thanks! I'll definitely check it out. I'm checking defaults etc, and remapping messages to keyword arguments, already, so `is_subtype` might be sufficient for my needs.

**Comment by Stewori** [comment]
int/float compatibility is granted by the PEP 484 numeric tower (also under all sorts of nesting; beware of lists and dicts though: for writable datatypes there maybe co/contravariance issues). Various other stuff can be modeled by ducktyping, generics and subclasshooks. Depends on your specific usecase in the end if this suites you.

**Comment by shaunc** [comment]
Very good -- thanks! We do use/encourage TypedDicts -- do these also fall under "beware of lists and dicts"?

**Comment by Stewori** [comment]
TypedDict is not supported at the moment. If it was supported, the subtleties illustrated in https://www.python.org/dev/peps/pep-0589/#type-consistency would apply, i.e. presumably no compatibility between TypedDict and Dict or Mapping can be expected.

**Comment by agronholm** [comment]
TypedDict is problematic for runtime checkers, as when inheriting from another TypedDict it is not retained in the MRO, thus making it impossible to determine the overall totality status of the dict at runtime.

**Comment by Stewori** [comment]
Interesting. Sure there is not some dirty trick to get it anyway? From my experience, in Python there is literally always some dirty trick available. Sadly, I never needed as many dirty tricks as for typing.

**Comment by shaunc** [comment]
It does have an "__annotations__" member -- 
```
In [2]: from typing import TypedDict                                                                                                               

In [3]: class Foo(TypedDict): 
   ...:     foo: int 
   ...:                                                                                                                                            

In [4]: class Bar(Foo): 
   ...:     bar: str 
   ...:                                                                                                                                            

In [5]: Bar.__annotations__                                                                                                                        
Out[5]: {'bar': str, 'foo': int}
```

**Comment by agronholm** [comment]
The annotations member only tells which fields it has, not where they came from.

**Comment by shaunc** [comment]
Hmm. I'm sure there is something I don't understand that you are very familiar with. To determine whether one dict is substitutable for another, all we need to know is the types of the fields of the two dictionaries, right? As far as I know (and maybe, again, I don't understand something) it would seem that the inheritance structure doesn't matter for this?

**Comment by agronholm** [comment]
Typeguard checks the values of fields against their declared types too. That's why it needs to know if the keys need to exist in the dict or not. If you inherit one TypedDict from another and they have different `totality` settings, there is no way to know that at run time.

**Comment by shaunc** [comment]
Hmm... just reading the thread that led to "totality" :( ... does seem like a hack -- would much prefer `OptionalItem` (or whatever...). Um, but doesn't the totality setting of the most derived class override? Ah --

>  The totality flag only applies to items defined in the body of the TypedDict definition. Inherited items won't be affected, and instead use totality of the TypedDict type where they were defined. This makes it possible to have a combination of required and non-required keys in a single TypedDict type.

Hmm... seems to be an implementation bug in PEP589 then.

**Comment by Stewori** [comment]
> The only way to get the totality information is static code analysis.

Alex, where is your fantasy? I wouldn't have called it *dirty* tricks if it wouldn't include monkeypatching:

```
from typing import TypedDict, _TypedDictMeta

_tdm_new = _TypedDictMeta.__new__
def _tdm_better_new(cls, name, bases, ns, total=True):
	res = _tdm_new(cls, name, bases, ns, total)
	res.tbases = bases
	return res
_TypedDictMeta.__new__ = _tdm_better_new

class Foo(TypedDict, total=False):
	foo: int

class Bar(Foo):
	bar: str

print(Bar.__annotations__) # {'bar': <class 'str'>, 'foo': <class 'int'>}
print(Bar.tbases) # (<class '__main__.Foo'>,)
print(Bar.__total__) # True
for base in Bar.tbases: print(base.__total__) # False
```

**Comment by shaunc** [comment]
@Stewori -- nice! :)

**Comment by Stewori** [comment]
I don't think there was an actual reason. I believe it is just what you said:
> an implementation bug in PEP589 then

**Comment by agronholm** [comment]
> I wonder why they hid the bases in the first place?

They were only thinking of static type checkers. That's the general mindset I see when trying to work with the `typing` module.
