### ISSUE TITLE
Q: should docs © year be updated?

### ISSUE THREAD

**Issue by dimaqq** [agronholm/typeguard#146]
When I discovered `typeguard` I landed on the docs page.
I saw `Copyright 2015` at the bottom of the page and thought that the project was abandoned.
Then I found the repo, saw that it was active, and thought that the docs were hopelessly out of date.

Is it only me, or is copyright year possibly meaningful to others too?

**Comment by agronholm** [comment]
The copyright year was set at the beginning of the project. I simply don't have the time/attention to keep an **end** year up to date in all my projects, thus I don't set it. There are any number of ways to see if a project is active: looking at the [release history](https://pypi.org/project/typeguard/#history) on PyPI, looking at the [commit history](https://github.com/agronholm/typeguard/commits/master) or the [version history](https://typeguard.readthedocs.io/en/latest/versionhistory.html) in the documentation.
