### ISSUE TITLE
support recursive import hook when using pytest plugin

### ISSUE THREAD

**Issue by HitLuca** [agronholm/typeguard#147]
When using typeguard and its pytest plugin, I found that the `--typeguard-packages` is not recursive, meaning that if a project is structured as a series of subfolders the typeguard hook will only be applied to the root level ones.

example:

```
test/a.py
test/b/b.py
test/c/c.py
```

`pytest --typeguard-packages=test` will only add the `@typeguard` decorator to `test/a.py`.

I also tried `--typeguard-packages=test.*`, `--typeguard-packages=test.**`, `--typeguard-packages=test/**` etc. with no luck

**Comment by HitLuca** [comment]
A workaround I found was to add `import_hook('test')` in `tests/conftest.py` but having a config file option would be much cleaner, as sometimes the `conftest.py` file has to be created just for this purpose

**Comment by agronholm** [comment]
Is `test` a namespace package or are you playing around with `PYTHONPATH`?

**Comment by HitLuca** [comment]
what do you mean exactly? I don't alter PYTHONPATH during tests, but I have a `sys.path.append(str(Path(__file__).resolve().parents[1]))` in my api in order to not have to always run it from the same folder

**Comment by HitLuca** [comment]
I can make a minimal example if that can help, maybe I'm doing something wrong somewhere

**Comment by HitLuca** [comment]
Ok there's something really weird going on, my example works as expected but not in my projects, but I don't think to have different setups. Could it be due to other pytest plugins maybe?

**Comment by HitLuca** [comment]
If I create a simple function 

```python
def a(x:int) -> int:
    return x
```

and place it in one of my python files, and test it with a wrong type (`a('test')`) typeguard doesn't work, but if I create a new file in the same subfolder as the previous one (`a.py`) with the same function and I test it, typeguard correctly makes it fail.

I am using mock here and there, but not in the functions if that can help

**Comment by agronholm** [comment]
> what do you mean exactly? I don't alter PYTHONPATH during tests, but I have a sys.path.append(str(Path(__file__).resolve().parents[1])) in my api main.py entrypoint in order to not have to always run it from the same folder

This is exactly what I mean. You're not using a proper package structure here, which is why the plugin is not working as expected.

**Comment by HitLuca** [comment]
Even after removing the `sys` instruction from my api `main.py` and restarting the venv the tests don't behave as expected

**Comment by agronholm** [comment]
Can you build a minimum working example for me? A minimal repository and the exact command you use to run the tests.

**Comment by HitLuca** [comment]
I have already done it with the same folder structure and commands and it all works as expected. I am thinking of copying my original project and test by ablation until I figure out at least where the problem is. I will update you on my findings

**Comment by HitLuca** [comment]
Ok I figured out the issue: cyclic imports.

I am testing a function in a helper functions file. Before startup my `conftest.py` sets up my flask app, which is done by importing and executing a function, but that function imports stuff all the way down to importing a function from the helper functions file. If I move that function import in `conftest.py` inside one of the fixture in order to defer it's execution typeguard starts working again. 

I am not really sure if typeguard can be updated to fix the issue, I am sure that my setup doesn't create issues when running the api, linting, testing etc.

At least I am happy to have discovered the origin of the problem, by going through a chain of 10+ files until the cycle emerged

**Comment by agronholm** [comment]
I'm going to close this now, but if you want something, create a minimum working example and I can reopen the ticket.
