### ISSUE TITLE
TypeError: type must be one of (Type, Tuple); got tuple instead

### ISSUE THREAD

**Issue by antonagestam** [agronholm/typeguard#153]
I am running into this issue when trying to run the test suite of [phantom-types](https://github.com/antonagestam/phantom-types) using the pytest plugin.

```
TypeError: type of argument "t" must be one of (Type, Tuple); got tuple instead
```

A minimal example reproducing the error:

```python
from typing import List
from typing import Tuple
from typing import Type
from typing import Union

from typeguard import typechecked


@typechecked
def fn(t: Union[Type, Tuple[Type, ...]]) -> None:
    ...


fn((Tuple, List))
```

**Comment by agronholm** [comment]
Neither `typing.List` or `typing.Tuple` are classes so typeguard rejects the call.

**Comment by antonagestam** [comment]
> Neither `typing.List` or `typing.Tuple` is a class so typeguard rejects the call.

Is there a reason typeguard  interprets `typing.Type` like that? It should model types and not classes, right?

**Comment by agronholm** [comment]
`Type` means class. Those two objects are not classes:
```
>>> from inspect import isclass
>>> from typing import Tuple, List
>>> isclass(Tuple)
False
>>> isclass(List)
False
```
Mypy agrees:
`/tmp/test.py:7: error: Argument 1 to "fn" has incompatible type "Tuple[_SpecialForm, Type[List[Any]]]"; expected "Union[Type[Any], Tuple[Type[Any], ...]]"`

**Comment by antonagestam** [comment]
@agronholm Interesting. How are you invoking mypy? I'm not getting that error even with `--strict` on mypy 0.790 (though I had to change to `Type[Any]`.

**Comment by agronholm** [comment]
I did `mypy --strict /tmp/test.py`
The script:
```
from typing import Type, Tuple, Union, List, Any

def fn(t: Union[Type[Any], Tuple[Type[Any], ...]]) -> None:
    return None

fn((Tuple, List))
```

**Comment by antonagestam** [comment]
@agronholm It seems the `typechecked` decorator wasn't maintaining typing of the function and hiding the error?


Anyhow, in my real world case the types aren't `Tuple` and `List`, but this, which passes with `mypy --strict` (without the decorator) for me:

```python
from typing import MutableMapping, MutableSequence, MutableSet, Tuple, Union

mutable = (MutableSequence, MutableSet, MutableMapping)


def fn(t: Union[type, Tuple[type, ...]]) -> None:
    ...


fn((MutableMapping, MutableSet, MutableSequence))
```

This throws when adding the `@typechecked` decorator to the function.

Note also that typeshed has a similar signature for [`isinstance()`](https://github.com/python/typeshed/blob/master/stdlib/2and3/builtins.pyi#L1330).

**Comment by agronholm** [comment]
Those are not classes either according to `inspect.isclass()`. I don't know if mypy uses an internal exception in its validation rules for these, but I'm not understanding how a run-time type checker should determine that these are `Type`s.

**Comment by antonagestam** [comment]
Gotcha, thanks for investigating deeply and explaining in detail! 🙏

To summarize, is the issue that `GenericAlias` lacks enough information to determine if it's legal to call `isinstance(..., T)` with the type?

**Comment by agronholm** [comment]
Well, `GenericAlias` is not even part of the public API, so using that for anything seems dubious.
Before making any changes, I would need to understand the basis on which mypy allows passing non-classes as Types.

**Comment by antonagestam** [comment]
Related note, typeshed also uses `Type` to mean types (not classes) [in `cast()`](https://github.com/python/typeshed/blob/c585d5d5cf6bb4e0702804ac32beeaf1dbfcf725/stdlib/3/typing.pyi#L630).
