### ISSUE TITLE
Terminal is corrupted after running (aws cdk) python file that imports typeguard

### ISSUE THREAD

**Issue by ottokruse** [agronholm/typeguard#154]
I'm using AWS CDK (https://github.com/aws/aws-cdk) and notice that after running `cdk synth` my terminal is corrupted. E.g. the up arrow displays "^[[A" instead of showing me the last terminal command. Then, after executing any other command, like a bare enter, or CTRL-C, the terminal is restored.

I chased this with the CDK team to no avail but later found that if I comment out the import of "typeguard" out, my terminal is not corrupted anymore:

`# from typeguard import typechecked`

I'm struggling to create a minimal code sample to reproduce. It seems to only occur in my larger code base.

In the mean time, do you perhaps have a suggestion why your library could cause this?

I realize I'm not giving you a lot here, but maybe this is something you recognize immediately. In the mean time I'll work on creating a minimal code sample to reproduce

**Comment by agronholm** [comment]
Typeguard only raises exceptions when something is wrong so it's not a likely culprit.

**Comment by agronholm** [comment]
It might trigger another problem but I don't see it as a direct cause.

**Comment by ottokruse** [comment]
Amazingly, if I comment out this line in your lib, the issue does not occur either.

`# from unittest.mock import Mock`

Will investigate further
