### ISSUE TITLE
`# type: ignore` comment is not respected

### ISSUE THREAD

**Issue by mihaic** [agronholm/typeguard#16]
[PEP 484](https://www.python.org/dev/peps/pep-0484/#type-comments) states:
"A # type: ignore comment on a line by itself is equivalent to adding an inline # type: ignore to each line until the end of the current indented block. At top indentation level this has effect of disabling type checking until the end of file."

**Comment by agronholm** [comment]
How do you propose I get this information at runtime?

**Comment by mihaic** [comment]
As far as I can tell, `inspect.getsource` results include comments.

**Comment by agronholm** [comment]
I don't think I will be personally implementing this. It involves far too much work given the benefits.

**Comment by agronholm** [comment]
You should probably check out [pytypes](https://github.com/Stewori/pytypes), as that project parses type comments.
