### ISSUE TITLE
How to get errors on `Literal` with typechecked annotated `class`?

### ISSUE THREAD

**Issue by SamuelMarks** [agronholm/typeguard#160]
```python
from typing import Literal
from dataclasses import dataclass

from typeguard import typechecked


@dataclass
@typechecked
class A(object):
    optimizer: Literal[
        "Adadelta", "Adagrad", "Adam", "Adamax", "Ftrl", "Nadam", "RMSprop"
    ] = None

print(A(optimizer='Foo'), A(optimizer=None), A(optimizer=True), A(optimizer=5))
```

Output:
```python
(A(optimizer='Foo'),
 A(optimizer=None),
 A(optimizer=True),
 A(optimizer=5),
 A(optimizer=0.2))
```

Expectation:
Error on all of these. This should work though `A(optimizer='Adagrad')`…

**Comment by SamuelMarks** [comment]
@agronholm In the meantime, I've started maintaining the old [`enforce`](https://github.com/RussBaz/enforce) repo, and added [`Literal`](https://docs.python.org/3/library/typing.html#typing.Literal) support with: https://github.com/SamuelMarks/enforce/commit/349e6f8

**Comment by svermeulen** [comment]
I don't think `@typechecked` can be applied to dataclass types as discussed in #161 and #61

**Comment by SamuelMarks** [comment]
@svermeulen Might give your gist a shot https://gist.github.com/svermeulen/8a6ad727113a6d07f78332152c1d33b2

I suppose avoiding maintaining my own runtime type checker is a good idea…
