### ISSUE TITLE
How to specify ForwardReferencePolicy with import hook

### ISSUE THREAD

**Issue by EPronovost** [agronholm/typeguard#163]
I see that `TypeChecker` takes an optional `ForwardReferencePolicy`, but it is deprecated.
> Deprecated since version 2.6: Use install_import_hook() instead. This class will be removed in v3.0

`install_import_hook()` doesn't currently seem to support specifying a `ForwardReferencePolicy`.  Since it uses `@typechecked`, I believe we could add a `ForwardReferencePolicy` argument to that decorator and pass it through to `_CallMemo` [here](https://github.com/agronholm/typeguard/blob/6f4f9d6cfd9d6333090ec2f4e9f56c4945cd7d45/typeguard/__init__.py#L901).  We could also add a `set_global_forward_reference_policy` method which allows users to change the default policy used by `_CallMemo`.
@agronholm did I miss something about `install_import_hook()`? If not, what do you think of these two ideas?  Thanks.

**Comment by agronholm** [comment]
Damn, this ticket totally slipped through the cracks. So, the plan was to allow the user to specify a number of configuration options (including forward reference policy) but I have not had time to work on this project beyond important bugfixes.

**Comment by agronholm** [comment]
In the 3.0 branch, you can now configure Typeguard with whatever `ForwardReferencePolicy` you want. This configuration system will of course be polished before the first release, but it's there.
