### ISSUE TITLE
Python 3.10 compatibility

### ISSUE THREAD

**Issue by snecklifter** [agronholm/typeguard#164]
Hello,

I package typeguard for Fedora and for the Fedora 35 release we are targeting Python 3.10.

The following bug has been raised as typeguard currently fails to build:

https://bugzilla.redhat.com/show_bug.cgi?id=1900764

There are ongoing builds with logs here: 

https://copr.fedorainfracloud.org/coprs/g/python/python3.10/package/python-typeguard/

as python 3.10 development also progresses.

Would it be possible to check if this is a python 3.10 issue or something that needs changing in the typeguard code?

Thanks!

**Comment by agronholm** [comment]
From what I can see from the build log:
```
Problem: package python3-typing-extensions-3.7.4.3-2.fc34.noarch requires python(abi) = 3.9, but none of the providers can be installed
```
`typing-extensions` is a dependency of typeguard, but it seems that there is something wrong with its packaging setup.

**Comment by snecklifter** [comment]
@agronholm thanks, seems the issue was with the earlier python 3.10 builds and now typing needs fixing.

**Comment by snecklifter** [comment]
@agronholm the original error has re-surfaced now we have typing enabled in the 3.10 repository.

https://copr.fedorainfracloud.org/coprs/g/python/python3.10/package/python-typeguard/

**Comment by agronholm** [comment]
Yeah, I can confirm that a tox run on Python 3.10 ends up with 19 test failures. I'll investigate.

**Comment by agronholm** [comment]
They're all NameErrors so something must have changed in 3.10 that affects quite a few tests.

**Comment by agronholm** [comment]
The reason for the error is that Python 3.10 changed annotations so that they're always lazily evaluated. In some tests, `CallMemo` isn't able to resolve those annotations to their proper, nonlocal values, thus raising `NameError`.

**Comment by agronholm** [comment]
I'm investigating whether the nonlocal name space could be somehow found and passed to `_CallMemo`.

**Comment by agronholm** [comment]
The problems should be gone now. I take it you need a patch release to continue your work?

**Comment by snecklifter** [comment]
> The problems should be gone now. I take it you need a patch release to continue your work?

Only if not too much trouble. It can certainly wait or I can carry the patch in the interim. Many thanks for looking at this.

**Comment by agronholm** [comment]
I've made a patch release with this fix in it.
