### ISSUE TITLE
None in Tuple is not checked

### ISSUE THREAD

**Issue by smarie** [agronholm/typeguard#17]
Hello there,
While comparing this library with other type checkers such as [enforce](https://github.com/RussBaz/enforce) and [typecheck-decorator](https://github.com/prechelt/typecheck-decorator) I found this bug:

```python
from typeguard import typechecked

@typechecked
def method(a: Tuple[str, int] = ('hello', 1)) -> int:
    if a is None:
        return a
    else:
        print(a[0])
        return a[1]

try:
    method(None)
except TypeError:
    print('None for the whole tuple is correctly handled')

try:
    method((None, 0))
    raise Exception('error None not checked inside tuple!')
except TypeError:
    pass
```

**Comment by smarie** [comment]
Actually type checking in Tuple does not work as well :

```python
from typeguard import typechecked

@typechecked
def method(a: Tuple[str, int] = ('hello', 1)) -> int:
    if a is None:
        return a
    else:
        print(a[0])
        return a[1]

try:
    method(0)
except TypeError:
    print('Wrong type the whole tuple is correctly handled')

try:
    method((0, 0))
    raise Exception('error wrong type in tuple not handled!')
except TypeError:
    pass
```

Kind regards

**Comment by agronholm** [comment]
The curious thing is that the default value messes up the type hint in typeguard code. Without it, this works fine.

**Comment by agronholm** [comment]
Normally I replace the annotated type with the union of itself and the type of the default value, but in this case it produces the built-in `tuple` class (not even `Tuple`).

**Comment by agronholm** [comment]
Fixed in https://github.com/agronholm/typeguard/commit/ef236707ce109dbd4e1174c061843acc1c3f6378.
