### ISSUE TITLE
Propagating the arguments types of the wrapped function for pylance autocompletion

### ISSUE THREAD

**Issue by martinResearch** [agronholm/typeguard#174]
**Is your feature request related to a problem? Please describe.**

Thank you for this amazing library. 

I am using the Pylance plugin in VS Code to get the list of the function arguments displayed when typing the name of the function. But when wrapping a function with `@typechecked` I get unhelpful displayed `(function) my_func1: (*args: Unknown, **kwargs: Unknown) -> Any`

Here is a simple example:
```
from typeguard import typechecked

@typechecked
def my_func1(x:int , y:int):
    return x+y

my_func1(6,6) 
```
When overing pylance `shows (function) my_func1: (*args: Unknown, **kwargs: Unknown) -> Any`

In comparison with a basic decorator
```
def my_decorator():
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            return func(*args, **kwargs)
        return wrapper
    return decorator
 
@my_decorator()
def my_func2(x:int , y:int):
    return x+y
 
my_func2(6,6) 
```
When overing over `my_func2(6,6)` Pylance shows `(function) my_func2: (x: int, y: int) -> int`
which is more useful.

**Describe the solution you'd like**

I would like to get `(function) my_func: (x: int, y: int) -> int` when overing over `my_func1(6,6)`

Could the decorator @typechecked be improved to propagate the arguments and returned values types of the original function so that they get picked up by Pylance? or is that a Pylance limitation that needs to be solved in the Pylance repository ?

**Comment by martinResearch** [comment]
If I comment the lines 
```
@overload
def typechecked(*, always: bool = False) -> Callable[[T_CallableOrType], T_CallableOrType]:
     ...


@overload
def typechecked(func: T_CallableOrType, *, always: bool = False) -> T_CallableOrType:
    ...
```

In pyguard's `__init__.py` file , then the type inference used by Pylance works.

**Comment by agronholm** [comment]
Is there something wrong with these annotations? I remember this being discussed somewhere on this issue tracker.

**Comment by martinResearch** [comment]
the commit https://github.com/agronholm/typeguard/commit/61f9f15e7db6b90ed05fd835660739715f110a59 fixes the problem. I looks like it is posterior to the last release on Pypi.org.  When is scheduled the next release ?

**Comment by agronholm** [comment]
There is no release schedule. I usually drop releases when enough fixes or features pile up, or when someone asks. I'll try to do it this weekend.

**Comment by agronholm** [comment]
The automated release 4 days ago failed and I didn't notice until now. I've uploaded the release manually. Sorry about the delay.

**Comment by martinResearch** [comment]
Thank you very much!
