### ISSUE TITLE
Test failures with 2.11.1

### ISSUE THREAD

**Issue by snecklifter** [agronholm/typeguard#176]
This is also reproduceable for me on 2.11.0 but not on 2.10.0

This is when running the test suite with `python -m pytest`

==================================== ERRORS ====================================
__________________ ERROR collecting tests/test_importhook.py ___________________
ImportError while importing test module '/builddir/build/BUILD/typeguard-2.11.1/tests/test_importhook.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_importhook.py:9: in <module>
    from typeguard.importhook import TypeguardFinder, install_import_hook
E   ModuleNotFoundError: No module named 'typeguard'
___________________ ERROR collecting tests/test_typeguard.py ___________________
ImportError while importing test module '/builddir/build/BUILD/typeguard-2.11.1/tests/test_typeguard.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_typeguard.py:16: in <module>
    from typeguard import (
E   ModuleNotFoundError: No module named 'typeguard'
________________ ERROR collecting tests/test_typeguard_py36.py _________________
ImportError while importing test module '/builddir/build/BUILD/typeguard-2.11.1/tests/test_typeguard_py36.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_typeguard_py36.py:7: in <module>
    from typeguard import TypeChecker, typechecked
E   ModuleNotFoundError: No module named 'typeguard'
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 3 errors in 0.24s ===============================

**Comment by agronholm** [comment]
As with any package, it needs to be installed before it can be imported. Before switching to the `src` layout it was possible to run the tests without installing because the package was located directly at the project root. But one shouldn't ever rely on this since the source might need extension module compilation, source transpilation or other build processes in order to work.

**Comment by mattst88** [comment]
I encountered this when packaging typeguard for Gentoo Linux (https://github.com/gentoo/gentoo/pull/20297). I worked around it by adding a testing dependence on the package itself, which is not ideal since it requires package testers to do a two-stage testing procedure.

As far as I can tell, most all Python packages in Gentoo are testable before installation. Though I'm aware of a few cases in the past where they weren't, I don't see any at the moment. If it's possible to make typeguard's tests not depend on the system-installed typeguard, we would certainly appreciate it.

**Comment by agronholm** [comment]
@mattst88 is using `tox` or a virtualenv not an option for you?

**Comment by agronholm** [comment]
If you could shed some light on how you do the testing, that would help.

**Comment by mattst88** [comment]
Thanks much. I'm poking some Gentoo people more knowledgeable than me for answers.

**Comment by mattst88** [comment]
It looks like the issue I see when running tests via Gentoo's package manager portage can be reproduced with

````
PYTHONPATH=$(pwd)/src pytest -vv
````

from a git checkout of typeguard:

````
tests/mypy/test_type_annotations.py::test_positive FAILED                                                                            [ 99%]
tests/mypy/test_type_annotations.py::test_negative FAILED                                                                            [100%]

================================================================= FAILURES =================================================================
______________________________________________________________ test_positive _______________________________________________________________
/tmp/typeguard/tests/mypy/test_type_annotations.py:83: in test_positive
    subprocess.check_call(get_mypy_cmd(POSITIVE_FILE))
/usr/lib/python3.9/subprocess.py:373: in check_call
    raise CalledProcessError(retcode, cmd)
E   subprocess.CalledProcessError: Command '['mypy', '--strict', 'positive.py']' returned non-zero exit status 1.
----------------------------------------------------------- Captured stdout call -----------------------------------------------------------
positive.py:2: error: Cannot find implementation or library stub for module named 'typeguard'
positive.py:2: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
positive.py:5: error: Untyped decorator makes function "foo" untyped
positive.py:18: error: Returning Any from function declared to return "bool"
positive.py:40: error: Untyped decorator makes function "get_value_checked" untyped
positive.py:49: error: Untyped decorator makes function "create_myclass_checked" untyped
Found 5 errors in 1 file (checked 1 source file)
______________________________________________________________ test_negative _______________________________________________________________
/tmp/typeguard/tests/mypy/test_type_annotations.py:96: in test_negative
    raise RuntimeError(
E   RuntimeError: Expected error lines {32, 11, 16, 20, 52, 53, 24, 28, 31} does not match mypy error lines {1, 4, 9, 11, 14, 16, 20, 52, 53, 24, 28}.
````

The proximate cause is that mypy appears to ignore `PYTHONPATH`. Also setting `MYPYPATH` then shows things that may be actual errors? And test_negative now passes.

````
PYTHONPATH="$(pwd)/src" MYPYPATH="$PYTHONPATH" pytest -vv
````

````
tests/mypy/test_type_annotations.py::test_positive FAILED                                                                            [ 99%]
tests/mypy/test_type_annotations.py::test_negative PASSED                                                                            [100%]

================================================================= FAILURES =================================================================
______________________________________________________________ test_positive _______________________________________________________________
/tmp/typeguard/tests/mypy/test_type_annotations.py:83: in test_positive
    subprocess.check_call(get_mypy_cmd(POSITIVE_FILE))
/usr/lib/python3.9/subprocess.py:373: in check_call
    raise CalledProcessError(retcode, cmd)
E   subprocess.CalledProcessError: Command '['mypy', '--strict', 'positive.py']' returned non-zero exit status 1.
----------------------------------------------------------- Captured stdout call -----------------------------------------------------------
/tmp/typeguard/src/typeguard/__init__.py:30: error: Incompatible import of "Literal" (imported name has type "typing._SpecialForm", local name has type "typing_extensions._SpecialForm")
/tmp/typeguard/src/typeguard/__init__.py:32: error: Incompatible types in assignment (expression has type "None", variable has type "_SpecialForm")
/tmp/typeguard/src/typeguard/__init__.py:41: error: Cannot assign multiple types to name "NoReturn" without an explicit "Type[...]" annotation
/tmp/typeguard/src/typeguard/__init__.py:48: error: Cannot assign to a type
/tmp/typeguard/src/typeguard/__init__.py:48: error: Incompatible types in assignment (expression has type "None", variable has type "Type[AsyncGenerator[Any, Any]]")
/tmp/typeguard/src/typeguard/__init__.py:50: error: Function is missing a type annotation
/tmp/typeguard/src/typeguard/__init__.py:50: error: All conditional function variants must have identical signatures
/tmp/typeguard/src/typeguard/__init__.py:53: error: Function is missing a type annotation
/tmp/typeguard/src/typeguard/__init__.py:53: error: All conditional function variants must have identical signatures
[....]
````

**Comment by agronholm** [comment]
Which version of mypy produces these results?

**Comment by mattst88** [comment]
0.812.

````sh
% mypy --version
mypy 0.812
````

**Comment by agronholm** [comment]
On my machine, the test suite passes with mypy 0.812.

**Comment by agronholm** [comment]
Do you install the test requirements before running `pytest`?

**Comment by mattst88** [comment]
These?

````
[options.extras_require]
test =
    pytest
    typing_extensions
    mypy; python_implementation != "PyPy"
````

Yes, they are all installed prior to testing typeguard.

I do not have `flake8` listed as a test dependency, but it is installed on the system in any case.

**Comment by mattst88** [comment]
> On my machine, the test suite passes with mypy 0.812.

Just to clarify, everything passes when you run

````
PYTHONPATH="$(pwd)/src" MYPYPATH="$PYTHONPATH" pytest -vv
````

from a git checkout of typeguard?

Thanks for your help. I really appreciate it!

**Comment by agronholm** [comment]
`test_positive` fails with that command unless I install `typeguard` in the virtualenv with `pip install -e .`.

**Comment by agronholm** [comment]
It seems that the mypy command is checking things it shouldn't, hence the errors.

**Comment by agronholm** [comment]
This has everything to do with how mypy treats the `typeguard` imports. When the test fails, it's treating it as source code rather than an external library. I don't have the energy to look much further into this, but I'll dig into it later this week.

By the way, is there a reason why you're not packaging the latest release?

**Comment by mattst88** [comment]
> This has everything to do with how mypy treats the `typeguard` imports. When the test fails, it's treating it as source code rather than an external library. I don't have the energy to look much further into this, but I'll dig into it later this week.

Thank  you very much for your help!

> By the way, is there a reason why you're not packaging the latest release?

typeguard hasn't been packaged in Gentoo previously. My pull request is adding v2.12.0 which is the latest (as far as I can tell :)

**Comment by agronholm** [comment]
Oh sorry, the original poster's tracebacks confused me.

**Comment by mattst88** [comment]
(I probably should have opened a new issue. Sorry for the confusion)

**Comment by mattst88** [comment]
All tests pass for me on Gentoo with v2.13.3. I think this is because we ignore the mypy tests. I have no more interest in this bug.
