### ISSUE TITLE
About performance

### ISSUE THREAD

**Issue by Gr1N** [agronholm/typeguard#18]
Hi!

Thanks for the project, looks very good and interesting.
I want to ask you some questions about performance: do you have any metrics (or thoughts) how usage of `typechecked` or `TypeChecker` affects on performance? And do you use your library in production or this just a prototype for fun?

**Comment by agronholm** [comment]
I am not concerned about performance since using `PYTHONOPTIMIZED=1` (or `-O`) disables the checks entirely in production. These checks are meant to be used only in testing and development, where I have not observed a noticeable drop in performance.

**Comment by Gr1N** [comment]
Understand, not my case, because I have idea to replace in some way validation (e.g. forms in django) by typing. Something like define annotations for http handler and validate request using just defined types. This is why I interested in performance.

**Comment by agronholm** [comment]
Do you not also need to validate the values then?

**Comment by Gr1N** [comment]
Of course I need to validate values (min_length, max_length, ...) and some business validation. But I think using typing I can solve some part of validation: is parameter required or not, default values and types. And yes I understand that I can can't use just typing, I need to write extra code for validation. 

This is just idea and prototype. And I want to try to solve not only validation question, I also want to try to build documentation based on annotations and code generation (e.g. client libraries for my services).

**Comment by agronholm** [comment]
Can you give an example of what your API endpoints would look like?

**Comment by Gr1N** [comment]
Something like:
```
class Body:
    def __init__(self, username: str, *, password: str = 'pwd') -> None:
        self.username = username
        self.password = password

class Response:
    def __init__(self, token: str) -> None:
        self.token = token

class Handler:
    def handle(self, body: Body) -> Response:
        ...
```

**Comment by agronholm** [comment]
Wait, are you saying that you create a new class for the body and response of every endpoint?

**Comment by Gr1N** [comment]
In the current concept, yes.

**Comment by agronholm** [comment]
That seems like a horrible idea. Consider why nobody has done that before. It will make your code unnecessarily verbose. Why not instead use something like WTForms?

**Comment by Gr1N** [comment]
I'm currently use Cerberus and I like it, but sometimes looking into any forms realisation and think that there are so many code which I not need I my project.

Maybe you are right about code verbose, but defining class with typing looks like defining django form or WTForm. What verbosity you see?

**Comment by agronholm** [comment]
With a 100 endpoints you end up with 300 classes. I honestly do not see why this is necessary. No framework I've ever seen requires you to create a response class for every endpoint. Normally you'd just return whatever data you want to return from the endpoint. If you want to ensure correctness, add tests to your test suite.

**Comment by Gr1N** [comment]
I agree with you, response class is overhead. But if you have defined response class, you can build documentation where user can find response schema and possible example. And also you can generate client library and user of your library looking into code can understand with what data he works. I understand that this is a very strange idea for Python, but for example you can find what I tried to explain in Golang.

**Comment by agronholm** [comment]
Regardless, I have no benchmarks to give you, but if you make some, I might be interested in seeing them. Is there anything else I can help you with?

**Comment by Gr1N** [comment]
No, but many thanks for the conversation.

**Comment by agronholm** [comment]
As far as API documentation goes, I suggest you check out Swagger. I know at least one Python framework that has Swagger integration: [API-star](https://github.com/tomchristie/apistar).
