### ISSUE TITLE
Use an alternative to  import hook for current file

### ISSUE THREAD

**Issue by MVrachev** [agronholm/typeguard#183]
**Is your feature request related to a problem? Please describe.**
It will be great if we can enable a configuration option for each file that will automatically decorate each function and class
with `@typechecked` decorator.

**Describe the solution you'd like**
A flag that could be set from the currently running file and can be set or unset for each file path:

```python
import typeguard

typeguard.type_check_module(<module_path>)

def add(a: int, b: int) -> int
  return a + b

# A TypeError will be raised because argument "a" should be an int.
add("3", 4)
```

**Describe alternatives you've considered**
Not sure what other alternatives there is.
I imagine that in the back end there will be a dictionary containing file paths as keys and boolean values showing if this flag
set for that file or not.

**Comment by agronholm** [comment]
Have you considered subclassing `TypeguardFinder` and overriding the `should_instrument()` method? This method was specially made for this purpose.

**Comment by MVrachev** [comment]
I experimented with `TypeguardFinder` and `should_instrument` but I can't make it work:
```python
from typeguard.importhook import TypeguardFinder, install_import_hook

class AllModulesFinder(TypeguardFinder):
    def should_instrument(self, moduleName: str) -> bool:
        return True 

install_import_hook('', cls = AllModulesFinder)

class B:
    def __init__(self, a: int) -> None:
        self.a = a
        print("In init")

b = B("3") # Doesn't raise an error

**Comment by agronholm** [comment]
Is that class `B` in the same module as where you install the import hook?

**Comment by MVrachev** [comment]
> Is that class `B` in the same module as where you install the import hook?

Yes, that is my idea.
To enforce type checking for the whole module just by adding a simple configuration option at the begging of the file.

**Comment by agronholm** [comment]
You do realize that since the module has already been imported, the import hook won't do anything?

**Comment by MVrachev** [comment]
> You do realize that since the module has already been imported, the import hook won't do anything?

Yes, that's why initially in my issue description I said `an alternative` to import_hook`.

**Comment by agronholm** [comment]
It will never be as good as the import hook because it can't decorate inner functions.

Can you describe why you cannot use the import hook? What is the use case like?

**Comment by agronholm** [comment]
There is now a way to have the import hook instrument all modules imported from that point onward: by omitting the `packages` argument to `install_import_hook()`. But I don't plan to add any other new instrumentation mechanisms unless there is very strong need that isn't covered by the import hook. So far I'm not convinced by these arguments.
