### ISSUE TITLE
QUESTION: dealing with Numpy

### ISSUE THREAD

**Issue by luk-f-a** [agronholm/typeguard#184]
**Is your feature request related to a problem? Please describe.**
I work extensively with numpy, and have annotated many functions as `def foo(x: int)`. However, I get many errors because typeguard considers `np.int32` or `np.int64` not to be `int`. 

```python
from typeguard import typechecked
import numpy as np

@typechecked
def foo(x: int):
    return x

arr = np.ones(1, dtype='i8')
foo(arr[0])
```

Is there an easy way to deal with this, besides creating a type alias for the union of int, int32, int64 and changing all the annotations?

Thanks!

**Comment by agronholm** [comment]
Not at the moment. A hypothetical plugin (if typeguard had plugins) could address this.

**Comment by luk-f-a** [comment]
thanks @agronholm , then I'll proceed with the Union.
