### ISSUE TITLE
Handler function for failing type check

### ISSUE THREAD

**Issue by kasium** [agronholm/typeguard#189]
Starting with #85 it would be nice to be able to register a handler function which can receive the failing check and do additional things depending on the user case:
```python

def handler(exec):
    # do whatever

from typeguard.importhook import install_import_hook
install_import_hook('...', handler=handler)
```

For example it would be possible to properly delegate the issue to a logging infrastructure. Depending on #85 I'm also happy to contribute here. The main use case would be, that in a productive system, only a warning is emitted (instead of an error) which can then be delegated to the logging systems.

**Comment by agronholm** [comment]
I've opened #215 to discuss this (and other related matters).

**Comment by agronholm** [comment]
As of 3.0, you can do this:
```python
from typeguard import TypeCheckError, TypeCheckMemo, config

def fail_callback(error: TypeCheckError, memo: TypeCheckMemo) -> None:
    print("Type checking failed:", error)

config.typecheck_fail_callback = fail_callback
```
Let me know if this doesn't resolve your request.
