### ISSUE TITLE
Type variables bound to first element type in heterogeneous collections

### ISSUE THREAD

**Issue by cjolowicz** [agronholm/typeguard#196]
**Describe the bug**

When checking type variables in heterogeneous collections, typeguard binds the variable to the type of the first item, and rejects items with a different type.

**To Reproduce**
```python
from typing import TypeVar

from typeguard import typechecked


T = TypeVar("T")


@typechecked
def f(arg: dict[str, T]) -> None:
    pass


f(
    {
        "a": "string",
        "b": ["list of strings"],
    }
)
```

Output:

```
Traceback (most recent call last):
  File "repro.py", line 14, in <module>
    f(
  File "venv/lib/python3.9/site-packages/typeguard/__init__.py", line 926, in wrapper
    check_argument_types(memo)
  File "venv/lib/python3.9/site-packages/typeguard/__init__.py", line 768, in check_argument_types
    raise TypeError(*exc.args) from None
TypeError: type of argument "arg"['b'] must be exactly str; got list instead
```

**Expected behavior**
Each item should only be checked against the constraints of the type variable, if any.

**Additional context**
Possibly related: #139

**Comment by agronholm** [comment]
Yes, this is due to an initial misunderstanding of how binding works. Correcting this requires effort beyond what I have currently available for project, however.

**Comment by cjolowicz** [comment]
I understand, thanks for clarifying. Feel free to close this if you consider it a duplicate.
