### ISSUE TITLE
Custom Error type

### ISSUE THREAD

**Issue by djetelina** [agronholm/typeguard#20]
Hi, I'd love to be able to catch typeguard validation errors explicitly, as I'm using it for validation of user's input and I'd love to be able to tell them when it's their fault and not try and tell them that my code's TypeError is their fault. I might be able to send a pull request for this, but wanted to run it by you first.

**Comment by agronholm** [comment]
It's been well over two years, but I am adding a validation mode that emit warnings instead. Would that work for you? If not, how would you want to configure this?

**Comment by iScrE4m** [comment]
Hey, I'm not using typeguard anymore (switched companies) and I don't even really remember, so I can't say. Sorry!

**Comment by agronholm** [comment]
As of v3.0, `TypeCheckError` is now raised instead of `TypeError`, so I consider this done.
