### ISSUE TITLE
Missing typing_extensions dependency

### ISSUE THREAD

**Issue by AckslD** [agronholm/typeguard#217]
**Describe the bug**
Seems `typing_extensions` is a missing dependency (at least on py38).
I get the error:
```
    def is_typeddict(tp) -> bool:
>       from typing_extensions import _TypedDictMeta
E       ModuleNotFoundError: No module named 'typing_extensions'

.../python3.8/site-packages/typeguard/__init__.py:73: ModuleNotFoundError
```
when using typeguard 2.13.1 but not in 2.13.0.

**Comment by agronholm** [comment]
Crap, it wasn't supposed to be a required dependency on the 2.x branch. Fixing.

**Comment by AckslD** [comment]
Great, thanks @agronholm :+1:
