### ISSUE TITLE
Confusing error message when an optional argument is a callable with too many parameters

### ISSUE THREAD

**Issue by Zac-HD** [agronholm/typeguard#223]
The following example raises a confusing error: `# TypeError: type of argument "arg" must be one of (Callable, NoneType); got function instead`.

```python
from typing import Callable, Optional
from typeguard import typechecked

@typechecked
def f(arg: Optional[Callable[[], None]]) -> None:
    pass

f(lambda _: None)  # Any function with required args, not just lambdas
```

I think it should instead raise the same error as you would see without the `Optional`: `TypeError: callable passed as argument "arg" has too many arguments in its declaration; expected 0 but 1 argument(s) declared`.

**Comment by agronholm** [comment]
Currently the 3.0 branch produces this error for this code:
```
typeguard._exceptions.TypeCheckError: argument "arg" did not match any element in the union:
  Callable[list, NoneType]: has too many arguments in its declaration; expected 0 but 1 argument(s) declared
  NoneType: is not an instance of NoneType
```

**Comment by Zac-HD** [comment]
Beautiful - can't wait to use it 🤩

**Comment by agronholm** [comment]
(looks like the `Callable` annotation is rendered wrong in the error message but that's another issue to be fixed before a prerelease)
