### ISSUE TITLE
typeguard does not recognize PEP 604 Unions

### ISSUE THREAD

**Issue by Mirandatz** [agronholm/typeguard#225]
**Describe the bug**
typeguard does not recognize the ["pipe operator" for unions ](https://www.python.org/dev/peps/pep-0604/),
but it does recognize typing.Union.

**To Reproduce**
```
import dataclasses
import typing

import typeguard


@dataclasses.dataclass(frozen=True)
class A:
    pass


@dataclasses.dataclass(frozen=True)
class B:
    pass


UsingOptional = typing.Union[A, B]
UsingPipe = A | B


@typeguard.typechecked
@dataclasses.dataclass(frozen=True)
class DoesExplode:
    values: tuple[UsingOptional, ...]


@typeguard.typechecked
@dataclasses.dataclass(frozen=True)
class ShouldExplode:
    values: tuple[UsingPipe, ...]


def main() -> None:
    values = (A(), B(), "should_explode")
    ShouldExplode(values)
    DoesExplode(values)


if __name__ == "__main__":
    main()
```

**Expected behavior**
AI expected both classes to throw, but only DoesExplode does.

**Additional context**

**Comment by agronholm** [comment]
This should be working in the 3.0 branch, have you tried that yet?

**Comment by Mirandatz** [comment]
Tried just now and it appears to work! Very nice! :D

Is 3.0 branch stable?

**Comment by agronholm** [comment]
The command line interface should be stable; the API is not.

**Comment by agronholm** [comment]
Confused this with another project I'm working on. This project doesn't have a CLI. The API is not stable here either but it's getting there.
