### ISSUE TITLE
Incorrect handling of *args and **kwargs (PEP 484)

### ISSUE THREAD

**Issue by Mirandatz** [agronholm/typeguard#226]
**Describe the bug**
It appears that branch 3.0 doesn't handle *args and **kwargs correctly.

Obs: I am using the instructions of [this SO answer](https://stackoverflow.com/questions/37031928/type-annotations-for-args-and-kwargs
) to annotate my function.

**To Reproduce**
```
import typeguard


@typeguard.typechecked
def process_list(prefix: str, *whatever: str) -> None:
    pass


process_list("a", "b", "c")
```

**Expected behavior**
Code should run without a TypeCheckError.

**Comment by agronholm** [comment]
It runs fine on the 3.0 branch. This branch will form the next major release. I am currently a bit busy with other projects but will get back to this one to finish the job. Let me know if this is a blocker issue for you.
