### ISSUE TITLE
Import hook conflcits with pytest import hook

### ISSUE THREAD

**Issue by saguziel** [agronholm/typeguard#230]
**Describe the bug**
When using pytest and the typeguard import hook, the assert rewriting of pytest does not work (https://docs.pytest.org/en/6.2.x/assert.html). This means that `assert` does not get translated into `assertEquals` and does not print expected and actual. It seems like pytest is common enough that it would be great if this worked.

**To Reproduce**
```from unittest import TestCase

class Test(TestCase):
    def test_broken_assert(self):
        assert 1 = 2 # when pytest and typeguard importhooks both on, it will not print expected and actual
        self.assertEquals(1, 2) # always works as expected
```

**Expected behavior**
Asserts should be rewritten correctly by test when typeguard importhook is on.

I imagine this could also be worked around by changing the importhook to not apply on test modules (which is also possible to do by users)

**Comment by agronholm** [comment]
Although it is documented that the import hook may conflict with others, and as such is not a bug per se, you are correct in that it would be very nice if a workaround could be found.

**Comment by agronholm** [comment]
I'm revisiting this now, and I started wondering why there would be a conflict between the pytest import hook and the tests. The tests should be instrumented by pytest while the actual code should be instrumented by typeguard. I tested this with another project of mine. Are you by any chance either placing your tests in the same package as the code, or instrumenting all packages with typeguard?

**Comment by agronholm** [comment]
I don't think it will ever be possible to use both typeguard and pytest instrumentation in the same module, so the obvious workaround is to have typeguard avoid trying to instrument test modules.
