### ISSUE TITLE
Allow optional type checking of return value(s)

### ISSUE THREAD

**Issue by mhostetter** [agronholm/typeguard#234]
Functions that return "large" iterables have linear type checking time, which can be prohibitive. In cases where you know you are returning the correct type, it would be nice to skip that check.

This feature request proposes adding a `outputs=True` keyword argument to `typechecked()`. By default, it type checks the output(s). However, with `outputs=False`, it only type checks the inputs. This way the decorator could be used in the following way.

*My use case is not as frivolous. I'm returning a list of prime numbers.*

## Current Usage

```python
# feature.py
from typeguard import typechecked
from typing import List

@typechecked
def make_list(n: int) -> List[int]:
    return list(range(0, n))
```

## Current Output

```python
In [1]: %run feature.py

In [2]: %time l = make_list(10)
CPU times: user 106 µs, sys: 5 µs, total: 111 µs
Wall time: 113 µs

In [3]: %time l = make_list(1000)
CPU times: user 2.16 ms, sys: 94 µs, total: 2.26 ms
Wall time: 2.26 ms

In [4]: %time l = make_list(1_000_000)
CPU times: user 1.44 s, sys: 20.2 ms, total: 1.46 s
Wall time: 1.46 s
```

## Desired Usage

```python
from typeguard import typechecked
from typing import List

@typechecked(outputs=False)
def make_list(n: int) -> List[int]:
    return list(range(0, n))
```

**Comment by agronholm** [comment]
This is more or less fixed in v3.0.0b2 since by default it only checks the first element in a sequence.

**Comment by chl1123** [comment]
from typeguard import install_import_hook
install_import_hook('module')

How to configure not to check return values using `install_import_hook`?

**Comment by agronholm** [comment]
This question doesn't belong in this issue. And no, there is no way currently to only perform certain checks in an instrumented function. Please open a discussion and present your use case.
