### ISSUE TITLE
Type checks missed for `Iterable[int]`

### ISSUE THREAD

**Issue by mhostetter** [agronholm/typeguard#235]
I noticed the type checking on `Iterable[int]` doesn't catch strings or nested iterables. I believe `Iterable[int]`, however, is meant to type any object that defines `__iter__()` and yields all ints.

## Minimal Reproducer

```python
# bug.py
import typeguard

from typing import Iterable

@typeguard.typechecked
def function(a: Iterable[int]):
    print(a)

function([1, 2, 3])
function([1, "a", 3])
function([[1, 2], [3, 4]])
```

## Output

```
$ python3 bug.py
[1, 2, 3]
[1, 'a', 3]
[[1, 2], [3, 4]]
```

## Expected Output

I would have expected calls two and three to have raised a `TypeError`.

For reference, VS Code's pylance returns these errors.

![image](https://user-images.githubusercontent.com/12112573/156029219-5b28cce8-cf78-4d29-bb47-35a1865662d5.png)

```
Argument of type "list[int | str]" cannot be assigned to parameter "a" of type "Iterable[int]" in function "function"
  TypeVar "_T_co@Iterable" is covariant
    Type "int | str" cannot be assigned to type "int"
      "str" is incompatible with "int"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)
```

![image](https://user-images.githubusercontent.com/12112573/156029249-ab4dc32d-c3d5-442e-a994-af1351a19188.png)

```
Argument of type "list[list[int]]" cannot be assigned to parameter "a" of type "Iterable[int]" in function "function"
  TypeVar "_T_co@Iterable" is covariant
    "list[int]" is incompatible with "int"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)
```

**Comment by agronholm** [comment]
`Iterable` is not safe to type check at run time, as it might cause side effects, hence no support. It's also not on the list of supported `typing.*` types (list [here](https://typeguard.readthedocs.io/en/latest/userguide.html#supported-typing-types)), so this shouldn't be reported as a bug.

**Comment by agronholm** [comment]
I partially retract my previous statement, as `@typechecked` does check in fact iterables in return values by wrapping them.

**Comment by agronholm** [comment]
As of v3.0.0, no wrapping is done anymore. So like I said before, iterables cannot be checked like sequences since iterating an iterable could destroy information or cause side effects. The best I can do is check if the object is indeed iterable, and that's already being done.

**Comment by skeggse** [comment]
This might be a horrible idea (and might violate a particular invariant you're trying to maintain), but what about lazily checking the types of the iterable? If the value is truly an iterable, then doing something like
```py
def check_iterable(value: Iterable[T], type: Type) -> Iterable[T]:
    return (check_type(entry, get_args(type)[0]) for entry in value)
```

Alternately, what about having a special case for a `Sequence` being passed in to an `Iterable` argument, where the values won't be consumed by iterating? That would provide more safety relative to the current state.

**Comment by agronholm** [comment]
I don't like special casing built-in types because the next thing you see is people asking for the same support in numpy types, and then other 3rd party libs. If somebody wants to run-time type check these, then they should declare the types as sequences. The example snippet won't of course work that way because it's a generator comprehension.

**Comment by skeggse** [comment]
The generator comprehension bit was intended - the idea being that the types would only get checked if/when the iterable is consumed, but that may or may not be desirable.

The case I want to handle doesn't fit sequences well, because sets and frozensets aren't sequenced and my code needs to accept those. Iterable is closer, but isn't sized/is consumable, so I'm not sure where to go from there besides just union a bunch of common iterables together.
