### ISSUE TITLE
Some release notes?

### ISSUE THREAD

**Issue by wqh17101** [agronholm/typeguard#236]
**Is your feature request related to a problem? Please describe.**
I find that there are no release notes.

**Describe the solution you'd like**
Add release notes when released.

**Additional context**
Without release notes,we can not know the difference between different versions.

**Comment by agronholm** [comment]
What are [these](https://typeguard.readthedocs.io/en/latest/versionhistory.html) then?

**Comment by wqh17101** [comment]
well....
