### ISSUE TITLE
New 3.9 syntax e.g. list[str] fails on 3.7

### ISSUE THREAD

**Issue by Malachov** [agronholm/typeguard#237]
Hello there. 

If using new 3.9 syntax (e.g. `list[str]`) with `from __future__ import annotations` in python it works, but in Typeguard not.

```python
from __future__ import annotations
from typeguard import typechecked

@typechecked
class Example:
    def __init__(self):
        self._hello = []

    @property
    def hello(self) -> list[str]:
        return self._hello


example = Example()

bad = example.hello  # gives Exception has occurred: TypeError 'type' object is not subscriptable
```
Well, this may not be a bug, but intended behavior, if so, feel free to close the issue.

My issue is that I use it libraries and it would fail for all the users with older python.

I see two possible solutions...

1) Implement somehow
2) Change catched error so user know what happened (he is using `from __future__ import annotations` so he suppose it should work)

If changing error so user know what is happening and why, he can simply use decorator only if detected python version >= 3.9. It's validated only with some python versions, but 3'rd party library still works, though not validated

My question is: Is it possible to allow this functionality in a simple way?

When I did type validation by myself on functions, I used eval (adding function locals) with simple string replace in type convertor ("list..." -> "List...") if using older versions

It works though there is eval security issue and limitation on only few particular types (list, tuple, dict), which is for general use sufficient...

Btw thanks for great tool

**Comment by agronholm** [comment]
This is not possible to implement with any reasonable amount of effort. You should limit these checks to 3.9+ only.
