### ISSUE TITLE
TypedDict and Dataclass check with typeguard

### ISSUE THREAD

**Issue by fcarpentey75012** [agronholm/typeguard#238]
Hello, 

I would like to use the dataclass to define the type and the field (to have the default value) and use TypedDict with typeguard to check the type of each keys in the dictionary. But Pylance doesn't accept this syntax.

`    
    from dataclasses import dataclass, field
    from typing import TypedDict
    from typeguard import typechecked

    @dataclass
    class Fieldsgetindexopen():
        """Metadata for the request
        """
        hedge: bool = field(default_factory=True)
        assetclass: str = field(default_factory='ACT')

    @typechecked
    def test(params : TypedDict('params', Fieldsgetindexopen.__annotations__)):
        print('Test')

    #Correct   
    print(test(params = {"hedge" : True, "assetclass" : "ACT"}))
    #No Correct
    print(test(params = {"hedge" : "True", "assetclass" : "ACT"})) `

Pylance Error : 
![Capture](https://user-images.githubusercontent.com/58303822/156179880-1dac7eda-9581-4d46-948b-7f19ac7e82e6.PNG)

Do you have any idea to resolve this problem ?

Thank you

**Comment by agronholm** [comment]
This isn't really a typeguard issue, but you need to define the typed dict as documented in the standard library, and then just use its name in the annotation.
