### ISSUE TITLE
Follow `mypy --strict`

### ISSUE THREAD

**Issue by eggplants** [agronholm/typeguard#240]
**Is your feature request related to a problem? Please describe.**
Almost functions of `typeguard` are lacking of type hints. And `mypy --strict 'src'` raises many errors.

**Describe the solution you'd like**
Make sure that nothing error occurs when `mypy --strict 'src'` is executed.

**Comment by agronholm** [comment]
I'm aware, but I've had other priorities. If you would like to fix this, I can review a PR.

**Comment by eggplants** [comment]
@agronholm thank you. Now I'm working on it.
