### ISSUE TITLE
typing_extensions.TypedDict not detected on Python 3.10

### ISSUE THREAD

**Issue by d-k-bo** [agronholm/typeguard#242]
**Describe the bug**
typeguard doesn't work with `typing_extensions.TypedDict` on Python 3.10 with typing_extensions >= 4.1.

**To Reproduce**
Run tests:

    tox -e py310

which fails due to

    TypeError: TypedDict does not support instance and class checks

**Expected behavior**
typeguard recognizes `typing_extensions.TypedDict`s as TypedDicts and all tests succeed.

**Additional context**
Since typing_extensions 4.1 implements its own implementation of `TypedDict` to support PEP 655, so `typing.is_typeddict()` doesn't recognize `typing_extensions.TypedDict`.

**Comment by agronholm** [comment]
Does this happen on latest master too?

**Comment by agronholm** [comment]
I'm guessing so due to that PR.

**Comment by d-k-bo** [comment]
> Does this happen on latest master too?

Yes, it does. See also https://github.com/python/typing/pull/1057 for the change that causes this behaviour.

**Comment by agronholm** [comment]
Fixed via #243.
