### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by eggplants** [agronholm/typeguard#244]
It is necessary to setup linting tool or define @agronholm's favorite style for getting rid of time to style codes.
I didn't tell it from code.

**Comment by agronholm** [comment]
Is this a question or a statement?

**Comment by eggplants** [comment]
I am concerned that the quotations are not consistent and the line breaks are unevenly positioned. Using black and isort to automatically format styles avoids unnecessary discussion and revision of styles, as happened in #241.

**Comment by eggplants** [comment]
After 3.0 branch has merged, I try to introduce these tools and re-add type annotations.

**Comment by agronholm** [comment]
I've done that in the 3.0 branch now.
