### ISSUE TITLE
check_type doesn't raise ValueError if expected_type is not a type

### ISSUE THREAD

**Issue by Kentzo** [agronholm/typeguard#25]
Shouldn't `check_type` raise an error if typeguard cannot recognize it as a type instead of silently exiting?

**Comment by agronholm** [comment]
I'm not entirely sure about this – some may use annotations for purposes other than type checking.

**Comment by Kentzo** [comment]
Could you think of an example?

**Comment by agronholm** [comment]
TypeVars and Unions (on 3.6+) are not classes.

**Comment by Kentzo** [comment]
Hmm, and there is no attribute to distinguish them and alike functions?
