### ISSUE TITLE
RuntimeError: typeguard cannot check these packages because they are already imported

### ISSUE THREAD

**Issue by FilipHesse** [agronholm/typeguard#260]
**Describe the bug**
Typeguard throws the following error: `RuntimeError: typeguard cannot check these packages because they are already imported: mypkg` in the following scenario:

I am using the typeguard plugin for pytest. My project structure is the following: .
```
├── noxfile.py
├── pyproject.toml
├── src
│   └── mypkg
│       ├── __init__.py
│       └── dummy_class.py
└── tests
    ├── __init__.py
    ├── conftest.py
    ├── example_dummy_fixture.py
    └── test_dummy.py
```

I am testing the class `dummy_class` from `dummy_class.py` in the testfile `test_dummy.py`. For the test in `test_dummy.py` I need a fixture, which is defined in `example_dummy_fixture.py`. 
I am importing `dummy_class` into `example_dummy_fixture.py` (needed for the fixture) and I also import it into `test_dummy.py` (to test it).
Furthermore, I added the plugin `tests.example_dummy_fixture` to `conftest.py`.

It is important to run the code with nox and poetry (see additional context), because I am testing the installed package instead of the source code. This makes a difference when importing (I can type `from mypkg import ...` instead of `from src.mypkg import ...`). 
So running a pytest session with `nox -s tests` works successfully (tests passed), but `nox -s typeguard` throws: 
```INTERNALERROR> RuntimeError: typeguard cannot check these packages because they are already imported: mypkg```

**To Reproduce**
Content of `dummy_class.py`:
```python
class dummy_class:
    def __init__(self, a, b):
        self.a = a
        self.b = b

    def foo(self):
        return self.a
```

Content of `example_dummy_fixture.py`:
```python
import pytest

from mypkg.dummy_class import dummy_class

@pytest.fixture
def example_dummy() -> dummy_class:
    return dummy_class(1,2)

```

Content of `test_dummy.py`:
```python
import pytest
from mypkg.dummy_class import dummy_class

def test_foo(
    example_dummy: dummy_class,
) -> None:
    '''Test foo'''
    assert example_dummy.foo() == 1

```

Content of `conftest.py`
```python
"""Config for pytest."""
pytest_plugins = [
    "tests.example_dummy_fixture",
]
```

To set up the project, you need `pyproject.toml` and `noxfile.py`
So here is my `pyproject.toml`:
```toml
[tool.poetry]
name = "mypkg"
version = "0.0.0"
description = "mypkg"
authors = ["me"]
license = ""
[tool.poetry.urls]
Changelog = ""

[tool.poetry.dependencies]
python = "^3.6.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
typeguard = "^2.13.3"

[build-system]
requires = ["poetry-core>=1.0.0", "numpy>=1.18.5"]
build-backend = "poetry.core.masonry.api"
```

and the `noxfile.py`:
```python
"""Nox sessions."""
import shutil
import sys
from pathlib import Path
from textwrap import dedent

import nox

try:
    from nox_poetry import Session
    from nox_poetry import session
except ImportError:
    message = f"""\
    Nox failed to import the 'nox-poetry' package.

    Please install it using the following command:

    {sys.executable} -m pip install nox-poetry"""
    raise SystemExit(dedent(message)) from None


package = "mypkg"
python_versions = [
    "3.6",
]
nox.needs_version = ">= 2021.6.6"
nox.options.sessions = (
    "tests",
    "typeguard",
)

@session(python=python_versions)
def tests(session: Session) -> None:
    """Run the test suite."""
    session.install(".")
    session.install( "pytest", "pygments")
    
    session.run("pytest", *session.posargs)

@session(python=python_versions)
def typeguard(session: Session) -> None:
    """Runtime type checking using Typeguard."""
    session.install(".")
    session.install("pytest", "typeguard", "pygments")
    session.run("pytest", f"--typeguard-packages={package}", *session.posargs)
```

You first need to install [poetry](https://python-poetry.org/docs/master/#installing-with-the-official-installer), [nox](https://nox.thea.codes/en/stable/) and [nox-poetry](https://nox-poetry.readthedocs.io/en/stable/). During installation, I used python 3.9.13. from [pyenv](https://github.com/pyenv/pyenv). For execution of the code I activate python 3.6.9 from pyenv.

Then call `poetry install` in the working directory  of the project.
Then, the calls  `nox -s tests` should run the test successfully and `nox -s typeguard` should throw the error shown above.

**Expected behavior**
I would expect typeguard to run regularly with the final output `nox > Session typeguard-3.6 was successful.`

**Additional context**
* System: Ubuntu Server 20.04 LTS
* Python-Version: Python 3.6.15 installed with pyenv. During installation, I use python 3.9.13 from pyenv.

My original Project is based on the [cookiecutter-hypermodern-python template](https://github.com/cjolowicz/cookiecutter-hypermodern-python), which uses poetry for packaging and dependencies and nox for test automation. As stated above, running within this environment is important, because I want to use `from mypkg.dummy_class import dummy_class` instead of `from src.mypkg.dummy_class import dummy_class`. If I would use `from src.mypkg import dummy_class`, I would create another typeguard error in another place (would require an extended code example), because this differs from the way of importing in the package `mypkg`:  
```
TypeError: type of argument "dummies"[0] must be mypkg.dummy_class.dummy_class; got src.mypkg.dummy_class.dummy_class instead
```

**Full output during error**
```bash
nox -s typeguard
nox > Running session typeguard-3.6
nox > Creating virtual environment (virtualenv) using python3.6 in .nox/typeguard-3-6
nox > poetry build --format=wheel --no-ansi
nox > pip uninstall --yes file:///media/myproject/dist/mypkg-0.0.0-py3-none-any.whl
nox > poetry export --format=requirements.txt --dev --without-hashes
nox > python -m pip install --constraint=.nox/typeguard-3-6/tmp/requirements.txt file:///media/myproject/dist/mypkg-0.0.0-py3-none-any.whl
nox > python -m pip install --constraint=.nox/typeguard-3-6/tmp/requirements.txt pytest typeguard pygments
nox > pytest --typeguard-packages=mypkg
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/media/myproject/.nox/typeguard-3-6/lib/python3.6/site-packages/_pytest/main.py", line 265, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/media/myproject/.nox/typeguard-3-6/lib/python3.6/site-packages/_pytest/config/__init__.py", line 982, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/media/myproject/.nox/typeguard-3-6/lib/python3.6/site-packages/pluggy/_hooks.py", line 277, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
INTERNALERROR>   File "/media/myproject/.nox/typeguard-3-6/lib/python3.6/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/media/myproject/.nox/typeguard-3-6/lib/python3.6/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/media/myproject/.nox/typeguard-3-6/lib/python3.6/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/media/myproject/.nox/typeguard-3-6/lib/python3.6/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/media/myproject/.nox/typeguard-3-6/lib/python3.6/site-packages/typeguard/pytest_plugin.py", line 28, in pytest_configure
INTERNALERROR>     raise RuntimeError(message.format(", ".join(already_imported_packages)))
INTERNALERROR> RuntimeError: typeguard cannot check these packages because they are already imported: mypkg
nox > Command pytest --typeguard-packages=mypkg failed with exit code 3
nox > Session typeguard-3.6 failed.
```

**Comment by agronholm** [comment]
If the package has already been imported, what is typeguard supposed to do? It relies on AST manipulation to insert its decorators in the code.

**Comment by FilipHesse** [comment]
Do you have any idea why the package already being imported is no problem for pytest but only for typeguard? I do not see what I can do to prevent the package from being imported twice. I need mypkg within the fixture and within the test.

**Comment by agronholm** [comment]
I suspect it has to do with nox. Could you try to factor out nox and see if this happens with only pytest?

**Comment by FilipHesse** [comment]
If I do not use nox, the I can not call `from mypkg.dummy_class import dummy_class` but only `from src.mypkg.dummy_class import dummy_class`. Indeed, with or without nox: using `from src.[...]` does solve the described problem, but it causes another typeguard related issue in my project:
```
TypeError: type of argument "dummies"[0] must be mypkg.dummy_class.dummy_class; got src.mypkg.dummy_class.dummy_class instead
```
Would you like me to provide a minimal example for that?

**Comment by agronholm** [comment]
Yes, it would help if I could run it locally.

**Comment by FilipHesse** [comment]
You can reporduce the error **without nox and poetry**. Just clone the [repo](https://github.com/FilipHesse/typeguard-bug-report-packages-already-imported) and follow a few instructions from the README.md.
(The code is slightly modified from the example above to simplify further).
The output should be the error described above: 
```
INTERNALERROR> RuntimeError: typeguard cannot check these packages because they are already imported: mypkg
```

If you run pytest alone, then there is no issue with importing modules (just type `pytest`), pytest is successfull.

**Comment by fefe982** [comment]
Met a similar problem. I ended up calling `install_import_hook` directly in `conftest.py`.

**Comment by simonw** [comment]
I ran into the same problem just now: "RuntimeError: typeguard cannot check these packages because they are already imported"

I solved it by applying this workaround I found through GitHub code search: https://github.com/bbugyi200/logutils/blob/c1d7723c4efa5311956ebd6752bfad71c05ceb9b/tests/conftest.py#L12-L52

Short version: add this to `conftest.py` (my module under test is called `sqlite_utils`):

```python
from typeguard import typechecked
from typeguard.importhook import install_import_hook


def pytest_configure():
    install_import_hook("sqlite_utils")


def pytest_runtest_call(item):
    # Decorate every test function [e.g. test_foo()] with typeguard's
    # typechecked() decorator.
    test_func = getattr(item, "obj", None)
    if test_func is not None:
        setattr(item, "obj", typechecked(test_func))
```

**Comment by Dioneta** [comment]
This solution did not work for me. 

`from typeguard import typechecked
from typeguard.importhook import install_import_hook


def pytest_configure():
    install_import_hook("sqlite_utils")


def pytest_runtest_call(item):
    # Decorate every test function [e.g. test_foo()] with typeguard's
    # typechecked() decorator.
    test_func = getattr(item, "obj", None)
    if test_func is not None:
        setattr(item, "obj", typechecked(test_func))`

**Comment by agronholm** [comment]
I will change the `RuntimeError` into a warning in the next major release.

**Comment by AlanCoding** [comment]
I tried to use the pytest plugin in https://github.com/ansible/django-ansible-base/pull/177 but then found out it was not actually enforcing types. The warning ("cannot check these packages...") did not show up unless using `py.test --trace-config` was used, which made this hard to discover, even `py.test -s` will not show it. I would have rather you left it as a `RuntimeError`.

My issue seems specific to `pytest-django`. Pytest-django uses `pytest_load_initial_conftests` which is called earlier than `pytest_configure`. That will call `django.setup()`, which will import app settings, which will inevitably import app code.

https://github.com/pytest-dev/pytest-django/blob/11f613da77b5bc22d44eaa8c82a0fda427f091cb/pytest_django/plugin.py#L360

<details>

<summary>Stack trace where early import happens</summary>

```
$ py.test test_app/tests/rbac/test_triggers.py -k test_alan --trace-config -p typeguard -vvvvv
<site_packages>/_pytest/config/__init__.py:331: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
Plugin: helpconfig, Hook: pytest_cmdline_parse
Exception:
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
  config = pluginmanager.hook.pytest_cmdline_parse(
Traceback (most recent call last):
  File "/home/alancoding/venvs/awx/bin/py.test", line 8, in <module>
    sys.exit(console_main())
             ^^^^^^^^^^^^^^
  File "<site_packages>/_pytest/config/__init__.py", line 192, in console_main
    code = main()
           ^^^^^^
  File "<site_packages>/_pytest/config/__init__.py", line 150, in main
    config = _prepareconfig(args, plugins)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<site_packages>/_pytest/config/__init__.py", line 331, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<site_packages>/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<site_packages>/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<site_packages>/pluggy/_callers.py", line 155, in _multicall
    teardown[0].send(outcome)
  File "<site_packages>/_pytest/helpconfig.py", line 104, in pytest_cmdline_parse
    config: Config = outcome.get_result()
                     ^^^^^^^^^^^^^^^^^^^^
  File "<site_packages>/pluggy/_result.py", line 99, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "<site_packages>/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<site_packages>/_pytest/config/__init__.py", line 1075, in pytest_cmdline_parse
    self.parse(args)
  File "<site_packages>/_pytest/config/__init__.py", line 1425, in parse
    self._preparse(args, addopts=addopts)
  File "<site_packages>/_pytest/config/__init__.py", line 1327, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "<site_packages>/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<site_packages>/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<site_packages>/pluggy/_callers.py", line 181, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "<site_packages>/pluggy/_result.py", line 99, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "<site_packages>/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<site_packages>/pytest_django/plugin.py", line 360, in pytest_load_initial_conftests
    _setup_django(early_config)
  File "<site_packages>/pytest_django/plugin.py", line 236, in _setup_django
    django.setup()
  File "<site_packages>/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "<site_packages>/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "<site_packages>/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<repos_root>/django-ansible-base/ansible_base/resource_registry/__init__.py", line 1, in <module>
    raise Exception
Exception
```
</details>

I looked into making a patch here which would add the `pytest_load_initial_conftests` hook, which may have a chance at fixing the issue combined with using `py.test -p typeguard` (which is reasonable to ask users do). The problem is that typeguard needs its config values like `typeguard-packages` to `install_import_hook`, and that runs too early, at a point where the pytest config isn't fully parsed.

I don't see an option forward where the typeguard & pytest-django pytest plugins are not conflicting. That leaves the remaining option of a custom configuration in Django settings (to preempt imports) like this https://github.com/ansible/django-ansible-base/pull/260.
