### ISSUE TITLE
TypeError when using Lists of Lists

### ISSUE THREAD

**Issue by FilipHesse** [agronholm/typeguard#261]
This bug is related to [this](https://github.com/FilipHesse/typeguard-bug-report-typeerror-list-of-lists) bug report. However, to avoid confusion, I am opening a new bug report.
I run into the error 
```
FAILED tests/test_foobar.py::test_bar - TypeError: type of argument "my_list"[0] must be mypkg.dummy_class.dummy_class; got src.mypkg.dummy_class.dummy_class instead
```
in the following scenario:
I am using the typeguard plugin for pytest. My project structure is the following:
```
.
├── README.md
├── pyproject.toml
├── requirements.txt
├── src
│   └── mypkg
│        ├── __init__.py
│        ├── bar.py
│        ├── dummy_class.py
│        └── foo.py
└── tests
    ├── __init__.py
    ├── conftest.py
    ├── example_dummy_fixture.py
    └── test_foobar.py
```

I am testing the functions `foo(my_list: List[dummy_class])` and `bar(my_list_of_lists: List[List[dummy_class]])` which take a list and a lists of lists of the class `dummy_class` as input arguments. 
The class `dummy_class` is defined in `dummy_class.py`. The testfile is `test_foobar.py`. For the test in `test_foobar.py` I need a fixture (object of `dummy_class`), which is defined in `example_dummy_fixture.py`.
I added the plugin `tests.example_dummy_fixture` to `conftest.py`.

If I install mypkg (`pip install .`) and run
```
pytest
```
then the session is successful (`2 passed in 0.04s`).

If I run the typeguard session 
```
pytest --typeguard-packages=mypkg
```
the TypeError is thrown:
```
FAILED tests/test_foobar.py::test_bar - TypeError: type of argument "my_list"[0] must be mypkg.dummy_class.dummy_class; got src.mypkg.dummy_class.dummy_class instead
```

**To Reproduce**
To reproduce, you can clone the [Github-repo](https://github.com/FilipHesse/typeguard-bug-report-typeerror-list-of-lists) with the code and follow the instructions in the REAMDME.md.
For completeness, I will also provide the code here:
Content of `bar.py`:
```python
from typing import List
from mypkg.dummy_class import dummy_class
from mypkg.foo import foo

def bar(my_list_of_lists: List[List[dummy_class]]) -> None:
    for my_list in my_list_of_lists:
        foo(my_list)
```

Content of `foo.py`:
```python
from typing import List
from mypkg.dummy_class import dummy_class

def foo(my_list: List[dummy_class]):
    pass
```

Content of `dummy_class.py`:
```python
class dummy_class:
    def __init__(self, a):
        self.a = a
```

Content of `conftest.py`:
```python
"""Config for pytest."""
pytest_plugins = [
    "tests.example_dummy_fixture",
]
```

Content of `example_dummy_fixture.py`:
```python
import pytest

from src.mypkg.dummy_class import dummy_class

@pytest.fixture
def example_dummy() -> dummy_class:
    return dummy_class(1)
```

Content of `test_foobar.py`:
```python
"""Tests for UpliftVisualization."""
import pytest
from src.mypkg.dummy_class import dummy_class
from src.mypkg.foo import foo
from src.mypkg.bar import bar

def test_bar(
    example_dummy: dummy_class,
) -> None:
    '''Test bar'''
    bar([[example_dummy],[example_dummy]])

def test_foo(
    example_dummy: dummy_class,
) -> None:
    '''Test foo'''
    foo([example_dummy])
```

Content of `pyproject.toml`:
```toml
[project]
name = "mypkg"
version = "0.0.0"
description = "mypkg"
authors = [{ name = "Me", email = "me@mycompany.com" }]

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]
```

*Instructions*
* Install python 3.6.15
* create a virtual environment and activate it
```
    python -m venv venv
    source venv/bin/activate
```
* Upgrade pip and setuptools
```
pip install --upgrade pip setuptools
```
* install the package `mypkg`
```
pip install .
```
* run pytest with the typeguard plugin
```
pytest --typeguard-packages=mypkg
```

*Outcome*
```
FAILED tests/test_foobar.py::test_bar - TypeError: type of argument "my_list"[0] must be mypkg.dummy_class.dummy_class; got src.mypkg.dummy_class.dummy_class instead
```

The error only happens for the bar function, that accepts a list of lists as input argument. If we only test the foo function (comment out/remove the `test_bar` function) with a simple list as input argument, then typeguard runs without any issue.

**Expected behavior**
I expect the typeguard session to run successfully as `mypkg.dummy_class.dummy_class` and `src.mypkg.dummy_class.dummy_class` refer to the same class.

**Additional context**
An obvious solution might be to use `from mypkg.[...] import [...]` instead of `from src.mypkg.[...] import [...]` in all test-related files, which unfortunately leads to another issue described in [my previous bug report](https://github.com/agronholm/typeguard/issues/260)
This can be reproduced with this example code as well (simply replace `src.mypkg` with `mypkg` globally).

By the way, the project structure with an src directory containing the packages is strongly recommended by pytest, see [pytest doc](https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html), just like the method of installing the package with pip before testing it.

If I understand the pytest best practices right, then I should import `from mypkg` instead of `from src.mypkg`, which, again, leads to the [related issue](https://github.com/agronholm/typeguard/issues/260)

Thank you in advance!

**Comment by agronholm** [comment]
There is an actual type mismatch here (since the module is imported twice under two different names) so this is not a typeguard bug. You must sort out your import issues – using `src` as if it was a package is wrong.
