### ISSUE TITLE
Failed when using Type[TypeVar] with constraints

### ISSUE THREAD

**Issue by fefe982** [agronholm/typeguard#263]
Check failed when using Type[TypeVar] with constraints as annotation.

```python
from typing import Type, TypeVar
import typeguard

T = TypeVar("t", int, float)

@typeguard.typechecked
def foo(t: Type[T]) -> T:
    return t()

foo(int)
```

This should pass, but failed with
```
TypeError: argument "t" must match one of the constraints (int, float); got int instead
```

tested with python 3.10.4 and typeguard 2.13.3

----

`T = TypeVar("t", bound=Union[int, float])` works properly.

**Comment by agronholm** [comment]
Works on typeguard 3.0.0b1.
