### ISSUE TITLE
Please release latest versions to ubuntu

### ISSUE THREAD

**Issue by InigoMoreno** [agronholm/typeguard#270]
Hey, I can see that typeguard on ubuntu is still on version 2.2. 
```
$ apt-cache madison python3-typeguard
python3-typeguard |    2.2.2-1 | http://es.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
python3-typeguard |    2.2.2-1 | http://es.archive.ubuntu.com/ubuntu focal/universe i386 Packages
```
Would it be possible to make a new release for the latest version?

**Comment by agronholm** [comment]
Duplicate of #257.

**Comment by agronholm** [comment]
If you were asking about 2.13 being released, then you should ask those maintaining the Ubuntu package. That is not me.

**Comment by InigoMoreno** [comment]
Who would that be?

**Comment by agronholm** [comment]
Best I could find is "Ubuntu MOTU Developers" (ubuntu-motu@lists.ubuntu.com). I am in no way involved in that, so I don't know any more than you do.
