### ISSUE TITLE
Add support for typing.Self

### ISSUE THREAD

**Issue by LostInDarkMath** [agronholm/typeguard#275]
Python 3.11 was released now as stable version. It added some new typing features. The most important change is the addition of [`typing.Self`](https://docs.python.org/3.11/library/typing.html#typing.Self). It would be nice if `typeguard` could have support for this!

**Comment by agronholm** [comment]
It would indeed. But even Mypy hasn't gotten around to supporting `Self`. I will of course add support when I resume work on typeguard, but I don't know when that will be.
