### ISSUE TITLE
typeguard doesn't check types like "a | b" 

### ISSUE THREAD

**Issue by jingfeijia-tsy** [agronholm/typeguard#276]
It seems typeguard doesn't support types like "a | b" that is introduced in [PEP604](https://peps.python.org/pep-0604/).

**To Reproduce**
```
from typeguard import typechecked
from typing import Union

@typechecked
def f(x: int | float):
  print(x)

@typechecked
def g(x: Union[int, float]):
  print(x)

f("a")
g("a")
```

**Expected behavior**
Both should raise TypeError, but in reality f("a") just passed without raising an exception.

**Comment by antonagestam** [comment]
This should be pretty easy to fix, we just need to add handling for a new type when available. See equivalent fixes here:

- https://github.com/konradhalas/dacite/pull/184
- https://github.com/ilevkivskyi/typing_inspect/pull/83

I guess it would be rather fitting if I provided a fix for this here as well, we'll see if I find the time.

Cheers

**Comment by agronholm** [comment]
This is already done in master, but I haven't had any time to devote on the project lately, thus no new release :(

**Comment by supersergiy** [comment]
Exciting to see `typeguard` being worked on again! 

PEP604-style Union still doesn't seem to work with TypeAliases on master:
```python
from typing_extensions import TypeAlias

from typeguard import typechecked

A: TypeAlias = int
B: TypeAlias = str

@typechecked
def foo(a: A | B): ...

foo(1)
```
`TypeError: unsupported operand type(s) for |: 'type' and 'type'`
