### ISSUE TITLE
[FR] hide stacktrace info from typeguard

### ISSUE THREAD

**Issue by Cologler** [agronholm/typeguard#28]
Is possible replace from

``` py
    @wraps(func)
    def wrapper(*args, **kwargs):
        memo = _CallMemo(func, args=args, kwargs=kwargs)
        check_argument_types(memo)
        retval = func(*args, **kwargs)
        check_return_type(retval, memo)
        return retval
```

to

``` py
    @wraps(func)
    def wrapper(*args, **kwargs):
        memo = _CallMemo(func, args=args, kwargs=kwargs)
        try:
            check_argument_types(memo)
        except TypeError as err:
            raise TypeError(err)
        retval = func(*args, **kwargs)
        try:
            check_return_type(retval, memo)
        except TypeError as err:
            raise TypeError(err)
        return retval
```

for hide stacktrace info from typeguard.

**Comment by agronholm** [comment]
Is this a question? I wasn't sure. Anyway, since exceptions are chained, this would just add to the noise without adding any useful information.

**Comment by Cologler** [comment]
I think user code does not need to see the stacktrace which come from recursive hell.

currently:

![picpick-20180103-221150-001](https://user-images.githubusercontent.com/10906962/34523604-23303e98-f0d3-11e7-8ae8-9b607ba5a081.png)

and if we use `try-reraise` then the message is more clear:

![picpick-20180103-221300-001](https://user-images.githubusercontent.com/10906962/34523668-64a4c3da-f0d3-11e7-82ae-7e2ba82b8c8b.png)

**Comment by Cologler** [comment]
@agronholm

**Comment by agronholm** [comment]
What are you doing to suppress the chained exceptions?

**Comment by Cologler** [comment]
😂 I don't know what you mean.

**Comment by agronholm** [comment]
When you raise an exception in the handler of another exception, the original exception is chained to the new exception (by default). Printing such an exception adds messages like "While handling this exception, another exception occurred: ...".

**Comment by Cologler** [comment]
Oh, I missing that ! 😂

But that can fix by:

``` py
    @wraps(func)
    def wrapper(*args, **kwargs):
        memo = _CallMemo(func, args=args, kwargs=kwargs)
        error = None
        try:
            check_argument_types(memo)
        except TypeError as err:
            error = err
        if error is not None:
            raise TypeError(error)
        retval = func(*args, **kwargs)
        try:
            check_return_type(retval, memo)
        except TypeError as err:
            error = err
        if error is not None:
            raise TypeError(error)
        return retval
```

Just a little ugly ...

**Comment by agronholm** [comment]
If you *really* wanted to fix that, you would suppress exception chaining:

```python
try:
    check_argument_types(memo)
except TypeError as err:
    raise TypeError(*err.args) from None
```

**Comment by Cologler** [comment]
cool. 

but `raise TypeError(err) from None` maybe better. (still can get origin error from we catch)

but why do not add this in `typeguard` ?

**Comment by agronholm** [comment]
I'll think about it.
