### ISSUE TITLE
Subscripted generics cannot be used with class and instance checks

### ISSUE THREAD

**Issue by apmorton** [agronholm/typeguard#280]
```python
from typing import Tuple
from typeguard import typechecked


@typechecked
def foo() -> Tuple[bool, bool]:
    return False, False


// this works
foo()

class UnrelatedThing:
    __class_getitem__ = classmethod(type(Tuple[int]))

// this throws TypeError: Subscripted generics cannot be used with class and instance checks
foo()

```

This appears to have been fixed by 0fbb5b8f8c7b24361a6289122d5c8e87ba3b10ef, but no release has been made since then.

Would it be possible to make a new stable release so we can pick up this fix?

**Comment by agronholm** [comment]
I'll try. I don't remember where I left off with preparing the next major release (I have quite a few projects to maintain). I really want to get a new release out, so long as it's in a usable condition.

**Comment by agronholm** [comment]
I'm not comfortable with the overall state of the new code, but I've made a beta release (3.0.0b1). Enjoy.
