### ISSUE TITLE
typeguard doesn't ignore `unittest.mock.MagicMock` arguments

### ISSUE THREAD

**Issue by supersergiy** [agronholm/typeguard#282]
**Describe the bug**
`typeguard` doesn't ignore `unittest.mock.MagicMock` arguments on `master`. Used to work with `2.13.3`.

**To Reproduce**
```python
import unittest
from typeguard import typechecked

@typechecked
def foo(a: int): ...

a = unittest.mock.MagicMock()

foo(a) # typeguard.TypeCheckError: argument "a" is not an instance of int
```

**Comment by supersergiy** [comment]
Would it be an acceptable solution to check for `isinstance(value, Mock)` in `check_type_internal`? I could make a PR

**Comment by agronholm** [comment]
That sounds like the correct solution. I'll get this fixed over the weekend.
