### ISSUE TITLE
`bool` passes `check_number`

### ISSUE THREAD

**Issue by makslevental** [agronholm/typeguard#288]
Definitely a wtf moment for me... (can repro with the everso concise `isinstance(True, (float, int))`). [Some coroborating discussion](https://stackoverflow.com/a/37888668/9045206). As discussed, `check_number` should be:

```python
def check_number(
    value: Any, origin_type: Any, args: tuple[Any, ...], memo: TypeCheckMemo
) -> None:
    if origin_type is complex and not isinstance(value, (complex, float, int)):
        raise TypeCheckError("is neither complex, float or int")
    elif origin_type is float and isinstance(value, bool):
        raise TypeCheckError("is neither float or int")
    elif origin_type is float and not isinstance(value, (float, int)):
        raise TypeCheckError("is neither float or int")
```

or the more terse

```python
def check_number(
    value: Any, origin_type: Any, args: tuple[Any, ...], memo: TypeCheckMemo
) -> None:
    if origin_type is complex and not isinstance(value, (complex, float, int)):
        raise TypeCheckError("is neither complex, float or int")
    elif origin_type is float and (not isinstance(value, (float, int)) or isinstance(value, bool)):
        raise TypeCheckError("is neither float or int")
```

Can submit a PR if you'd like.

**Comment by makslevental** [comment]
On a similar note:

why not have a separate 

```python
def check_float(
    value: Any, origin_type: Any, args: tuple[Any, ...], memo: TypeCheckMemo
) -> None:
    if origin_type is float and not isinstance(value, float):
        raise TypeCheckError("is not a float")
```

in

```python
origin_type_checkers = {
   ...
   # float: check_number,
   # float: check_float,
}
```

?

**Comment by agronholm** [comment]
Mypy does not complain about passing a bool against an int-annotated argument (see [here](https://mypy-play.net/?mypy=latest&python=3.11&gist=ab1887d8ee95083076e65a24fb243c65)). Why should typeguard behave differently?

**Comment by makslevental** [comment]
You don't see how there could be APIs that wasn't to guard against bools being passed as ints? If don't want to diverge from mypy then you should open up `origin_type_checkers` as a public API for people that do.

**Comment by agronholm** [comment]
There already is such an API: https://typeguard.readthedocs.io/en/latest/extending.html

**Comment by makslevental** [comment]
> There already is such an API: https://typeguard.readthedocs.io/en/latest/extending.html

this is for custom types - the [values](https://github.com/agronholm/typeguard/blob/7b9c127395ab259b03c89d7aa170718e51a084ec/src/typeguard/_checkers.py#L672) in the `origin_type_checkers` dictionary are not affected (`checker_lookup_functions` is exactly where i first went)

**Comment by agronholm** [comment]
No, but the custom lookup functions are called first, and if you return a custom checker for `bool`, it should be used. Let me know if this is not the case.

**Comment by makslevental** [comment]
Cool that worked - I had to "bind" all of `float`, `int`, `bool` but that's fine. Thanks!

Just in case you were curious, I'm using `typeguard` for essentially (expensive) multiple dispatch in a [MLIR/PyTorch project](https://github.com/nod-ai/PI) ([here's](https://github.com/nod-ai/PI/blob/main/pi/dispatcher/function.py#L60) the particular spot). Great library - way better architected and designed than the alternative (cough `beartype` cough).
