### ISSUE TITLE
#289 makes arguments non-optional for python3.9

### ISSUE THREAD

**Issue by supersergiy** [agronholm/typeguard#295]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

Tip of Main

### Python version

3.9

### What happened?

#289 makes arguments non-optional for python3.9

Pinning to commit `63b28186a9d00bb489f282f80b76834ac3d057fc` solves the issue.

### How can we reproduce the bug?

```python
from typeguard import typechecked

@typechecked
def foo(a: bool = True):
    ...
foo()
```

Outcome:
```
Traceback (most recent call last):
  File "/home/sergiy/tmp/type_adventures/recomp.py", line 6, in <module>
    foo()
TypeError: foo() missing 1 required positional argument: 'a'
```

**Comment by agronholm** [comment]
Looks like the recompiled function is missing `__defaults__`.
