### ISSUE TITLE
@typechecked failed to identify correct type

### ISSUE THREAD

**Issue by FFFluoride** [agronholm/typeguard#296]
### Things to check first

- [x] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

2.13.3

### Python version

Python 3.11.0rc1

### What happened?

What happened
relevant imports:
```
from typeguard import typechecked
from dataclasses import dataclass
```
I had  a class:
```
@typechecked
@dataclass
class SpeciesCollection:
  """Class to keep track of species in db"""
  collection: list[dict[float]]
```
`SpeciesCollection` was used in class `Context`:
```
@typechecked
@dataclass
class Context:
  path: str
  species_dict: SpeciesCollection
  cat_collection: CatCollection
```

In a different script I imported this module (which is called cat_db_mod_rewrite):
```
#testing.py
import sys
sys.path.append("../modules/")
from cat_db_mod_rewrite import *
from datetime import datetime

context = Context(
  "~/.pickles",
  SpeciesCollection([
    {"maincoon": 500.0},
    {"black": 400000.0}
  ]),
  CatCollection([])
)
```

When I ran `testing.py`, it gave me the error:
```
Traceback (most recent call last):
  File "/home/fffluoride/dox/python/school/CAT-MAN/programs/testing.py", line 8, in <module>
    SpeciesCollection([
  File "/home/fffluoride/.local/lib/python3.11/site-packages/typeguard/__init__.py", line 1032, in wrapper
    check_argument_types(memo)
  File "/home/fffluoride/.local/lib/python3.11/site-packages/typeguard/__init__.py", line 873, in check_argument_types
    check_type(description, value, expected_type, memo)
  File "/home/fffluoride/.local/lib/python3.11/site-packages/typeguard/__init__.py", line 757, in check_type
    checker_func(argname, value, expected_type, memo)
  File "/home/fffluoride/.local/lib/python3.11/site-packages/typeguard/__init__.py", line 458, in check_list
    check_type('{}[{}]'.format(argname, i), v, value_type, memo)
  File "/home/fffluoride/.local/lib/python3.11/site-packages/typeguard/__init__.py", line 757, in check_type
    checker_func(argname, value, expected_type, memo)
  File "/home/fffluoride/.local/lib/python3.11/site-packages/typeguard/__init__.py", line 416, in check_dict
    key_type, value_type = expected_type.__args__
    ^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```
I expected the stack trace to be not that good so I ran this program through the pudb debugger.
I inspected the types and was confused by expected_type being GenericAlias which every time I tried to see what was in the GenericAlias, there was just another GenericAlias. I ran in the debugger shell with the types in the program: `check_type(expected_type, value, 'arg')` and there was no exception thrown (I have an image attatched)
![Screenshot from 2023-02-18 12-39-25](https://user-images.githubusercontent.com/82343884/219866300-116ae10e-a67c-42ee-8df5-5d0e3e897e85.png).
I don't really understand how exactly this module works so I was wondering if it was a bug.

### How can we reproduce the bug?

I made a small script that reproduces the behaviour I saw:
```
from typeguard import typechecked
from dataclasses import dataclass

@typechecked
@dataclass
class Collection:
    collection: list[dict[float]]

my_collection = Collection([
    {"something": 10},
    {"a_thing": 100}
])
```

**Comment by FFFluoride** [comment]
Forgot to include the screenshot of pudb for the reproducable version of the issue
![Screenshot from 2023-02-18 12-51-31](https://user-images.githubusercontent.com/82343884/219866809-847d49d9-779a-45ba-86d7-9061f88c53c6.png)

**Comment by agronholm** [comment]
Have you tried 3.0.0b2 or master? I don' think Typeguard supports Python 3.11 in the 2.x series, and in `master`, `@typechecked` has been totally refactored.

**Comment by FFFluoride** [comment]
Can I upgrade the package using pip? I'm gonna try to see how I do that.

**Comment by FFFluoride** [comment]
> Have you tried 3.0.0b2 or master? I don' think Typeguard supports Python 3.11 in the 2.x series, and in `master`, `@typechecked` has been totally refactored.

Seems like that didn't work
![Screenshot from 2023-02-18 15-29-34](https://user-images.githubusercontent.com/82343884/219874242-1f6b8d18-abd5-475b-a8ba-e2dd168f2b53.png)

**Comment by agronholm** [comment]
Sorry, I should've read your issue report better (but I'm on vacation, so that's my excuse). Type checking of class members isn't supported at the moment. Are you sure you checked the existing issues? Like [this one](https://github.com/agronholm/typeguard/issues/161)?

**Comment by FFFluoride** [comment]
> 

oops sorry, I remember scanning through the issues but I must've missed this one. I suppose you can close this issue but may I ask why?

**Comment by agronholm** [comment]
Why checking of class members is not supported? One, I haven't had the time to do it, and two, doing it safely is very tricky.

**Comment by FFFluoride** [comment]
I see well good luck with that loving your module despite the support for dataclasses. And hey maybe I'll even contribute If I have the time, enjoy the rest of your holiday
