### ISSUE TITLE
Include `type(value)` in `TypeCheckError`'s

### ISSUE THREAD

**Issue by supersergiy** [agronholm/typeguard#297]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

It would be helpful to see offender's type in the exception. Perhaps something simple can suffice for most cases?

### Use case

Whenever I get a `typeguard.TypeCheckError`, the first thing I do is usually looking into the offender's type manually.

**Comment by agronholm** [comment]
I agree, this is something I intend to add before the final release.

**Comment by agronholm** [comment]
Would you mind checking the linked PR? I'm just about ready to make a new release then.
