### ISSUE TITLE
 #294 breaks compatibility with `attrs`

### ISSUE THREAD

**Issue by supersergiy** [agronholm/typeguard#300]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

Tip of Main

### Python version

3.10

### What happened?

#294 breaks compatibility with `attrs`.
No problem on b660f28efd9e98542864b66ab6bffdb59e5a0fee.

### How can we reproduce the bug?

```python
from typeguard import typechecked
import attrs

@typechecked
@attrs.mutable
class A:
    ...
```

```
...
  File "/home/sergiy/tmp/typeguard/src/typeguard/_transformer.py", line 257, in visit_ClassDef
    self.generic_visit(node)
  File "/usr/lib/python3.10/ast.py", line 494, in generic_visit
    value = self.visit(value)
  File "/usr/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/home/sergiy/tmp/typeguard/src/typeguard/_transformer.py", line 312, in visit_FunctionDef
    self.generic_visit(node)
  File "/usr/lib/python3.10/ast.py", line 494, in generic_visit
    value = self.visit(value)
  File "/usr/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/usr/lib/python3.10/ast.py", line 494, in generic_visit
    value = self.visit(value)
  File "/usr/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/home/sergiy/tmp/typeguard/src/typeguard/_transformer.py", line 566, in visit_Assign
    annotation = self._memo.variable_annotations.get(name.id)
AttributeError: 'Subscript' object has no attribute 'id'
```

**Comment by agronholm** [comment]
I am currently doing a cleanup based on errors reported by Mypy. I think this is one of those problems I've fixed locally. I'll push once I'm done with the last two unsolved errors.

**Comment by agronholm** [comment]
Oh btw, that order of decorators is not going to work. You need to reverse them. The changes I have lined up should raise a proper error if you try this.

**Comment by agronholm** [comment]
Oh right, I was thinking of functions. It fails with a different error on my local version, and I'm not sure why.

**Comment by supersergiy** [comment]
Oh, interesting. Would reversing decorator order still typecheck the attrs-generated `__init__`?

**Comment by agronholm** [comment]
It wouldn't. For classes, decorator order is a whole different ballgame, hence my retraction earlier. On my local version, I get `ValueError: empty body on If` which is weird since no `if` statements are involved.

**Comment by agronholm** [comment]
The trouble is that `typeguard` recompiles functions with instrumentation code injected, but it needs the original source to do that. So it cannot instrument code generated on the fly.

**Comment by agronholm** [comment]
Ok, my debugging shed some light into the mystery: instead of the target class, `@typechecked` gets `<function _ClassBuilder._make_getstate_setstate.<locals>.slots_getstate at 0x7fde28c6f130>`. This function does not have a `__wrapped__` attribute, so `@typechecked` think it's being used to instrument a function not even belonging to the current module.

**Comment by agronholm** [comment]
FYI, I just pushed some commits to master now. The main code base is now mypy clean.

**Comment by agronholm** [comment]
Further debugging on this revealed that `@typechecked` does get the target class as intended, but it then tries to instrument functions from `attrs`, thinking they are methods belonging to the class. I've fixed this by checking that the module name and qualname match the containing class.

**Comment by supersergiy** [comment]
Awesome! Thanks for the prompt fix
