### ISSUE TITLE
Typechecked fails when *args followed by keyword argument with default value

### ISSUE THREAD

**Issue by tvdboom** [agronholm/typeguard#305]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

rc1

### Python version

3.9

### What happened?

typechecked raises an exception that shouldn't be raised when a function has args followed by kwargs with default. For code snippet below, error is:
```
Traceback (most recent call last):
  File "C:\Users\Mavs\Documents\Python\ATOM\venv39\lib\site-packages\IPython\core\interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-df714957fb70>", line 1, in <module>
    runfile('C:\\Users\\Mavs\\Documents\\Python\\ATOM\\test.py', wdir='C:\\Users\\Mavs\\Documents\\Python\\ATOM')
  File "C:\Program Files\JetBrains\PyCharm 2022.1.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2022.1.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\Mavs\Documents\Python\ATOM\test.py", line 133, in <module>
    func(1)
TypeError: func() missing 1 required keyword-only argument: 'a'
```

### How can we reproduce the bug?

```
from __future__ import annotations
from typeguard import typechecked

@typechecked
def func(*args, a: int | None = None):
    # do whatever...     
    pass

func(1)  # This should pass, since a defaults to None
```

**Comment by agronholm** [comment]
Fascinating. I checked with `config.debug_instrumentation = True` and there are no problems with the AST transformation, so this must be a problem with the actual generated function object (some dunder attribute missing?).

**Comment by tvdboom** [comment]
I wouldn't know tbh. But this error didn't occur with typeguard version 2.13.3. It started appearing after I updated

**Comment by agronholm** [comment]
Unlike 2.x, Typeguard 3.0 recompiles functions with type checking machinery injected instead of wrapping the functions, hence the issue.

**Comment by agronholm** [comment]
The weirdest aspect of this is that this works just fine in the test suite, but not when running separately.

**Comment by agronholm** [comment]
I found the bug: the `__kwdefaults__` attribute was not transferred from the original to the new one. How it still passed the unit test is still under investigation.

**Comment by agronholm** [comment]
Never mind, PEBCAK. Fixed.

**Comment by tvdboom** [comment]
Awesome, thanks for the quick fix!
