### ISSUE TITLE
ValueError: tuple.index(x): x not in tuple for decorator on class

### ISSUE THREAD

**Issue by tonkolviktor** [agronholm/typeguard#309]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

3.0.0

### Python version

3.8

### What happened?

Hi, first of all thanks for the module!

Since the new version is out we get this:
```
---> 26 from <our_module> import RelationalDatabase

/databricks/python_shell/dbruntime/PythonPackageImportsInstrumentation/__init__.py in import_patch(name, globals, locals, fromlist, level)
    165             # Import the desired module. If you’re seeing this while debugging a failed import,
    166             # look at preceding stack frames for relevant error information.
--> 167             original_result = python_builtin_import(name, globals, locals, fromlist, level)
    168 
    169             is_root_import = thread_local._nest_level == 1

/databricks/python/lib/python3.8/site-packages/<our_module>/base.py in <module>
     33 
     34 @typechecked
---> 35 class RelationalDatabase(Service, ABC):

/databricks/python/lib/python3.8/site-packages/typeguard/_decorators.py in typechecked(target)
    140         for key, attr in target.__dict__.items():
    141             if is_method_of(attr, target):
--> 142                 retval = instrument(attr)
    143                 if isfunction(retval):
    144                     setattr(target, key, retval)

/databricks/python/lib/python3.8/site-packages/typeguard/_decorators.py in instrument(f)
     86         # Existing closure needs modifications
     87         cell = make_cell()
---> 88         index = new_code.co_freevars.index(f.__name__)
     89         closure = f.__closure__[:index] + (cell,) + f.__closure__[index:]
     90     else:

ValueError: tuple.index(x): x not in tuple
```

### How can we reproduce the bug?

I'm unsure if this is always the case for class decorator or if in our setup is something extra. Feel free to ask.

**Comment by agronholm** [comment]
I really need to know what the decorated function is that causes this. No way for me to debug otherwise.

**Comment by tonkolviktor** [comment]
do you mean this?

```
     34 @typechecked
---> 35 class RelationalDatabase(Service, ABC):
```
`@typechecked` is:
`from typeguard import typechecked`

**Comment by agronholm** [comment]
No, I mean the method or other function it was currently instrumenting. In other words, the `attr` variable in the second to last frame in your traceback.

**Comment by tonkolviktor** [comment]
ok, I've narrowed it down:
```dummy.py
from contextlib import contextmanager
from typeguard import typechecked


@typechecked
class Dummy:
    @contextmanager
    def as_transaction(self):
        pass
```
from dummy import Dummy reproduces the problem

**Comment by agronholm** [comment]
Ok, I can reproduce it here now. Curious thing – `@typechecked` is supposed to ignore anything wrapped by other decorators.

**Comment by agronholm** [comment]
Ahh...I see the problem now. The check for `__wrapped__` did not apply when using the decorator on a class.
