### ISSUE TITLE
Type checking in lists doesn't work anymore

### ISSUE THREAD

**Issue by armintaenzertng** [agronholm/typeguard#310]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

3.0.0

### Python version

3.10.6

### What happened?

Hi, thanks for updating the library! Unfortunately, the update seems to have broken the type checking of lists, see the minimum example below. I expect the `test_typecheck()` to raise an error, as 42 is not a string. It did until now, but not anymore, so I believe this is a bug.

It does fail, though, when using `list_test([42, "test"])`, so maybe only the first list item is checked?

### How can we reproduce the bug?
```python
from typing import List

from typeguard import typechecked


@typechecked
def list_test(string_list: List[str]):
    pass

def test_typecheck():
    list_test(["test", 42])
```

**Comment by agronholm** [comment]
It seems that when I compressed the changelog, I neglected to mention this change. Typeguard, like beartype, now only checks the first element of each sequence by default to avoid causing a major performance impact. To get the old behavior, you can change `typeguard.config.collection_check_strategy` to `CollectionCheckStrategy.ALL_ITEMS`. See [this](https://typeguard.readthedocs.io/en/stable/api.html#typeguard.CollectionCheckStrategy) for further info.

**Comment by armintaenzertng** [comment]
Thanks for the hint and the quick update of the changelog! :)

As a sidenote: Another breaking change for us was that instead of `TypeError` the type check now raises `TypeCheckError`.

**Comment by agronholm** [comment]
> As a sidenote: Another breaking change for us was that instead of `TypeError` the type check now raises `TypeCheckError`.

Ack. At some point in my implementation it inherited from `TypeError`, maybe that's why I forgot about it.
