### ISSUE TITLE
Typeguard 3.0.0 breaks when being run with a test folder containg an __init__.py

### ISSUE THREAD

**Issue by DanaBCooper** [agronholm/typeguard#311]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

3.0.0

### Python version

3.7,3.8,3.9

### What happened?

When running pytest on a tests folder that contains an __init__.py, I encountered the following issue

```
packages/typeguard/_pytest_plugin.py", line 6, in <module>
2023-03-15 00:58:11+0000      from pytest import Config, Parser
2023-03-15 00:58:11+0000  ImportError: cannot import name 'Config' from 'pytest' 
```

Pinning typeguard to 2.13.3 resolved the issue (it was a dependency of another unit I was using). I came to believe the __init__ was responsible after reading https://stackoverflow.com/questions/41748464/pytest-cannot-import-module-while-python-can

I believe typeguard 3.0.0 exposed this issue if an __init__.py is present.

In trying to find a minimal viable reproducer, it appears the __init__.py is not necessary for the issue to appear?

### How can we reproduce the bug?

```
pip3 install pytest==6.2.5 typeguard==3.0.0
pytest
```

**Comment by agronholm** [comment]
> Also breaks for most recent pytest ==7.2.2 , by the way

Doesn't happen for me.

**Comment by DanaBCooper** [comment]
Sorry, test environment was using the wrong version. It does seem to only break on older versions - ie pytest 6.2.5. Am I to take that as those aren't supported by Typeguard? Apologies for the confusion

**Comment by agronholm** [comment]
I haven't tested it on such old versions. I don't know what the minimum pytest version is.

**Comment by agronholm** [comment]
I specified pytest 7 as the minimum version.

**Comment by DanaBCooper** [comment]
Thank you! :)
