### ISSUE TITLE
Typeguard 3.0.0 Raises Error when Overwriting Variable Name

### ISSUE THREAD

**Issue by justinessert** [agronholm/typeguard#313]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

3.0.0

### Python version

3.9.13

### What happened?

It appears like there is a bug in the newest version of typeguard (`3.0.0`) that causes `typechecked` to raise an error if one of the input parameters in the function being checked is overwritten in the same function to a different type. For example, take this function:

```python
@typechecked
def convert_to_float(
    a: int
) -> float:
    a = float(a)
    return a
```

If I call this function with `convert_to_float(1)` then I get the error `typeguard.TypeCheckError: a is not an instance of int`, presumably because it is checking the type of `a` only at the end of the function.

To confirm this, I changed the example code to the following, and this did not throw an error:

```python
@typechecked
def convert_to_float(
    a: int
) -> float:
    b = float(a)
    return b
```

### How can we reproduce the bug?

```python
@typechecked
def convert_to_float(
    a: int
) -> float:
    a = float(a)
    return a
convert_to_float(1)
```

**Comment by agronholm** [comment]
Typeguard is doing the right thing here, since `float` is not assignable to `int`. Mypy will tell you as much:
`Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]`

**Comment by justinessert** [comment]
@agronholm This is not correct. The input to this function is indeed an integer type and the output is a float type. There should not be an error when we call this function

**Comment by agronholm** [comment]
The return type annotation is irrelevant. What both Typeguard and Mypy see here is the local variable `a`, of type `int` being assigned an incompatible value (`float`).
