### ISSUE TITLE
Global config introduced in 3.0.0 isn't threadsafe

### ISSUE THREAD

**Issue by antonagestam** [agronholm/typeguard#316]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

3.0.1

### Python version

3.11.0

### What happened?

Hi there 👋

I'm the maintainer of [phantom-types](https://github.com/antonagestam/phantom-types), a project that relies heavily on typeguard. It's very nice to see all the new activity going on here! 👍

While looking into the changes for 3.0.0, I noticed the change in default strategy for items of collections. phantom-types relies on the original behavior, and would have to configure `ALL_ITEMS` whenever making calls to `check_type`. However, I noticed that the configuration is really just a globally shared state, with no facilities for thread safety. As phantom-types is a library that is used in many different contexts by its users, some of them are bound to be using threads.

Hence, the current implementation in 3.0.0 wouldn't really be safe to start using, as it'd be only a matter of time before users stumble upon this race condition when using threads (or asyncio).

Would you be open to somehow addressing this? I think ideally from my perspective, there would be a way to pass in config directly to the `check_type` call, instead of relying on the integrity of globally shared state. What do you think?

Again, typeguard really enables phantom-types, and I'm plenty grateful for this library!

### How can we reproduce the bug?

In this example, we expect `target` to never be called, because locally in `thread_a` we're setting to check `ALL_ITEMS` and then calling with an invalid list. Yet, because another thread is concurrently altering the global config, only the first item of the list is checked, and `target` is called.

```python
from concurrent.futures import ThreadPoolExecutor
import time

import pytest
import typeguard


@typeguard.typechecked
def target(arg: list[int]) -> int:
    # This should never be reached, because we're calling with invalid arguments.
    assert all(isinstance(item, int) for item in arg), "not all items are int"
    return 1


def test_typeguard_threadsafe():
    typeguard.config.collection_check_strategy = (
        typeguard.CollectionCheckStrategy.FIRST_ITEM
    )

    def thread_a():
        typeguard.config.collection_check_strategy = (
            typeguard.CollectionCheckStrategy.ALL_ITEMS
        )
        # Uncommenting this sleep makes the test pass, proving there's a race condition.
        time.sleep(.2)
        with pytest.raises(typeguard.TypeCheckError):
            target([1, "2"])

    def thread_b():
        time.sleep(.1)
        typeguard.config.collection_check_strategy = (
            typeguard.CollectionCheckStrategy.FIRST_ITEM
        )

    with ThreadPoolExecutor() as pool:
        future_a = pool.submit(thread_a)
        future_b = pool.submit(thread_b)
        future_a.result()
        future_b.result()
```

**Comment by agronholm** [comment]
The current config system wasn't designed to accommodate being changed on a per-thread/task basis at run time. I already added a huge amount of changes to the library and was a bit overwhelmed by the complexity, so I decided to limit configuration support for the 3.0 release, especially given that there was no such thing in the 2.x series in the first place.

I'm open to suggestions on how to address this.

**Comment by antonagestam** [comment]
@agronholm I'll experiment a bit and get back here 🙂

**Comment by antonagestam** [comment]
@agronholm I think this is the gist of what I'm suggesting (+/- docs, tests): https://github.com/agronholm/typeguard/pull/317. Basically all internal check functions are updated to require passing a configuration object. Public functions are updated to accept an optional `config` parameter, that defaults to `global_config`. It's a non-breaking change in the public API. Instead of this:

```python
typeguard.config.collection_check_strategy = CollectionCheckStrategy.ALL_ITEMS
check_type([1], list[int])
```

I would now be able to pass in the configuration.

```python
config = replace(
    typeguard.config,
    collection_check_strategy=CollectionCheckStrategy.ALL_ITEMS,
)
check_type([1], list[int], config=config)
```

**Comment by agronholm** [comment]
What's `replace()` anyway?

**Comment by antonagestam** [comment]
> So the gist is to only support explicit config in `check_type()`?

Yes, I _think_ so, at least that solves my concerns. Are the these entry-points deprecated?

- `check_argument_types`
- `check_return_type`
- `check_send_type`
- `check_yield_type`
- `check_variable_assignment`

**Comment by antonagestam** [comment]
> What's `replace()` anyway?

[`dataclasses.replace`](https://docs.python.org/3/library/dataclasses.html#dataclasses.replace), but the means of copying isn't really important here I think :)

**Comment by agronholm** [comment]
> > So the gist is to only support explicit config in `check_type()`?
> 
> Yes, I _think_ so, at least that solves my concerns. Are the these entry-points deprecated?
> 
> * `check_argument_types`
> * `check_return_type`
> * `check_send_type`
> * `check_yield_type`
> * `check_variable_assignment`

They're not part of the public API.

**Comment by antonagestam** [comment]
@agronholm Oh, I didn't find any usages with PyCharm, I see now there's some special sauce here.

I guess it boils down to deciding whether `@typechecked` should always use the global configuration, or if it should have the same ability of accepting a configuration as `check_type`? Do you have an opinion?

**Comment by agronholm** [comment]
My plan was to add parameters to `@typechecked` that would allow overriding config options, but I wasn't sure how exactly to implement it. The same would probably have to be added to the import hook. Unfortunately, my mental exhaustion killed these plans in the crib.

**Comment by agronholm** [comment]
I was thinking of allowing all the configuration options to be overridden by passing arguments to `@typechecked()`. That would introduce some unfortunate duplication though. Not sure if there's any way around that.

As it happens, I may need to make a new major version bump soon, so if this requires breaking changes, I would need to get it done at the same time.

**Comment by antonagestam** [comment]
> I was thinking of allowing all the configuration options to be overridden by passing arguments to @typechecked().

This sounds sensible! 👍

> That would introduce some unfortunate duplication though.

Just to clarify, do you mean duplication as in one would have to pass the config for each decoration, like below?

```python
@typechecked(config_param="config_value")  # config_param from here ...
def fn1():
    ...

@typechecked(config_param="config_value")  # ... is duplicated by config_param here.
def fn2():
    ...
```

If so, two ideas pop up that aren't mutually exclusive.

We could still allow passing a full `config: TypeCheckConfiguration` object, the signature would be a messy perhaps, but totally possible. This would allow users to instantiate a single configuration object and then reuse it.

We can mention in documentation that configuration can be bound by the decorator factory, this wouldn't need any extra implementation work, i.e.:

```python
typechecked_bound = typechecked(config_param="config_value")

@typechecked_bound
def fn1():
    ...

@typechecked_bound
def fn2():
    ...
```

**Comment by agronholm** [comment]
Option 1: Have `@typechecked` accept a `config` argument. The downside: it would override _all_ configuration options, even if you just wanted to override one of them.
Option 2: Have `@typechecked` accept the options as named keyword arguments. The downside: whenever a new option is introduced, we have to add it to both `TypeCheckConfiguration` and `@typechecked`, which is the duplication I was talking about.
Option 3: Have `@typechecked` accept arbitrary keyword arguments, or a dict of override arguments. The downside: either these arguments will be untyped, or we have to introduce a new `TypedDict` for that, which again leads to duplication.

**Comment by antonagestam** [comment]
@agronholm I'd like to experiment with ParamSpec to see if we could make option 3 typed.

**Comment by antonagestam** [comment]
I was hoping something like this would work: https://mypy-play.net/?mypy=master&python=3.11&gist=69ea4b9c1941a319b2409c04841bdbb7

Since it doesn't, my vote lies with option 2. There's some duplication, but in my opinion the duplication is worth it for a friendlier API.

**Comment by agronholm** [comment]
Option 2 is tenable as long as `@typechecked` is the only place where the options need to be duplicated. But what about `check_type()` then? Would we have a completely different solution for that? What I had in mind was some sort of `ConfigOverride` class which would duplicate the options in `TypeCheckConfiguration` but would allow fields to be left as `None` (or a sentinel value that signifies "not set"). Then we would have a method in either class that produces a new config object by applying the changes from `ConfigOverride`.

**Comment by antonagestam** [comment]
I updated the PR yesterday to do sort of option 2 for check_type, but left out one option that I felt doesn't make sense in that context. 

If you feel it will be a maintenance burden to keep those in sync, I don't think it would be a bad decision to accept a config instance instead. Do you want to ponder on the decision for a bit?

---

The description of ConfigOverride sounds unnecessary complex to me, what's the benefit over the standard library's `dataclasses.replace`?

**Comment by agronholm** [comment]
FYI: 4.0.0rc1 is out.
