### ISSUE TITLE
Bound methods be unboud methods after be typechecked

### ISSUE THREAD

**Issue by nycholas** [agronholm/typeguard#319]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

3.0.1

### Python version

3.10.10

### What happened?

The bound methods not be unbound by the typeguard after the compile stage.

### How can we reproduce the bug?

Save the code above in a file, main.py in that example:

```python
from typeguard import typechecked

class C:
    def fn(self, p1: str = 'None') -> str:
        return f'method: {p1}'

c = C()
c_fn_wrapped = typechecked(c.fn)
print(c_fn_wrapped())
```

In the shell:

```shell
$ python -m venv .venv
$ source .venv/bin/activate
$ pip install typeguard
$ python main.py
$ python main.py 
Traceback (most recent call last):
  File "/.../main.py", line 9, in <module>
    print(c_fn_wrapped())
TypeError: C.fn() missing 1 required positional argument: 'self'
```

Now change the typeguard version to the previous stable (2.13.3)

```shell
$ pip install typeguard==2.13.3
$ python main.py
method: None
```

**Comment by agronholm** [comment]
What's the actual use case here? You're supposed to use `@typechecked` as a decorator. Unlike in the 2.x series where it wraps the target function, in 3.x, it recompiles the target function with instrumentation added, so this result is not unexpected.

**Comment by nycholas** [comment]
I have a Flask library[1] that uses the typeguar to run-time type checking for functions and methods that work as route which tells to Flask what URL should trigger the functions (or methods), like the example below:

```
from flask import Flask
from flask_jsonrpc import JSONRPC

app = Flask("application")
jsonrpc = JSONRPC(app, "/api", enable_web_browsable_api=True)

@jsonrpc.method("App.index")
def index() -> str:
    return "Welcome to Flask JSON-RPC"
```

When the Flask calls the function trigged by an URL, the library uses the typeguard to run-time checking the hint types from this function.

I know that in 3.x the typeguard recompiles the target function with instrumentation, I thought the all features that 2.x has the version 3.x would have too, but I'm wrong in that, correct?

Thank you.




[1] - https://github.com/cenobites/flask-jsonrpc

**Comment by agronholm** [comment]
The API and semantics have changed, hence the major version bump. It looks like `flask-jsonrpc` has taken that into account by specifying `typeguard==2.13.3` as a dependency. So by trying to use typeguard 3.0 with it, you're breaking that dependency.

There is no wrapping decorator anymore, as it caused an extra stack frame to be added and did not allow typeguard to inspect variable assignments, among other things.

**Comment by nycholas** [comment]
OK, I understand. 

Thank you for your time ;).
