### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by samsammurphy** [agronholm/typeguard#327]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

It would be nice to explicitly say how to install this package somewhere in the github README.md and/or docs

    $ pip install typeguard

### Use case

ease of mind and gets people started quickly

**Comment by agronholm** [comment]
Typeguard is installed the exact same way as all other packages from PyPI. The first search result for that is https://packaging.python.org/en/latest/tutorials/installing-packages/ which is a pretty comprehensive guide. I would understand this request if Typeguard required extraordinary steps.
