### ISSUE TITLE
Cannot check types that are shadowed by argument names

### ISSUE THREAD

**Issue by jolaf** [agronholm/typeguard#337]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

4.0.0rc2 master

### Python version

3.10.6

### What happened?

```
Traceback (most recent call last):
  File "/media/sf_d/WWPass/git/python-test/test.py", line 4, in <module>
    import_module('A')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/jolaf/git/typeguard/src/typeguard/_importhook.py", line 122, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/media/sf_d/WWPass/git/python-test/A.py", line 6, in <module>
    f(bool)
  File "/media/sf_d/WWPass/git/python-test/A.py", line 1, in f
    def f(type: type | None = None) -> None:
  File "/home/jolaf/git/typeguard/src/typeguard/_functions.py", line 135, in check_argument_types
    check_type_internal(value, annotation, memo)
  File "/home/jolaf/git/typeguard/src/typeguard/_checkers.py", line 756, in check_type_internal
    checker(value, origin_type, args, memo)
  File "/home/jolaf/git/typeguard/src/typeguard/_checkers.py", line 432, in check_uniontype
    raise TypeCheckError(f"did not match any element in the union:\n{formatted_errors}")
typeguard.TypeCheckError: argument "type" (class bool) did not match any element in the union:
  bool: is not an instance of bool
  NoneType: is not an instance of NoneType
```

### How can we reproduce the bug?

`test.py`:
```python3
from importlib import import_module
from typeguard import install_import_hook
with install_import_hook(('A',)):
    import_module('A')
```

`A.py`:
```python3
def f(type: type | None = None) -> None:
    pass

f(bool)
```

Run:
```shell
$ python3 test.py
```

**Comment by jolaf** [comment]
If argument name is changes, crash doesn't happen.

**Comment by jolaf** [comment]
This piece of code is extracted from `tornado/options.py`.

**Comment by agronholm** [comment]
Oh dear. The problem here is that the internal checking functions now can't reference both the argument variable and the actual type because the argument name shadows the type in the global namespace. Even converting that to a forward reference wouldn't help because it would just resolve to the argument value.

**Comment by jolaf** [comment]
By the way, on typeguard 3.0.2 crash also doesn't happen.

**Comment by jolaf** [comment]
> the argument name shadows the type in the global namespace

I wonder how Python itself and mypy handle this.
Probably, the types are stored in a separate registry?

**Comment by agronholm** [comment]
> By the way, on typeguard 3.0.2 crash also doesn't happen.

Because typeguard 3.0.2 looks up the function object and extracts the type hints from its `__annotations__` property. That approach turned out to be a dead-end, as the function object can't always be looked up.

**Comment by agronholm** [comment]
> > the argument name shadows the type in the global namespace
> 
> I wonder how Python itself and mypy handle this. Probably, the types are stored in a separate registry?

Python only handled annotations on the function object; it doesn't touch them inside the function body. Mypy doesn't do run-time lookups so it's not affected.

**Comment by jolaf** [comment]
If it's difficult to fix this issue properly, it would be nice at least to avoid false positives.

**Comment by agronholm** [comment]
I was thinking that I could detect such cases and create explicit type aliases, but unfortunately that will not work in all cases. For 4.0.0, I think I will just skip the type checks. I wonder if I should at least emit warnings when this happens?

**Comment by jolaf** [comment]
Yes, I think, warnings that would not crash the app would be better than silence.

**Comment by jolaf** [comment]
Don't you think it would be nice to properly fix this in the future?
Shouldn't this issue be kept open?

**Comment by agronholm** [comment]
Can you think of a theoretical way of properly fixing this?

**Comment by jolaf** [comment]
Nope, I just hope that is possible. :)

**Comment by agronholm** [comment]
There is yet another issue not resolved in master yet: cases where local variable assignments or classes shadow types used in type checking of variable assignments, yield or send type checks, or return type checks. These could be worked around simply by assigning function-local aliases for those types in the beginning of the function body. For that, the function body needs to be examined beforehand for any newly assigned names that would conflict with the names of the types being checked against.

**Comment by jolaf** [comment]
Can typing information be extracted from function annotations, at least in some cases?

**Comment by agronholm** [comment]
You would have to get the function object first, and that's the reason the 3.x series was a bust. You can't rely on getting hands on the original function object.

**Comment by agronholm** [comment]
Consider the following code:
```python

class foo:
   pass

def pathological(foo: foo) -> None:
    pass
```
How would you write code inside `pathological()` that checks the `foo` argument against the type `foo`? This is not a problem for static checkers, or even typeguard 3.x. It's a problem for typeguard 4.x which doesn't rely on looking up the original function object (which in many cases is completely impossible).

**Comment by jolaf** [comment]
Maybe the function object could be used in cases when it's available and usable to resolve shadowed types?

**Comment by agronholm** [comment]
And if it's not? Like in nested functions? I can construct a corner case so pathological that no run-time type checker could resolve the types properly. Function object lookup is not only error prone, but also potentially very slow. I don't think these cases are common enough to warrant bending over backwards to properly check the affected arguments/yields/sends/returns/assignments.

Typeguard 4.0 has been mentally taxing enough that I just want to be done with it. I will still add the warnings I talked about before the final release though, so hopefully that will be enough for now.

**Comment by jolaf** [comment]
I tried the current master on `tornado`, and it still crashes, but in a different way:

```
Traceback (most recent call last):
  File "/media/sf_d/WWPass/git/android/app/test.py", line 4, in <module>
    import_module('A')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/jolaf/git/typeguard/src/typeguard/_importhook.py", line 122, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/media/sf_d/WWPass/git/android/app/A.py", line 15, in <module>
    f("", type = bool)
  File "/media/sf_d/WWPass/git/android/app/A.py", line 3, in f
    def f(
  File "/home/jolaf/git/typeguard/src/typeguard/_functions.py", line 135, in check_argument_types
    check_type_internal(value, annotation, memo)
  File "/home/jolaf/git/typeguard/src/typeguard/_checkers.py", line 759, in check_type_internal
    if not isinstance(value, origin_type):
  File "/usr/lib/python3.10/typing.py", line 396, in __instancecheck__
    raise TypeError(f"{self} cannot be used with isinstance()")
TypeError: typing.Optional cannot be used with isinstance()
```

Here's the updated test:

```python3
from typing import Any, Callable, Optional

def f(
        name: str,
        default: Any = None,
        type: Optional[type] = None,
        help: Optional[str] = None,
        metavar: Optional[str] = None,
        multiple: bool = False,
        group: Optional[str] = None,
        callback: Optional[Callable[[Any], None]] = None,
    ) -> None:
    pass

f("", type = bool)
```

**Comment by agronholm** [comment]
Damn, `Optional` needs special casing because it should be completely erased if it doesn't have a subscript.

**Comment by agronholm** [comment]
Could you create another issue for that?

**Comment by jolaf** [comment]
https://github.com/agronholm/typeguard/issues/342

**Comment by vthemelis** [comment]
@agronholm , is it possible to always access the type object (which I think is what you need) through `globals()`?

For example:

```Python3
def foo(int):
    int_type = globals()["int"]
```

I would imagine this always works as the annotation name in the global namespace should be a type anyway.

**Comment by agronholm** [comment]
Not always:
```python
def function() -> None:
    class A: pass

   def nested(a: A) -> None:
       pass

    nested(A())
```

**Comment by vthemelis** [comment]
Yes, makes sense. :/

What about creating an alias for the type just before the function definition and using that whiting the function?

**Comment by agronholm** [comment]
How would that work with `@typechecked`?

**Comment by vthemelis** [comment]
> How would that work with `@typechecked`?

I'm not very familiar with the code to give a concrete answer but it seem like `@typechecked` can lead to rewriting parts of the code surrounding it (eg https://github.com/agronholm/typeguard/issues/352). This can be rewriting parts of the tree or importing further typeguard helper functions. This would just be the equivalent of transforming:

```Python
def foo(int: int):
    ...
```
into

```Python
UNIQUE = int
def foo(int: int):
    # When needing to access the `int` type here, we access `UNIQUE` instead.
    ...
```

**Comment by agronholm** [comment]
> I'm not very familiar with the code to give a concrete answer but it seem like @typechecked can lead to rewriting parts of the code surrounding it (eg https://github.com/agronholm/typeguard/issues/352).

A decorator cannot replace any code or variables surrounding the function.
