### ISSUE TITLE
`@typechecked` decorator no longer respects `sys.flags.optimize`

### ISSUE THREAD

**Issue by zackmccord** [agronholm/typeguard#348]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

3.0.2

### Python version

3.8.13

### What happened?

In typeguard 2.13.3, passing the `-O` flag to Python would disable the `@typechecked` decorator. In 3.0.2, this is no longer the case.

Is this as-designed or unintentional? I see no mention either way in the documentation.

### How can we reproduce the bug?

```bash
$ pip install -U typeguard
Requirement already satisfied: typeguard in /Users/zmccord/Desktop/projects/franklin/virtualenv/lib/python3.8/site-packages (3.0.2)
Requirement already satisfied: typing-extensions>=4.4.0 in /Users/zmccord/Desktop/projects/franklin/virtualenv/lib/python3.8/site-packages (from typeguard) (4.5.0)
Requirement already satisfied: importlib-metadata>=3.6 in /Users/zmccord/Desktop/projects/franklin/virtualenv/lib/python3.8/site-packages (from typeguard) (4.11.3)
Requirement already satisfied: zipp>=0.5 in /Users/zmccord/Desktop/projects/franklin/virtualenv/lib/python3.8/site-packages (from importlib-metadata>=3.6->typeguard) (3.8.0)

[notice] A new release of pip available: 22.3 -> 23.1.2
[notice] To update, run: pip install --upgrade pip

$ cat example.py 
from typeguard import typechecked

@typechecked
def foo(x: int) -> int:
    y: int
    y = "fred"
    return y

foo("george")

$ python -O -O example.py
Traceback (most recent call last):
  File "example.py", line 9, in <module>
    foo("george")
  File "example.py", line 4, in foo
    def foo(x: int) -> int:
  File "/Users/zmccord/Desktop/projects/franklin/virtualenv/lib/python3.8/site-packages/typeguard/_functions.py", line 113, in check_argument_types
    check_type_internal(value, expected_type, memo=memo)
  File "/Users/zmccord/Desktop/projects/franklin/virtualenv/lib/python3.8/site-packages/typeguard/_checkers.py", line 680, in check_type_internal
    raise TypeCheckError(f"is not an instance of {qualified_name(origin_type)}")
typeguard.TypeCheckError: argument "x" (str) is not an instance of int

$ python --version
Python 3.8.13

$ pip install -U 'typeguard<3.0.0'
Collecting typeguard<3.0.0
  Using cached typeguard-2.13.3-py3-none-any.whl (17 kB)
Installing collected packages: typeguard
  Attempting uninstall: typeguard
    Found existing installation: typeguard 3.0.2
    Uninstalling typeguard-3.0.2:
      Successfully uninstalled typeguard-3.0.2
Successfully installed typeguard-2.13.3

[notice] A new release of pip available: 22.3 -> 23.1.2
[notice] To update, run: pip install --upgrade pip

$ python -O -O example.py

$ 
```

**Comment by agronholm** [comment]
A lot changed between 2.x and 3.x. Typeguard does AST transformations now, so it needs its own optimization specifier. I'm sorry that I didn't write anything about the -O specifier; that point was lost in the chaos of so many changes. I hope this isn't a big problem.

**Comment by zackmccord** [comment]
I thought it might be a design decision. What is the intended way to disable @typechecked in production?

**Comment by agronholm** [comment]
The intended way to use typeguard is through the import hook. As the import hook is enabled explicitly, all you would have to do is...not enable it in production.

**Comment by agronholm** [comment]
Does that answer your question?

**Comment by zackmccord** [comment]
Hmm, I'm not sure what to do now. Here's the situation: I had added some `@typechecked` decorators to existing code. I decorated only certain functions with `@typechecked`, while expanding the type-strictness of the codebase. At the time, this didn't have a performance penalty in production. The new behavior with 3.0.2, however, slowed and broke our build.

I can try using the import hook and removing all uses of `@typechecked`. But if I use the import hook, then I'm enforcing types on all of *everyone's* code. This may not be a popular move in the organization, so I'd rather remove typeguard altogether. 

If there's no longer a good way to disable `@typechecked` in production, perhaps it should be explicitly deprecated. At least, the obvious use case for it is no longer advisable.

Alternatively, would you be interested in entertaining a PR that restores the old behavior?

**Comment by agronholm** [comment]
You do know that you can control which modules are instrumented by typeguard?

You could also do something like this:
```python
if __debug__:
    from typeguard import type_checked
else:
        from typing import TypeVar
        _T = TypeVar("_T")

        def typechecked(target: _T, **kwargs) -> _T:
            return target if target else typechecked
```
This would effectively restore the old behavior. I modeled this after a snippet in the user guide.

**Comment by agronholm** [comment]
v4.0.0rc5 is out now. If nothing else surfaces within a week, I'll brand this version the final release.
