### ISSUE TITLE
typing.Collection not checked on Python 3.7

### ISSUE THREAD

**Issue by JoseKilo** [agronholm/typeguard#35]
Using this code

```python
import typing

from typeguard import typechecked


@typechecked
def foo(collection: typing.Collection) -> None:
    pass


if __name__ == '__main__':
    foo(True)
```

On python3.6 I get the following error, as expected:

```
TypeError: type of argument "collection" must be collections.abc.Collection; got bool instead
```

But, on Python3.7, nothing happens.

I think what changed was `inspect.isclass(typing.Collection)` which returns `True` on python3.6 and `False` on python3.7, and it skips this check https://github.com/agronholm/typeguard/blob/master/typeguard.py#L382 .

**Comment by agronholm** [comment]
I guess the test suite needs one more test case for this.
