### ISSUE TITLE
Documentation not showing because import_hook

### ISSUE THREAD

**Issue by Danguilhen** [agronholm/typeguard#359]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

4.0.0

### Python version

3.11.3

### What happened?

First, thank you for this amazing package !

This issue is not new (on typeguard 3.0.2 the issue is also there).

If you try the setup I explained just below, the docstring displayed is :

> Help on function foo in module src.code:

But without using the install_import_hook, the docstring displays as it should be :

> Help on function foo in module src.code:
> 
> foo(bar: int = 42)
>     This docstring won't show up:(
>     
>     Args:
>         bar: The answer to life universe and everything.

The import hook shouldn't make the docstring disappear, the consequence is that the documentation is almost empty after building it with tools like Sphinx 😢 

Thank you in advance for considering my issue.

### How can we reproduce the bug?

Reproducing the issue is very easy :

Reproduce this file structure :

> 
> src
> ---__init__.py
> ---code.py
> notebook.ipynb

In the code.py :
```
def foo(bar: int = 42):
    """This docstring won't show up:(

    Args:
        bar: The answer to life universe and everything.
    """
    print(bar)
```

In the __init__.py :
```
from typeguard import install_import_hook

install_import_hook(__name__)
```

Finally in a cell of the notebook try:
```
from src.code import foo

print(help(foo))
```

**Comment by agronholm** [comment]
Hm, I'm not removing the docstrings on purpose. Perhaps that has something to do with optimization settings.

**Comment by agronholm** [comment]
Now that I looked into this, it looks like this is because the generated code is inserted _before_ the docstring. I need to modify the transformer to only insert any new code after the docstring.
