### ISSUE TITLE
@typechecked ignores parameters with default arg

### ISSUE THREAD

**Issue by zopyx** [agronholm/typeguard#36]
```

from typeguard import typechecked
import typing


class X:
    pass


@typechecked
def foo(a: typing.Dict[X, int]={}):
    pass


foo(a={X():2})
foo(a={2:2})
```

This code is supposed to throw an exception for the second `foo()` call. But no error is being raised.
If you removed the default paramter `{}` then the check raises an exception.

Bug or feature?

**Comment by agronholm** [comment]
Rather a consequence of how default values are handled. Since according to the spec the default value is not required to match the annotated type (e.g. `x: int = None`), Typeguard constructs an union of the default value's type and the annonated type. And guess what? The type in this case is an unparametrized `dict`, which is why no error is raised.

**Comment by agronholm** [comment]
I went and re-read the spec, and it turns out it has been changed to recommend against this. Now I'm wondering if I should remove the code that combines the types.

**Comment by zopyx** [comment]
Well, the expected behavior (without reading or know the exact specs) is that improper arguments should be checked in dependent of the existence of default args or not. I consider the current behavior as unexpected and unnatural.

**Comment by zopyx** [comment]
Expected behavior would be an error - either because of the improper default argument type or the improper parameter or both

**Comment by agronholm** [comment]
Hm, looks like at least mypy makes an exception for allowing `None` as the default value even if the annotated type does not include it.

**Comment by agronholm** [comment]
But it does give a proper error for the sample I just posted.

**Comment by agronholm** [comment]
This was the same issue as #17.
