### ISSUE TITLE
Releasing a new version?

### ISSUE THREAD

**Issue by dahlia** [agronholm/typeguard#37]
The latest released version on PyPI (2.2.0) does not work well with Python 3.7.  There seem several unreleased patch commits to be compatible with Python 3.7.  Could you release a new version including these patches?

**Comment by agronholm** [comment]
I would've, but I discovered more cases where type checks are passed when they shouldn't be on 3.7 (at least). I intended to make a new release when I've fixed those.

**Comment by Stewori** [comment]
Python 3.7 really broke a lot of stuff with typing. I'm also having a hard time with that :(

**Comment by agronholm** [comment]
I've release v2.2.1 now.
