### ISSUE TITLE
check_type should have a return type of the type it is checking

### ISSUE THREAD

**Issue by cammil** [agronholm/typeguard#370]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

Currently check_type returns Any. However, I think it should return the type that it checks.

### Use case

If check_type returns the type that it checks, then uses of the return type of the check_type function call can also be type checked, which I assume would be desirable in all cases.

**Comment by agronholm** [comment]
Yeah, this did occur to me, but I don't remember why I didn't go through with the change. I'll look into including this in the next release.

**Comment by agronholm** [comment]
So I refreshed my memory about this. As you can see [here](https://github.com/agronholm/typeguard/blob/master/src/typeguard/_functions.py#L27-L36), typeguard already does this. If this isn't good enough, let me know exactly how you would change the type annotations.

**Comment by agronholm** [comment]
I'm going to close this issue, but if you can think of a way to improve the annotations, let me know.
