### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [agronholm/typeguard#374]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

Is it possible next time on release new version make the github release to have entry on htthttps://github.com/agronholm/typeguard/releases entry? 🤔

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

### Use case

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

**Comment by agronholm** [comment]
I'm working on a GitHub action that extracts the changelog. I can then use that to automate the creation of GitHub releases with proper changelogs attached.

**Comment by kloczek** [comment]
Thank you 👍 😄

**Comment by kloczek** [comment]
Thank you very much 👍 😄
