### ISSUE TITLE
Fix handling of non-total TypedDicts

### ISSUE THREAD

**Issue by skeggse** [agronholm/typeguard#376]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

4.1.0

### Python version

3.9.16

### What happened?

`typeguard` incorrectly reports `typeguard.TypeCheckError: dict has unexpected extra key(s)` on a `TypedDict` where `total=False`.

```py
from typing_extensions import Required, TypedDict
from typeguard import check_type

class Example(TypedDict, total=False):
    field0: Required[str]

# Should not produce an error, but does.
check_type(Example(field0="what", field1="not-defined"), Example)
```

### How can we reproduce the bug?

`python test.py` (where `test.py` is the file above)

```
Traceback (most recent call last):
  File "/tmp/test.py", line 8, in <module>
    check_type(Example(field0="what", field1="not-defined"), Example)
  File "/usr/local/lib/python3.9/site-packages/typeguard/_functions.py", line 108, in check_type
    check_type_internal(value, expected_type, memo)
  File "/usr/local/lib/python3.9/site-packages/typeguard/_checkers.py", line 774, in check_type_internal
    checker(value, origin_type, args, memo)
  File "/usr/local/lib/python3.9/site-packages/typeguard/_checkers.py", line 258, in check_typed_dict
    raise TypeCheckError(f"has unexpected extra key(s): {keys_formatted}")
typeguard.TypeCheckError: dict has unexpected extra key(s): "field1"
```

**Comment by agronholm** [comment]
This is not what the `total` parameter is for. Quote from the standard library documentation (emphasis mine):

> It is also possible to mark all keys as **non-required by default** by specifying a totality of False:

So `total=False` is to make all keys optional by default, not for allowing arbitrary undeclared keys.

Mypy also gives an error for your snippet:
```
example.py:8: error: Extra key "field1" for TypedDict "Example"  [typeddict-unknown-key]
    check_type(Example(field0="what", field1="not-defined"), Example)
```
