### ISSUE TITLE
Tuples containing Any check for length 1

### ISSUE THREAD

**Issue by thomas-tran-de** [agronholm/typeguard#383]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

4.1.2

### Python version

3.11

### What happened?

I type checked a list of tuples using `list[tuple[Any]]` and the following error was raised: `item 0 of list has wrong number of elements (expected 1, got 3 instead)`

### How can we reproduce the bug?

This bug was introduced with version 4.1.2. Prior versions work as expected.

With the new handling of Any, typeguard infers an expected length for the tuple. The easiest way to reproduce the bug is `check_type((1, 2), tuple[Any])` raising `TypeCheckError: tuple has wrong number of elements (expected 1, got 2 instead)`.

**Comment by agronholm** [comment]
The error is correct. For a 2-element tuple, you would have to specify `tuple[Any, Any]`, or for a variatic-length tuple, `tuple[Any, ...]`.

**Comment by thomas-tran-de** [comment]
Yes, I just realized by testing my own minimal example with the old version. In this case, this was actually a bug with decorators in previous versions and you just fixed it. The following snippet worked in 4.1.1 but now correctly raises an error:

```
@typechecked
def list_containing_any() -> tuple[Any]:
    return (1, 1)

list_containing_any()
```

Sorry for creating confusion and thanks for the super fast reply!
