### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [agronholm/typeguard#390]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

Is it possible next time on release new version make the github release to have entry on https://github.com/agronholm/typeguard/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/

### Use case

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

**Comment by vthemelis** [comment]
Duplicate of https://github.com/agronholm/typeguard/issues/374 ?

**Comment by kloczek** [comment]
Yes .. sorry.
My fault ..
