### ISSUE TITLE
Q: How to avoid double type-checking when calling super()?

### ISSUE THREAD

**Issue by strohel** [agronholm/typeguard#40]
This is mainly a request for comments rather than an issue report.

We have code like this:
```python
AuxFileDict = Dict[str, bytes]
MaskedBandWithMetaDict = Dict[str, MaskedBandWithMeta]

class A:

    @typechecked
    def __init__(self, band_map: MaskedBandWithMetaDict,
                 aux_files: AuxFileDict, extent: dict):
        ...

class B(A):

    @typechecked
    def __init__(self, band_map: MaskedBandWithMetaDict,
                 aux_files: AuxFileDict, extent: dict,
                 bandless_metadata: BandlessSceneMetadata):
        super().__init__(band_map, aux_files, extent)
        ...
```

If I understand this correctly, type-checks on `band_map`, `aux_files`, `extent` are executed twice if one does `b = B(band_map, aux_files, extent, bandless_metadata)` - once on `B.__init__()` and once on `A.__init__()`

Is there some reasonable way to avoid this? I can drop type annotations on the "shared" parameters of `B.__init__()`, but then I loose documentation and IDE goodies. Or perhaps the performance overhead would not be that bad in this case? (the checked dicts have just a couple of elements)

CC @Indy2222, @mathewcohle, @asgeirrr.

**Comment by agronholm** [comment]
Why are you concerned about the (small) overhead in development anyway? In production this should be non-issue assuming you're running Python in optimized mode like the docs suggest.

**Comment by strohel** [comment]
> In production this should be non-issue assuming you're running Python in optimized mode like the docs suggest.

I see, then I guess we're using the library in a way it was not intended. It is desired that the type checks are enabled in production, too.

**Comment by agronholm** [comment]
If you're not already using mypy, you should start. Static type checks are free. But run time type checks have overhead you do not want in production, at least if you care about performance. The cases caught by run time type checking but not static type checking are few, and mostly come from code that reads data from external sources.

**Comment by agronholm** [comment]
I'm closing this issue because there is no way to avoid double checking.
