### ISSUE TITLE
Wrapped `typechecked` does not propagate configuration

### ISSUE THREAD

**Issue by calebho** [agronholm/typeguard#405]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

4.1.5

### Python version

3.10

### What happened?

# repro
`python main.py` (see below for source)

## expected result
The script should throw

## actual result
The script does not throw

### How can we reproduce the bug?

```python
# main.py
import typeguard
from typeguard import CollectionCheckStrategy

def typechecked(f):
    return typeguard.typechecked(collection_check_strategy=CollectionCheckStrategy.ALL_ITEMS)(f)

@typechecked
def foo(xs: list[int]) -> None:
    pass

foo([1, "abc"])
```

**Comment by agronholm** [comment]
Is there a reason why you want to do this in a wrapper rather than directly, or via global configuration?

**Comment by agronholm** [comment]
Closing due to lack of response.

**Comment by jermenkoo** [comment]
@agronholm How would one configure this globally? For context, we're trying to upgrade typeguard across our company - we were relying heavily on the previous behavior. To achieve it, it seems the simplest to patch the typeguard's code as caleb was trying rather than to configure this

**Comment by agronholm** [comment]
The trivial solution is to make a derivative decorator, for example using `functools.partial`:
```py
from functools import partial
from typeguard import CollectionCheckStrategy, typechecked

my_typechecked = partial(typechecked, collection_check_strategy=CollectionCheckStrategy.ALL_ITEMS)
```
In v5.0 I will likely restore the old behavior, but I cannot do that in the 4.x series, as it's arguable a backwards incompatible change.
