### ISSUE TITLE
typing.* types do not have __name__ and they error when generating messages.

### ISSUE THREAD

**Issue by dalejung** [agronholm/typeguard#41]
```
        T = TypeVar('T', int, Collection)
        def foo(a: T, b: T):
            assert check_argument_types()

        with pytest.raises(TypeError):
            foo('aa', 'bb')
```

Shouldn't fail but does since `Collection.__name__` does not exist.

**Comment by agronholm** [comment]
Looks like yet another Python 3.7 issue. The `Collection` class, and its parametrized versions certainly DID have the `__name__` attribute in previous releases (which I just verified).

**Comment by agronholm** [comment]
Still, odd that the existing test suite didn't catch it.

**Comment by dalejung** [comment]
Yeah I figured. Even odder that it was even changed.
