### ISSUE TITLE
cannot add a checker_lookup_function that operates on bytes

### ISSUE THREAD

**Issue by Wizzerinus** [agronholm/typeguard#421]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

4.1.5

### Python version

3.11.6

### What happened?

See in the section below. I cannot really describe this bug efficiently aside from the title and that, apologies.

### How can we reproduce the bug?

```py
from typeguard import check_type, checker_lookup_functions


def validate_print(origin: type, params: tuple, annotation: tuple):
    print(f"validate_print: {origin=} {params=} {annotation=}")
    return None


checker_lookup_functions.append(validate_print)

check_type(100, int)    # prints the thing
check_type(b"", bytes)  # does not print the thing
```

**Comment by agronholm** [comment]
As the `bytes` type can be checked directly, there is no need for this. The `checker_lookup_functions` hook collection is not intended for custom validation messages.

**Comment by agronholm** [comment]
I should've added that the hook is intended for special types that are not checkable via a simple `isinstance()`.
