### ISSUE TITLE
Complete Check for Heterogeneous Iterable

### ISSUE THREAD

**Issue by subbyte** [agronholm/typeguard#422]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

4.1.5

### Python version

3.12.0

### What happened?

Python allows heterogeneous types in Iterables, e.g., List or Mapping. When it is defined as a homogeneous type item, should it be checked all through?

### How can we reproduce the bug?

```
# it is right to pass
check_type([1,2,3], List[int])

# it passes! but should not
check_type([1,2,"asdf"], List[int])

# it fails as expected
check_type(["e",2,3], List[int])

# same for Dict/Mapping
# this passes, right
check_type({"a": "aaa"}, Mapping[str, str])

# this should not pass, but it did
check_type({"a": "aaa", "b": 5}, Mapping[str, str])
```

**Comment by subbyte** [comment]
Thank you for the information @agronholm ! Sorry I didn't know the config.

**Comment by agronholm** [comment]
You are not the first one to hit this. Just tell me where I should document this. Nobody else has answered that question.

**Comment by agronholm** [comment]
There are only two maintained PEP 484 based run-time type checkers around: this library and Beartype. Both checkers check only the first item by default, as it quickly turns into a performance drag to check every single item, and most of the time the collections tend to be homogenous. I changed the default some time ago to match Beartype's, but I have been wondering if that was the right choice. Three people within the last two weeks have reported this as a bug.

**Comment by subbyte** [comment]
I can imagine performance could be an issue for checking all.

From pure syntax point of view, Python is homogenous for collections, so a user may define the type as `List[int | str | bool]`. To me, the checker should report an error if a `dict` is in the list. If a user define the list as `List[int]`, he really mean this is a homogeneous list.
