### ISSUE TITLE
TypeVar constraints only work for concrete types and not something like typing.Collection

### ISSUE THREAD

**Issue by dalejung** [agronholm/typeguard#43]
```
    @pytest.mark.xfail(reason="TypeVar uses `in` for constraint check")
    def test_typevar_constraints_typing_type(self):
        T = TypeVar('T', int, Collection)

        def foo(a: T, b: T):
            assert check_argument_types()

        foo([1, 2], 'bb')
```

Ran across it when looking into #41. Let me know if you want me to PR that xfail test

**Comment by agronholm** [comment]
What would you change here?

**Comment by agronholm** [comment]
That snippet won't even pass mypy's check. PEP 484 says:
> TypeVar supports constraining parametric types to a fixed set of possible types (note: those types cannot be parametrized by type variables).

As such, I believe this is not a valid concern and I'm closing the issue. Comment if you feel this is wrong.
