### ISSUE TITLE
"TypedDict does not support instance and class checks": interaction between `typing_extension`, `typeguard_ignore`, `attrs`

### ISSUE THREAD

**Issue by ryan-williams** [agronholm/typeguard#443]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

4.1.5

### Python version

3.11.8

### What happened?

See [test_typeddict.py](https://github.com/ryan-williams/typeguard-issues/blob/main/src/test_typeddict.py):

- ❌ `test_typeddict` below fails, as written, with error `TypeError: TypedDict does not support instance and class checks`.
- For some reason, it passes if either:
  - ✅ `typing.TypedDict` is used (instead of `typing_extensions.TypedDict`)
  - ✅ `typeguard_ignore` is imported directly: `from typeguard import typeguard_ignore`

```python
from typing import Any

import attrs
from typing_extensions import TypedDict
# from typing import TypedDict  # ✅ uncommenting this fixes ``test_typeddict`` below

import typeguard

# ✅ uncommenting this also fixes ``test_typeddict`` below (even though it's not used!)
# from typeguard import typeguard_ignore
typeguard_ignore = typeguard.typeguard_ignore


class Spec(TypedDict):
    num: int


@typeguard_ignore
def converter(arg: dict[str, Spec]) -> dict[str, Any]:
    return {}


@attrs.define()
class Class:
    field: dict[str, Any] = attrs.field(factory=dict, converter=converter)


# ❌ As written, this fails with `TypeError: TypedDict does not support instance and class checks`
# Uncommenting either of the "✅" lines above makes it work though 😵‍💫
def test_typeddict():
    Class(field={'aaa': { 'num': 111 }})
```

### How can we reproduce the bug?

[ryan-williams/typeguard-issues](https://github.com/ryan-williams/typeguard-issues) has a working repro; [here's the error in Github Actions](https://github.com/ryan-williams/typeguard-issues/actions/runs/8367660052/job/22910449378#step:6:121).

**Comment by agronholm** [comment]
This appears to be caused by `typing.is_typeddict()` not recognizing `typing_extensions.TypedDict`. I'll follow up with a fix.

**Comment by ryan-williams** [comment]
ty!

FWIW, in my actual codebase, [I worked around this](https://github.com/single-cell-data/TileDB-SOMA/pull/1960/files#r1534159145) by moving from `typing_extensions.TypedDict` to `typing.TypedDict`, which is possible in Python ≥3.8.

Whatever's happening here seems pretty niche, but appreciate your looking into it!

**Comment by agronholm** [comment]
Hm, I'm having trouble reproducing the problem on Python 3.11 and latest typing_extensions. Just to be sure, could you convert that into a standalone script that repros the issue?

**Comment by ryan-williams** [comment]
It should be standalone [here](https://github.com/ryan-williams/typeguard-issues/blob/main/src/test_typeddict.py) in [my repro repo](https://github.com/ryan-williams/typeguard-issues).

[Here's the failure](https://github.com/ryan-williams/typeguard-issues/actions/runs/8367660052/job/22910449378#step:6:121) in a simple Github Action. [Just above](https://github.com/ryan-williams/typeguard-issues/actions/runs/8367660052/job/22910449378#step:5:12) you can see `pip list`:

```
Package                Version Editable project location
---------------------- ------- ---------------------------------------------------
attrs                  23.2.0
iniconfig              2.0.0
packaging              24.0
pip                    24.0
pluggy                 1.4.0
pytest                 8.1.1
setuptools             65.5.0
typeguard              4.1.5
typeguard-callable-bug 0.0.0   /home/runner/work/typeguard-issues/typeguard-issues
typing_extensions      4.10.0
```

Seems to be on [latest typing_extensions](https://pypi.org/project/typing-extensions/), 4.10.0.

**Comment by ryan-williams** [comment]
[Here's](https://github.com/ryan-williams/typeguard-issues/blob/main/Dockerfile) a Dockerfile:

```Dockerfile
FROM python:3.11.8
RUN apt-get update -y && apt-get install -y git
RUN git clone https://github.com/ryan-williams/typeguard-issues
WORKDIR typeguard-issues
RUN pip install -e .
RUN pytest src/test_typeddict.py
```

**Comment by agronholm** [comment]
Thanks, I'll test it shortly.

**Comment by agronholm** [comment]
Ok, I managed to repro it without Docker or pytest. I have a fix in place, just need to write a test.
