### ISSUE TITLE
check_type(True, float) == True

### ISSUE THREAD

**Issue by juliendubost** [agronholm/typeguard#448]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

4.2.1

### Python version

3.11

### What happened?

I noticed a strange behavior of check_type i can't get to explain

`check_type(True, int)` pass : since bool is a subclass of int it can make sense, `isinstance(True, int) == True`

But, this should raise `TypeCheckError` 
`check_type(True, float)` pass whereas `isinstance(True,float) == False` 

### How can we reproduce the bug?

```
from typeguard import check_type
check_type(True, float)  # pass
```

**Comment by agronholm** [comment]
What is your expectation of the outcome of `check_type(1, float)`?

**Comment by juliendubost** [comment]
@agronholm => i would expect a `TypeCheckError` to be raised since `isinstance(1, float)` return False.

What do you think ?

**Comment by agronholm** [comment]
I don't think it should raise `TypeError` because [PEP 484](https://peps.python.org/pep-0484/#the-numeric-tower) says that `int` should pass as a `float`, and since `bool` is also an `int`, `check_type(True, float)` should also pass.

**Comment by agronholm** [comment]
And [mypy](https://mypy-play.net/?mypy=latest&python=3.12&gist=601cbadb892dc6f1dfa74456873e7999) agrees, so I'm closing this.

**Comment by juliendubost** [comment]
I see, thanks for your reply :+1:
