### ISSUE TITLE
Provide class decorator

### ISSUE THREAD

**Issue by koliyo** [agronholm/typeguard#46]
Thank you so much for this library! Really valuable to implement solid python code!

I want to request a class decorator that would add typechecking to all methods of a class. Is that feasable?

**Comment by agronholm** [comment]
So it would decorate all methods with `@typechecked`, yes? I guess I could look into it.

**Comment by koliyo** [comment]
Yes, I think it could be useful!

**Comment by Stewori** [comment]
You may want to borrow [this code](https://github.com/Stewori/pytypes/blob/master/pytypes/typechecker.py#L921) from pytypes where this feature is already implemented. However, it applies also to properties and optionally to inner classes, so some modification is required if you only want to check methods.
