### ISSUE TITLE
check_type doesn't work for the empty tuple type

### ISSUE THREAD

**Issue by lubieowoce** [agronholm/typeguard#47]
## `typeguard.check_type('x', (), typing.Tuple[()])` should succeed, but raises a TypeError instead

According to the `mypy` [docs](https://mypy.readthedocs.io/en/latest/builtin_types.html), the empty tuple `()` has type `typing.Tuple[()]`. (I couldn't find anything on this in the `typing` docs, but since Guido reviewed and merged [the commit](https://github.com/python/mypy/commit/71332d5857b36f4fa7e389bf9bf2c95776cd26f0) to `mypy's` docs ,  `Tuple[()]` seems like the official way to do it.)

On my machine, `check_type('x', (), Tuple[()])` does this:
```python
>>> from typing import Tuple
>>> from typeguard import check_type
>>> check_type('x', (), Tuple[()])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\lubieowoce\.virtualenvs\sumtype-PdEpNsgZ\lib\site-packages\typeguard.py", line 392, in check_type
    checker_func(argname, value, expected_type, memo)
  File "C:\Users\lubieowoce\.virtualenvs\sumtype-PdEpNsgZ\lib\site-packages\typeguard.py", line 256, in check_tuple
    .format(argname, len(tuple_params), len(value)))
TypeError: x has wrong number of elements (expected 1, got 0 instead)
```

**Comment by agronholm** [comment]
What is the empty tuple supposed to mean? If you wanted to represent a tuple with arbitrary contents, you could use `tuple` or `Tuple`.

**Comment by lubieowoce** [comment]
I don't want arbitrary contents, I want "no contents whatsoever" :) Let me clarify what I mean by that...

In python, tuples can be used in two ways, so `()` is slightly tricky to type. If you're using a tuple as a list – `Tuple[A, ...]` – then `()` is inded a valid value of that type for any `A`, just like `[]` for `List`s. Here, I'm interested in the more common struct-like usage, as in `Tuple[int, str, float]`.

I found `Tuple[()]` to look a bit confusing too, but if you recall that `x[a, b]` translates into `x.__getitem__( (a, b) )`, and that `x[(a, b)] == x[a, b]`**¹**, it makes more sense:

```python
(3, 'a'): Tuple[(int, str)] # = Tuple[int, str]
(5,):     Tuple[(int,)]     # = Tuple[int]
():       Tuple[()]
#          ^ () is the only value of this type
```
In this view, `Tuple[()]` means something like "a struct with no attributes" – `t: Tuple[(int, str)]` has an int and a string inside, `t: Tuple[()]` has nothing. ML-family languages, Rust, and Swift all have `Tuple[()]`**²** as the type of empty tuples, which only contains one value, `()`. Compatibility with `mypy`  is another reason to support this – as I said before, `mypy` accepts `(): Tuple[()]`.

As for practical – if a bit niche – usage**³**:
For a function `f = lambda: 5`, `Tuple[()]` is the type of "tuples whose values are valid arguments to `f`", i.e. tuples `t` with which you can do `f(*t)`.

---

**¹** Looks like there's more than one way to do it ;)
```python
>>> d = {(1,2): 'a',  (3,4): 'b'}
>>> d[1,2]
'a'
>>> d[(1,2)]
'a'
```

**²** Although, since those languages use `(int, str)` instead of `Tuple[int, str]`, the type is usually called `()` as well.
See [Haskell example](https://stackoverflow.com/a/9462310/5534735), [Rust example](https://stackoverflow.com/a/31107736/5534735), [Swift docs](https://docs.swift.org/swift-book/ReferenceManual/Types.html) (ctrl+F "the empty tuple type")

**³** In fact, this was more or less what I'm doing, though not with `typeguard`. I stumbled upon a similar issue in `Hypothesis` ([ticket](https://github.com/HypothesisWorks/hypothesis/issues/1583#event-1848723029)) – `from_type(T)`, which is used to generate arbitrary values `t: T` for testing purposes, failed for `Tuple[()]`, and I decided to check if `typeguard` supports it.
