### ISSUE TITLE
typing_extensions.Buffer requires `typing-extensions>=4.6`

### ISSUE THREAD

**Issue by ymerkli** [agronholm/typeguard#472]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

4.2.1

### Python version

3.10.12

### What happened?

typeguard uses `typing_extensions.Buffer`, which was only added to `typing_extenions>=4.6.0`.

### How can we reproduce the bug?

```
pip install typing_extensions==4.5.0
python -c "from typeguard import check_type"
```

**Comment by agronholm** [comment]
Typeguard already depends on `typing_extensions >= 4.10.0`, so I have no clue why you would report this as a bug.
