### ISSUE TITLE
Externally defined class functions, unable to typecheck accepting an argument of type of the parent class

### ISSUE THREAD

**Issue by Josh-Ring-jisc** [agronholm/typeguard#57]
This is related to this general issue: https://github.com/python/typing/issues/105

I have classes which are large and the make the situation manageable I have defined the class function in separate files and add these functions to the class on class initialisation.

I want these functions to have arguments the same type as the class of which they are a part, so I can compare two instances of the same class in multiple ways. 

According to the discussion in: https://github.com/python/typing/issues/105
this is the best practice method (for static type checking), but unfortunately this does not work for me in Python 3.7.2 with runtime checking, as provided by typeguard. It can work when the functions are all in the same file as the class, but doing this makes those files unmanageable in size.

## Inside the **external_file.py**
```python

from typing import TYPE_CHECKING
from typeguard import typechecked

if TYPE_CHECKING:
    from test_class_file import test_class

@typechecked
def large_function(self, test_class_instance : 'test_class') -> None:
    """Do some comparison on the class instances"""
    
    if test_class_instance.arg1 == self.arg1:
    	print("The values of arg1 matched")
    else:
    	print("The values of arg1 did not match")
```

## Inside the class definition file **test_class_file.py**
```python
from typeguard import typechecked
from external_file import large_function


class test_class():
    
    @typechecked
    def __init__(self, arg1 : str) -> None:
        """Init which includes externally defined large_function"""
        self.arg1 = arg1

        # Modify the class to add this externally defined function to all instances
        test_class.large_function = large_function    
        
    '''    
    # defined in the same file, this function works, if imported it fails
    # comment out the part in the init which inserts it into the class to test the below
    @typechecked
    def large_function(self, test_class_instance : 'test_class') -> None:
        """Do some comparison on the class instances"""
        
        if test_class_instance.arg1 == self.arg1:
            print("The values of arg1 matched")
        else:
            print("The values of arg1 did not match")
    '''
        
instance = test_class(arg1 = 'some_data')
instance2 = test_class(arg1 = 'some_data')

# Let's compare these class instances
instance.large_function(test_class_instance=instance2)
```

**Comment by agronholm** [comment]
I'm unclear as to what the problem is with typeguard. All you have to do is to import the module containing the class and refer to the class like `'modulename.classname'` in your type annotations.

**Comment by Josh-Ring-jisc** [comment]
Circular dependencies result if you import the class into the file containing that class' externally defined functions. This causes the import to fail.




Modifying the external file as you suggested didn't seem to help either

```python
@typechecked
def large_function(self, test_class_instance : 'test_class_file.test_class') -> None:
    """Do some comparison on the class instances"""
    
    if test_class_instance.arg1 == self.arg1:
    	print("The values of arg1 matched")
    else:
    	print("The values of arg1 did not match")
```

So I had to avoid the circular dependency of the import and this gave the predictable result:
```
Traceback (most recent call last):
  File "test_class_file.py", line 31, in <module>
    instance.large_function(test_class_instance=instance2)
  File "/home/josh/miniconda3/envs/predictor_env/lib/python3.7/site-packages/typeguard.py", line 492, in wrapper
    memo = _CallMemo(func, args=args, kwargs=kwargs)
  File "/home/josh/miniconda3/envs/predictor_env/lib/python3.7/site-packages/typeguard.py", line 45, in __init__
    hints = get_type_hints(func)
  File "/home/josh/miniconda3/envs/predictor_env/lib/python3.7/typing.py", line 1001, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/home/josh/miniconda3/envs/predictor_env/lib/python3.7/typing.py", line 260, in _eval_type
    return t._evaluate(globalns, localns)
  File "/home/josh/miniconda3/envs/predictor_env/lib/python3.7/typing.py", line 464, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'test_class_file' is not defined
```

**Comment by agronholm** [comment]
This is why you import the **module**, not the **class**! You can always import the other module, even if its definition is still in progress.

**Comment by Josh-Ring-jisc** [comment]
I just tested your assertion, it fails in all cases, because of the circular dependency, even from the module. This is because it is refering to the same class type. If it was another class it wouldn't be a problem.

**Comment by Josh-Ring-jisc** [comment]
Check here for more discussion:  [python/typing#105](https://github.com/python/typing/issues/105)

**Comment by agronholm** [comment]
Could you please provide me with an archive of the code you just tested with? I'd like to see for myself.

**Comment by Josh-Ring-jisc** [comment]
[class_externally_defined_functions.zip](https://github.com/agronholm/typeguard/files/2914446/class_externally_defined_functions.zip)

**Comment by agronholm** [comment]
Ok, it seems that the problem occurs because you're instantiating the class as a side effect of the module being imported. Is this absolutely necessary?

**Comment by Josh-Ring-jisc** [comment]
```python

if __name__ == '__main__':   
    instance = test_class(arg1 = 'some_data')
    instance2 = test_class(arg1 = 'some_data')
    
    # Let's compare these class instances
    instance.large_function(test_class_instance=instance2)
```


I have tried this too, you get a new error:

```
Traceback (most recent call last):
  File "test_class_file.py", line 32, in <module>
    instance.large_function(test_class_instance=instance2)
  File "/home/josh/miniconda3/envs/predictor_env/lib/python3.7/site-packages/typeguard.py", line 493, in wrapper
    check_argument_types(memo)
  File "/home/josh/miniconda3/envs/predictor_env/lib/python3.7/site-packages/typeguard.py", line 462, in check_argument_types
    raise TypeError(exc) from None
TypeError: type of argument "test_class_instance" must be test_class_file.test_class; got __main__.test_class instead
```

**Comment by agronholm** [comment]
This is a separate problem. It occurs because your module is now imported twice: as `test_class_file` and `__main__`. Try creating a dedicated module for your entry point where you instantiate the test classes and call the large function.

**Comment by Josh-Ring-jisc** [comment]
Apologies I had no idea that could happen. Thanks for the assistance.
