### ISSUE TITLE
Have you tested with the new typing.py yet?

### ISSUE THREAD

**Issue by gvanrossum** [agronholm/typeguard#6]
While Python 3.6 is in beta we're changing the way typing.py represents types. I can't make any promises that it'll stay stable until the 4th beta (after all PEP 484 is still provisional) but I figured I should give you a heads up that we're changing things around. You can follow the fun in our repo: https://github.com/python/typing/

**Comment by agronholm** [comment]
I will test, thanks for the heads up!

**Comment by agronholm** [comment]
```
53 failed, 12 passed in 11.73 seconds
```
Looks like I have some work to do...
