### ISSUE TITLE
Untyped decorator makes function "f" untyped

### ISSUE THREAD

**Issue by kshpytsya** [agronholm/typeguard#60]
Please add `py.typed` marker to the package, as described [here](https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages).

Without this, the following code

```py
from typeguard import typechecked

@typechecked
def f() -> None:
   pass
```

produces the following when checked with `mypy`:

```
$ mypy --python-executable venv-typeguard/bin/python --strict example.py
example.py:1: error: Cannot find module named 'typeguard'
example.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
example.py:4: error: Untyped decorator makes function "f" untyped
```

**Comment by agronholm** [comment]
Thanks for the heads up. I had no clue that PEP 561 even existed.

**Comment by kshpytsya** [comment]
To add to that, you probably need something like this, to avoid loosing type information on functions wrapped with `typechecked`:

```py
from typing import TypeVar

# ignore the "error: Missing type parameters for generic type"
Tcallable = TypeVar("T", bound="Callable")  # type: ignore

def typechecked(func: Tcallable) -> Tcallable:
   # replace by real code
   return func
```

The way your `typechecked` is annotated now causes the following:

```py
from typeguard import typechecked

@typechecked
def f() -> int:
    pass

reveal_type(f())
```

```
$ mypy --python-executable venv-typeguard/bin/python --strict example.py
example.py:17: error: Revealed type is 'Any'
```

**Comment by agronholm** [comment]
That did occur to me too. I didn't know how to debug that but you answered that question before I could ask. Thanks again!

**Comment by agronholm** [comment]
I'm really not sure how to properly type annotate the decorator. I could use some help.

**Comment by kshpytsya** [comment]
I suppose this could provide some insight:

https://github.com/python/typeshed/blob/5c94b5875209329791791e54c0599273ac6ba2c0/stdlib/2and3/contextlib.pyi#L30

https://docs.python.org/3/library/contextlib.html#contextlib.contextmanager

**Comment by agronholm** [comment]
The first link looks like it could help. I'll take a better look later.

**Comment by agronholm** [comment]
The biggest problem here is that the return type differs based on the arguments. I think this is what `@typing.overload` was meant for, but the spec states that it should not be used outside of `.pyi` files.
