### ISSUE TITLE
Thread safety on dataclass type annotations

### ISSUE THREAD

**Issue by Josh-Ring-jisc** [agronholm/typeguard#61]
**Python version:** Python 3.7.2
**Typeguard:** 2.3.1
**OS:** Ubuntu 19.04
**Arch:** 64bit

## Issue:
The following code will fail **only if** typeguard's `@typechecked` is annotated on the dataclass.

## Related issues:
this is likely related to what was fixed in V2.3.1

>**2.3.1** (2019-04-12)
>- Fixed thread safety issue with the type hints cache (PR by Kelsey Francis)

## Example code:

```
from typeguard import typechecked
import concurrent.futures
import math
from dataclasses import dataclass
from typing import Dict, Any

PRIMES = [
    112272535095293,
    112582705942171,
    112272535095293,
    115280095190773,
    115797848077099,
    1099726899285419]


## Type checking this dataclass causes the parallel region to freeze and be unable to complete
## If @typechecked is omitted then this problem will not be present
@typechecked
@dataclass
class data_class:
    a: int
    b: int = 0


@typechecked
def is_prime(args : Dict[str,Any]) -> bool:
    n = args.get('n')
    dc = args.get('dc')
    
    print(dc)
    
    if n % 2 == 0:
        return False

    sqrt_n = int(math.floor(math.sqrt(n)))
    for i in range(3, sqrt_n + 1, 2):
        if n % i == 0:
            return False
    return True


     

if __name__ == '__main__':

    with concurrent.futures.ProcessPoolExecutor() as executor:
        
        futures_tasks = []
        for number in PRIMES:
            futures_tasks.append( executor.submit(is_prime, {'n':number, 
                                                             'dc' : data_class(a=1, b=2)}
                                                 )
                                )
        
        for future, number in zip(concurrent.futures.as_completed(futures_tasks), PRIMES):
            print("The number: {}, is it prime? {}".format(number, future.result()))

**Comment by agronholm** [comment]
I will investigate, but in the meantime I have a question: why did you use `@typechecked` on a class?

**Comment by Josh-Ring-jisc** [comment]
`dataclass` is a new python 3.7 feature, where type-annotations are a first class citizen and it simplifies passing variables around, and is self documenting.

**Official docs:** https://docs.python.org/3/library/dataclasses.html
**More approachable tutorial:** https://realpython.com/python-data-classes/

**Comment by agronholm** [comment]
I know what a dataclass is. What I asked you was why you added the `@typechecked` decorator on it. Typeguard does not support variable annotations or dataclasses nor does it claim to.

**Comment by Josh-Ring-jisc** [comment]
Oh I see, I wasn't aware. Well good news then, it worked out of the box in single threaded code. Only having issues with multithreaded code.

**Comment by agronholm** [comment]
So if you remove the `@typechecked` from the class and keep it on `is_prime()`, will the code still fail with multiple threads?

**Comment by Josh-Ring-jisc** [comment]
No it will run without problems

**Comment by agronholm** [comment]
Alright, closing this as invalid then.
