### ISSUE TITLE
Forward references and recursive types can be be checked correctly without falling back to Any

### ISSUE THREAD

**Issue by pirate** [agronholm/typeguard#62]
First of all, this library is awesome, it's the best runtime type checking library we've tried out of several, thanks for all your hard work on it! It supports python 3.7 and provides an easy-to-use `check_type` function that's a great drop-in replacement for `assert isinstance`, something the other libraries we tried struggled with.

It appears `typeguard` doesn't support recursive type / forward reference type checking.  This is somewhat expected given it's not officially supported in `mypy` yet.

```python
from typing import Union, List, Dict
from typeguard import check_type

JSONType = Union[str, int, float, bool, None, List['JSONType'], Dict[str, 'JSONType']]

check_type('test', (1,2,3), JSONType)           # this fails correctly because `Tuple` is not in the `Union`
check_type('test', {'abc': (1,2,3)}, JSONType)  # but this does not throw an error, it passes even though the subtype is incorrect
```
It looks like it's evaluating `List['JSONType']` as `List[Any]` and `Dict[str, 'JSONType']]` as `Dict[str, Any]` when checking instead of using `ForwardRef._evaluate(...)` to check the actual type.

Lack of support for recursive types is a known issue with `mypy` in general, it's not yet implemented though it's been slated to be added in the future:
 - https://github.com/python/mypy/issues/731
 - https://github.com/python/typing/issues/182

**But because `typeguard` has the benefit of executing at runtime, it can actually check these correctly even when `mypy` cant provide it natively at compile-time.**
This might even be possible already at compile time, but I haven't dug through enough of the `mypy` source yet to tell.
To accomplish this at runtime, `typeguard` just has to resolve `ForwardRef` types to their actual types (e.g. `"JSONType"` -> `JSONType`), and this will allow forward reference and recursive types to be checked correctly!
```python
# this code goes somewhere inside of typeguard's runtime type checker function

import sys
import inspect
from typing import ForwardRef, Type, Any

def check_type(name: str, type_hint: Type, value: Any) -> None:
    ...

    if isinstance(type_hint, ForwardRef):
        # get caller's scope to evaluate types in
        frame = sys._getframe(1)
        caller_globals, caller_locals = frame.f_globals, frame.f_locals

        # ForwardRef provides a built-in way to evaluate to the actual type, you just
        # have to pass it the available types it can evaluate to in `globals()` `locals()`
        # e.g. in our example:
        #     type_hint = type_hint._evaluate({}, {'JSONType': JSONType})
        type_hint = type_hint._evaluate(caller_globals, caller_locals)

    ...
```
---

Unrelated minor gripe: One room for possible improvement is that the error message for variables with invalid subtypes imply the top level type `dict` is incorrect, when in fact it's a value several levels deep that has an incorrect type `tuple`:
```diff
- TypeError: type of test must be one of (str, int, float, bool, NoneType, Dict, List); got dict instead
+ TypeError: type of test must be one of (str, int, float, bool, NoneType, Dict, List); got dict containing a tuple instead
```

**Comment by pirate** [comment]
For people just trying to solve this quickly, a temporary workaround is to hardcode to the number of levels down you expect for the given object:
```python
FlatJSONType = Union[str, int, float, bool, None]
JSONTypeMaxDepth1 = Union[str, int, float, bool, None, Dict[str, FlatJSONType], List[FlatJSONType]]
JSONTypeMaxDepth2 = Union[str, int, float, bool, None, Dict[str, JSONTypeMaxDepth1], List[JSONTypeMaxDepth1]]
JSONTypeMaxDepth3 = Union[str, int, float, bool, None, Dict[str, JSONTypeMaxDepth2], List[JSONTypeMaxDepth2]]
JSONTypeMaxDepth4 = Union[str, int, float, bool, None, Dict[str, JSONTypeMaxDepth3], List[JSONTypeMaxDepth3]]
JSONTypeMaxDepth5 = Union[str, int, float, bool, None, Dict[str, JSONTypeMaxDepth4], List[JSONTypeMaxDepth4]]
JSONType = JSONTypeMaxDepth5

# this checks json objects up to 5 levels deep and throws if they are deeper, which is enough for most use cases
# replace FlatJSONType with Any if you want to allow infinite depth without checking below the 5th level

check_type('test', {'1': {'2': {'3': {"4": {"5": 1}}}}}, JSONType)         # this passes correctly
check_type('test', {'1': {'2': {'3': {"4": {"5": (1, 2)}}}}}, JSONType)    # this throws correctly due to the invalid value
check_type('test', {'1': {'2': {'3': {"4": {"5": {"6": 1}}}}}}, JSONType)  # this throws correctly due to exceeding the hardcoded depth
```

**Comment by agronholm** [comment]
You may want to track issue #65.

**Comment by agronholm** [comment]
Issue #65 is actually not a match for this one. Having now investigated this in depth, the problem only occurs with `check_type()`, never with `@typechecked`. In order to resolve the forward references, typeguard would have to get at least the global namespace in which the annotation was defined. How do you propose I do that?

**Comment by rfrowe** [comment]
I just ran into this today. In answer to your question, @agronholm, perhaps export `_CallMemo` from Typeguard so I can construct an instance myself with the necessary global/local namespace context and pass that to `check_type`? For now, I've just done this:

```python
RecType = Union[int, Tuple['RecType', ...]
foo: RecType = (1, (2, 3))
# What I want:
check_type('foo', RecType, foo)

# What I do instead:
@typechecked
def check_is_rec_type(foo: RecType):
    pass

check_is_rec_type(foo)
```

**Comment by rfrowe** [comment]
At the least, it would be nice if the `ForwardRef` failed to resolve so that, in my example,`check_type('foo', RecType, 'bar')` would fail instead of succeeding.

**Comment by rfrowe** [comment]
> Issue #65 is actually not a match for this one. Having now investigated this in depth, **the problem only occurs with `check_type()`, never with `@typechecked`**. In order to resolve the forward references, typeguard would have to get at least the global namespace in which the annotation was defined. How do you propose I do that?

@agronholm I believe that the bolded portion of your reply is false. See #129
