### ISSUE TITLE
Literal types not supported

### ISSUE THREAD

**Issue by pirate** [agronholm/typeguard#64]
It looks like `Literal` types currently aren't checked by `typeguard`.

https://mypy.readthedocs.io/en/latest/literal_types.html

```python
from typeguard import check_type
from typing_extensions import Literal

check_type('test', 123, Literal[1234])  # passes even though incorrect
```

I don't think this would be too hard to implement, maybe something like this:

```python
if isinstance(expected_type, Literal):
    expected_value = expected_type.__args__[0]
    assert value == expected_value
```

**Comment by agronholm** [comment]
Yeah, `typing.Literal` is a very recent addition to the standard library.

**Comment by pirate** [comment]
Bleeding edge for sure, but not too tricky internally it seems.  Want me to draft up a PR?  I can't promise I'll be able to do it quickly, but I am definitely motivated to get this added at some point. Also happy to leave it to you if you have opinions on how to implement this.

**Comment by agronholm** [comment]
I have a changeset for this in the works now.

**Comment by agronholm** [comment]
Bleh, the Literal from `typing_extensions` requires a totally different codepath than the stdlib version.

**Comment by agronholm** [comment]
Actually I cannot find any way to detect `typing_extensions.Literal`. I have never seen an API so hostile to run-time type checkers. I will not include this in my commit. If you know of a way, let me know.

**Comment by pirate** [comment]
That was fast, thank you!
