### ISSUE TITLE
Make error messages more informative when a Union check fails

### ISSUE THREAD

**Issue by agronholm** [agronholm/typeguard#65]
When an argument does not match a `Union`, the error message does not provide any hints as to why it specifically did not match each of the elements. This ought to be fixed to make troubleshooting easier.

**Comment by agronholm** [comment]
I don't have the energy to cram this into the next release, as it requires significant effort.

**Comment by jsh9** [comment]
I took a look at your source code (here: https://github.com/agronholm/typeguard/blob/1faec9d930c2b0f9bde841525703a35e8de834c1/typeguard/__init__.py#L408), and I think a quick fix may be to change Line 408 into:
```python
typelist = ', '.join(str(t) for t in union_params)
```

Then `typelist` looks like this:
```python
typing.Dict[int, float], typing.List[float, int]
```

(I admit that having `typing.` showing may not be the most elegant way. )

However, there may be another way: the `__args__` attribute of `t` is a tuple that looks like this: `(<class 'float'>, <class 'int'>)`. So maybe we can extract `"float"` and `"int"` and construct a nicer looking `typelist` string?

I can submit a pull request if you think my solutions are feasible.

**Comment by agronholm** [comment]
I don't understand at all what you're getting at. Could you elaborate a bit? Also, this is a problem that can't really be solved properly with a change of a single line. If it was, I would've done it already.

**Comment by jsh9** [comment]
Sorry I didn't provide enough context.

Below is the script that I was using:
```python
import typeguard
from typing import Union, Dict

b = {'a': 2, 'b': 2.3}

typeguard.check_type('b', b, Union[Dict[float, str], Dict[int, float]])
```

And the error message is:
`TypeError: type of b must be one of (Dict, Dict); got dict instead`

==============================
My solution can potentially solve the ambiguity in this part of the error message: "must be one of (Dict, Dict)", but probably not the second part.

But I noticed that the error message from this line https://github.com/agronholm/typeguard/blob/1faec9d930c2b0f9bde841525703a35e8de834c1/typeguard/__init__.py#L403 is quite informative. So maybe you can collect them in each iteration, and then show them at this line? https://github.com/agronholm/typeguard/blob/1faec9d930c2b0f9bde841525703a35e8de834c1/typeguard/__init__.py#L409

Then the error message would look like this:
```
type of keys of b must be either float or int; got str instead
type of keys of b must be int; got str instead
type of b must be one of (typing.Dict[int, float], typing.List[float, int]), ...
```

(Of course this error message is not perfect, but this may be a good starting point.)

**Comment by agronholm** [comment]
It becomes a problem when you have nested unions and you want to display a sensible error message telling the user what the problem was with each nested union. What you're suggesting won't quite cut it – a more elaborate solution is needed.

**Comment by jsh9** [comment]
Sure. Then I'll wait for your solutions then. It is indeed not very trivial. Thanks.

**Comment by luckydonald** [comment]
So in other words, `TypeError: type of buttons must be one of (List, Generator); got list instead`
is not a bug in the type check (as `list` is the same as `List`) but instead one element in that list doesn't work out?

So the error message is the bug while the comparison works fine?

**Comment by agronholm** [comment]
> So the the bug is the error message, while the comparison works fine?

That's right.

**Comment by KyleKing** [comment]
I came across an error today (`TypeError: type of argument "bar" must be one of (Tuple, NoneType); got tuple instead`) where Typeguard worked correctly (the tuple was out of order). The error confused me initially and I thought it might be related to #153 until I saw this ticket and #51

In case this helps, here is an example:

```py
from typing import Optional, Tuple

from typeguard import typechecked


@typechecked
def foo(bar: Optional[Tuple[int, str]] = None) -> str:
    if bar is None:
        bar = (0, 'def')

    return bar[1]


if __name__ == '__main__':
    assert foo(bar=(1, 'one')) == 'one'

    foo(bar=('one', 1))
    # Traceback (most recent call last):
    #   File "tuple_test.py", line 16, in <module>
    #     foo(bar=('one', 1))  # Raises Unclear TypeError
    #   File ".venv\lib\site-packages\typeguard\__init__.py", line
    # 911, in wrapper
    #     check_argument_types(memo)
    #   File ".venv\lib\site-packages\typeguard\__init__.py", line
    # 757, in check_argument_types
    #     raise TypeError(*exc.args) from None
    # TypeError: type of argument "bar" must be one of (Tuple, NoneType); got tuple instead
```

**Comment by agronholm** [comment]
I am actively working on this now. It required extensive architectural changes and thus will be part of the next major release only.
