### ISSUE TITLE
`TypeChecker` reports return type mismatch when exception is raised

### ISSUE THREAD

**Issue by niosHD** [agronholm/typeguard#68]
I currently use typeguard's `TypeChecker` to non-intrusively test one of my python projects and it works quite nicely in general. However, I noticed that exceptions seem to trip up the checking. I reduced the problem to the following example:

~~~python3
from typeguard import TypeChecker


def foo(arg: int) -> int:
    if arg > 10:
        raise Exception()
    return 42


checker = TypeChecker(__name__)
checker.start()

foo(5)
foo(12)
~~~
Executing this snippet gives me, besides the exception, the following return type mismatch warning: `TypeWarning: [MainThread] return from __main__.foo() at tgdemo.py:6: type of the return value must be int; got NoneType instead`

Is this a bug in the `TypeChecker`? The `typechecked` decorator at least does not complain about mismatching return values when an exception is raised.

**Comment by agronholm** [comment]
I think it's a bug. This mode of operation is not used nearly as much as the other two which may explain why nobody noticed before.

**Comment by niosHD** [comment]
Ok, thank you for confirming.

Based on a quick peek into the code and the documentation on [sys.setprofile](https://docs.python.org/3/library/sys.html#sys.setprofile) this specific warning seems to be easy to suppress. According to the documentation, in the event of an exception, the return event is triggered with `None` as `arg`. Therefore, we should simply skip the return type check if `arg` is None. However, this has also the implication that some real warnings get suppressed.

I sent #69 to show the change I have in mind. Maybe you have an idea how this can be addressed without the negative side effect.

**Comment by agronholm** [comment]
I tried looking at `sys.exc_info()` from the profiler hook but it's `(None, None, None)` even when an exception is being raised, so there is no way to tell the difference.
