### ISSUE TITLE
Support for NamedTuple

### ISSUE THREAD

**Issue by ruxi** [agronholm/typeguard#7]
Hi. I was just wondering if NamedTuples are supported? Or if there is plans to support NamedTuples in the future. I would like to do this:

    Employee = typing.NamedTuple("Employee", [("name", str), ("id", int)] )

    @typeguard.typechecked
    def foo(bar:Employee):
        pass  

    foo(Employee('bob', 1))

Currently, running the above example results in an AttributeError

Here is the output:
    https://gist.github.com/ruxi/17d934768aa9404ca99fac2cb1d2a1e2

**Comment by agronholm** [comment]
I'll add this to the list of things I need to fix in the next release.
