### ISSUE TITLE
Type[Any] causes false warning

### ISSUE THREAD

**Issue by jolaf** [agronholm/typeguard#71]
When `Type[Any]` is used as an argument type, passing a valid class object causes the following false warning: `Any cannot be used with issubclass()`.

```python3
from typing import Any, Type

from typeguard import TypeChecker

def f(c: Type[Any]) -> None:
    print(c.__name__)

with TypeChecker('__main__'):
    f(str)
```

```python3
$ mypy Test.py
$ python3 Test.py
/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py:694: TypeWarning: [MainThread] call to __main__.f() from Test.py:9: Any cannot be used with issubclass().
  warn(TypeWarning(memo, event, frame, exc))
str
```

**Comment by agronholm** [comment]
I have never seen this annotation in the wild. Why not simply use `Type` or `type` like I do?
But sure, this should not produce an internal error.

**Comment by jolaf** [comment]
In strict mode `mypy` prohibits using parameterized generic types without parameters.
It's like "Are you really sure your `List` can contain anything at all? If you do, please specify it explicitly".

**Comment by jolaf** [comment]
Thanks!
