### ISSUE TITLE
Listing modules to check manually is inconvenient

### ISSUE THREAD

**Issue by jolaf** [agronholm/typeguard#73]
For now to specify which code has to be checked I have to specify a list of modules as a parameter to `TypeChecker()` constructor.

If the code base to be checked is large, that list may grow up to hundreds of elements.

Providing such a list becomes extra work that not everybody wants to do.

Personally I would prefer some or all of the following improvements:

- Providing a special option meaning "check everything" and maybe "check everything except the standart library".

- Using some microlanguage in the modules list, like `MyModule*` meaning all modules whose names start with `MyModule`.

- Allowing to use regexps instead or together with strings in the module list, which easily allows checking everything or specifying the modules needed in a more concise way.

- Allowing to use a single regexp instead of list of modules.

- Allowing to use a callback instead of list of modules, that would take a module name as a parameter and return a `True` value if that module is to be checked.

- To reduce performance load on iterating the list, calling callbacks or resolving regexps, it may be worth adding internal cache of modules to be checked (and not to be checked), like `Dict[str, bool]`.

**Comment by agronholm** [comment]
I think you're misunderstanding how it works. All you have to do is list the top level package(s) to check, like in your second suggestion. See the code [here](https://github.com/agronholm/typeguard/blob/master/typeguard/__init__.py#L647-L648).

**Comment by jolaf** [comment]
Yes, I saw that code, but how, for example, I check the code in standard library? Or what about codebases that are not packaged, but just consist of modules?

**Comment by agronholm** [comment]
If you have complex requirements, then why not just override `TypeChecker.should_check_type()`?

**Comment by jolaf** [comment]
Yeah, that's what I'll do, thanks, I just didn't think about it as something complex.

I thought that "checking everything" is the simplest thing ever (in fact, I would expect it to be a default), and was amazed that the filtering mechanism (that I don't need at all) gets in the way in such a complex and counterintuitive manner. Well, inheritance solves it, of course.

**Comment by agronholm** [comment]
The intent with the package list was to ensure that the type checker only runs for your own packages. You would not normally try to check if third party libraries works correctly, and the standard library doesn't even have annotations so there's no point in checking those.

**Comment by jolaf** [comment]
That intent is pretty clear, yeah.

Any plans on supporting python/typeshed and other stub repositories? :)

**Comment by agronholm** [comment]
> Any plans on supporting `python/typeshed` and other stub repositories? :)

None. That would add a whole new dimension of complexity to the library.

**Comment by agronholm** [comment]
I think the pytypes project has that feature though.

**Comment by agronholm** [comment]
I'm going to consider this matter settled and close the issue.

**Comment by jolaf** [comment]
Just in case somebody looks for a simple solution to this:

```python3
from inspect import isasyncgenfunction
from typing import Any, Callable, Sequence, Union

from typeguard import TypeChecker

class AllTypeChecker(TypeChecker):
    """Extends `TypeChecker` to check all accessible code without listing individual packages."""
    def __init__(self, packages: Union[str, Sequence[str], None] = None, **kwargs: Any) -> None:
        TypeChecker.__init__(self, packages or (), **kwargs)

    def should_check_type(self, func: Callable[..., Any]) -> bool:
        return bool(func.__annotations__) and not isasyncgenfunction(func)
```
