### ISSUE TITLE
capturewarnings() hides warnings sometimes

### ISSUE THREAD

**Issue by jolaf** [agronholm/typeguard#82]
The following code:
```python3
from logging import warning, captureWarnings

from typeguard import TypeChecker

captureWarnings(True)

warning('Test')

def f(x: str) -> None:
    pass

with TypeChecker(('__main__',)):
    f(5)
```
produces the following output:
```python3
$ python3 Test.py 
WARNING:root:Test
WARNING:py.warnings:/usr/local/lib/python3.6/dist-packages/typeguard/__init__.py:911: TypeWarning: [MainThread] call to __main__.f() from Test.py:13: type of argument "x" must be str; got int instead
  warn(TypeWarning(memo, event, frame, exc))
```
And it is exactly as expected.

**HOWEVER** if `warning('Test')` line is commented out, **no warning gets issued** at all, which is incorrect.

If both `captureWarnings(True)` and `warning('Test')` lines are commented out, `TypeWarning` gets issued, which is correct.

It seems like `captureWarnings()` hides some warnings in some cases.

This could be a problem in Python `logging` module, but I couldn't reproduce it without `typeguard`.

**Comment by agronholm** [comment]
I intend to replace the profiler hook with the import hook approach. As such, I'm not likely to fix any problems with `TypeChecker`.

**Comment by jolaf** [comment]
I'm not sure if this problem is connected to `TypeChecker`.
Probably it is in some general mechanism of issuing `TypeWarning`s.

**Comment by agronholm** [comment]
`TypeChecker` is the only component in typeguard that raises `TypeWarning`. The import hook just installs `@typechecked` decorators which raise actual exceptions.

**Comment by jolaf** [comment]
Maybe relevant to #85.

**Comment by agronholm** [comment]
Closing as `TypeChecker` has been removed in the 3.0 branch.
