### ISSUE TITLE
Add option for import hook to only emit warnings

### ISSUE THREAD

**Issue by jolaf** [agronholm/typeguard#85]
For now import hook checker throws `TypeError` when it thinks it has found an error.

So when import hook checker is used and some false positive occurs, the program crashes, and that prevents finding any actual problems.

However, the `TypeChecker` was configurable to issue warnings instead of exceptions, and that way the only problem with false positives was cluttering up the output log. However, even that problem could be effectively moderated with `warnings.filterwarnings`.

It would be nice for import hook checker to have the capability to issue warnings instead of exceptions the same way the `TypeChecker` does.

Without this feature the import hook checker is hardly usable for finding bugs in real-world complex applications.

**Comment by jolaf** [comment]
See #74, #75, #81, #83 as examples of false positives.

**Comment by agronholm** [comment]
I've added this feature in the `warnings` branch. Please review it when you have time.

**Comment by agronholm** [comment]
There is one practical problem. The modules modified by the import hook are cached using Python's internal mechanism. Typeguard already takes that into account and uses an explicit "optimization key" but this does not take the various options, like the switch to emit warnings or errors. Perhaps I should add a global for this?

**Comment by jolaf** [comment]
Can the import hook insert the object containing necessary configuration information INTO each module being imported, as a variable with special name, like, for example, `__TYPEGUARD`?

**Comment by jolaf** [comment]
Another potential option could be creating a specially named file that would be read in each case a problem is detected.

**Comment by agronholm** [comment]
If I insert such a configuration object into each module, then those too would be cached. How would this solve the problem?

**Comment by jolaf** [comment]
Well, I probably don't understand what kind of caching you are talking about.

**Comment by agronholm** [comment]
The kind of caching where Python saves the compiled bytecode to `__pycache__/modulename.cpython-XX.pyc`.

**Comment by jolaf** [comment]
Don't you have access to the module after it is imported, from cache or not? Can you then insert the actual data in both cases?

**Comment by agronholm** [comment]
Hm, I suppose you're right. I'll have to ponder this.

**Comment by kasium** [comment]
Hi,
I have exactly the same requirement to give the import-hook the capability to only emit warnings and not exceptions.
If this is only a matter of including a flag into the hook, I'm happy to contribute here.

**Comment by agronholm** [comment]
Typeguard has since added a decorator to exclude problematic functions from being type checked (`@typeguard_ignore`).

**Comment by kasium** [comment]
@agronholm thanks for the info.
Let me maybe add some more context for a possible use-case: Let's say you using typeguard in a high-available application and you have two landscapes: test and production. You could now enable typeguard  on test in error mode, but can leave it in warning mode for production. You still get all issues, but the users will still get their running application.

**Comment by agronholm** [comment]
This can be done in v3.0 with:
```python
from typeguard import config, warn_on_error

config.typecheck_fail_callback = warn_on_error
```
