### ISSUE TITLE
sphinx-autodoc-typehints: NameError: name 'ConcatOperator' is not defined

### ISSUE THREAD

**Issue by kingspp** [agronholm/typeguard#9]
sphinx-autodoc-typehints build fails due to the use of `@typechecked()` decorator

```python
from typeguard import typechecked

class ConcatOperator(Operator):
    @strict_type
    def __init__(self, ...):
        super().__init__(name=name)
        pass

    @typechecked()
    def create_operator(self, model_name:str, operator_id:int) -> 'ConcatOperator':
        self.model_name = model_name
        self.operator_id = operator_id
        self.validate()
        return self

    def validate(self):
        pass
```

[Stacktrace](http://pastebin.com/XiaNM4zs)

@agronholm Typeguard is a simple yet effective library. But the above issue still persists with the use of your lib for type checking

**Comment by agronholm** [comment]
How about you try without the decorator and use one of the other type checking methods instead?

**Comment by agronholm** [comment]
Also, seems like you didn't remove your `@strict_type` there in `__init__`?

**Comment by agronholm** [comment]
This is not a problem with typeguard so I'm closing it as invalid.
