### ISSUE TITLE
Difficult to use typeguard and MagicMock

### ISSUE THREAD

**Issue by prescod** [agronholm/typeguard#96]
Thanks for TypeGuard! I love it. Much better way to ease into type checking than MyPy.

I've found a workaround, but might it make sense to allow MagicMocks to pass type argument and return type checks (not necessarily programming isinstance checks)?

My workaround is a "Mockable" generic type. It kind of adds noise to the code, though.

**Comment by agronholm** [comment]
Sounds like a good idea.

**Comment by prescod** [comment]
There doesn't seem to be any such thing as a "Mock Object Protocol" and inheriting from Any isn't possible, so I propose to just add a check for 

isinstance(Mock)

before calling check_types in check_argument_types and in check_return_type.

Would you be interested in a PR of that sort?

**Comment by agronholm** [comment]
Yeah, it should be pretty easy to do as well. Make sure you add the appropriate test(s) as well.

**Comment by agronholm** [comment]
Closed via #105.
