### ISSUE TITLE
Inconsistent behavior when handling float/int

### ISSUE THREAD

**Issue by jsh9** [agronholm/typeguard#98]
I've found that the `int` type in `List[int]` is correctly enforced, but not the `int` type in `Dict[str, int]`. Here is an example to reproduce my observation:

```python
from typeguard import typechecked
from typing import Dict, List

@typechecked
def func(a: List[int], b: Dict[str, float]) -> bool:
    return True

func([1, 2], {'a': 1, 'b': 2.0})  # should have failed, but didn't
func([1, 2.0], {'a': 1, 'b': 2})  # failed, as expected
```

Is this behavior a bug, or a feature?

Thanks! (Btw, awesome package!)

(My Python version is 3.7.3.)

**Comment by agronholm** [comment]
This is not a bug. Typeguard is working correctly here. According to the [numeric tower](https://www.python.org/dev/peps/pep-0484/#id27) described in PEP 484, any `int` is also a `float`, but not vice versa.

**Comment by jsh9** [comment]
Thanks for the explanation!
