### ISSUE TITLE
New Protocol support in 2.7.0 breaks pytest-typeguard for some codebases

### ISSUE THREAD

**Issue by jtbeach** [agronholm/typeguard#99]
Hi there,

With my codebase I run tests with pytest-typeguard to catch runtime type errors -- when I try to upgrade in 2.7.0, I get the following errors with my Protocol subclasses because I would need to decorate them with `@runtime`. This is emitted by the `issubclass` check -- the metaclass for protocols implement a subclass hook. An example error is:

```
 TypeError: Instance and class checks can only be used with @runtime protocols
```

I went ahead and decorated my Protocol subclasses with this, but I then get further errors when I because subclass checking only works with Protocol subclasses where all members are callable. I have some where I have variables as well as methods. If I simply decorate with @runtime, I then get an error:

```
TypeError: Protocols with non-method members don't support issubclass()
```

One idea I had would be to use `isinstance` rather than `issubclass` in the check.

Note I use Python 3.7 and import `Protocol` from `typing_extensions`.

I'm happy to raise a PR if you could provide some guidance as to what you think the desired behaviour is here. At the moment, we can't use pytest-typeguard on our codebase in 2.7.0.

**Comment by agronholm** [comment]
I have a test that verifies Protocol support is working: https://github.com/agronholm/typeguard/blob/master/tests/test_typeguard.py#L1110
Can you suggest additional/better tests?

**Comment by jtbeach** [comment]
Yup, I can add some test cases here -- will do when I find some time in the next few days.

**Comment by jtbeach** [comment]
@agronholm Sorry about the delay -- honestly forgot about this one since we are pinned to < 2.7.0.

I pushed a minimal reproducible test case here: https://github.com/jtbeach/typeguard-protocols

Instructions for reproducing the failure are in the README. Essentially my use case is subclassing `typing.Protocol` to describe the interface expected by a function so that it can accept either a mocked object or the real object.

**Comment by agronholm** [comment]
Thanks. I'll have a look later and see if I can fix this for v2.9.0 which I plan to release soon.

**Comment by agronholm** [comment]
While typeguard still has no proper Protocol checks, at least you won't get false positives anymore.

**Comment by jtbeach** [comment]
Thank you!!
